### ISSUE TITLE
Factor lots of code common in pios

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1001]
Things that should be easy
- [x] pios_ppm
- [x] pios_pwm
- [x] pios_debug
- [x] pios_irq
- [ ] pios_usb_hid_pwr

Things slightly more than trivial but that should probably be done:
- [ ] pios_led

Things that are moderately difficult and should be considered or skipped:
- [x] pios_spi
- [ ] pios_iap
- [x] pios_wdg

**Comment by tracernz** [comment]
I'll get PPM/PWM when fixing them for timer res I guess.
