### ISSUE TITLE
pios_pwm/pios_ppm ignore timer resolution

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1003]
Since 12 MHz was originally introduced. This is a problem on targets which share a timer between inputs and outputs such as the CC3D, and a bigger problem with #958.

**Comment by mluessi** [comment]
@tracernz how about adding a "max clock" option to the timer config? It could be used to limit the timer clock of shared timers on CC3D.

**Comment by tracernz** [comment]
That would limit serial RX users to 1 MHz outputs unnecessarily though.

**Comment by mluessi** [comment]
@tracernz we could use a different timer init struct depending on the Rx selected.

**Comment by tracernz** [comment]
Might as well just scale to us properly based on the timer clock IMO. Would be easier and one less target-specific thing needed.

**Comment by mluessi** [comment]
Yeah, but isn't the problem of having a very fast running shared timer that it will cause a ton of overflow interrupts when it is also used for input?

**Comment by tracernz** [comment]
It's not compatible with SyncPWM at all, so we need only consider traditional PWM cases. 1500/1520 us servos/ESCs will be fine, and 760 us servos should be fine (400 Hz is the max rate for those currently). Brushed output is the problematic case, and it's pretty much incompatible. Either you have poor output resolution, or lots of overflow interrupts for the input.

**Comment by mlyle** [comment]
IMO this was adequately solved by #958.
