### ISSUE TITLE
Lux: Disable PPM if Serial RX configured

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1007]
#1000 restored the behaviour of always initing PPM on Lux. We could implement PIOS_RCVR_NumDevs() and if it returns >0 skip initing PPM. Should avoid issues with setup wizard/noise etc.

**Comment by mlyle** [comment]
Or just have a flag whether to run PPM.  There's nothing wrong with having multiple RXes.  (Also, does GCS receiver count?)

**Comment by tracernz** [comment]
Yah, that requires user action though -> support requests inbound. :-P

**Comment by mlyle** [comment]
;) ppm on/off doesn't sound so bad, to fix the rare cases where PPM is a problem. 

IMO it's mostly useful for developers.  You can put a solder glob over the whole jumper, and switch between serial RXes and PPM without concern (vs. where serial to PPM will create an interrupt storm).

**Comment by mlyle** [comment]
Ehhhh. No one's complainin'....
