### ISSUE TITLE
gps to 5 satt

### ISSUE THREAD

**Issue by DRUMSZ** [d-ronin/dRonin#1017]
- Seen in version (release version or githash): 
- On flight controller (if applicable): cc3d revolution mini

Issue details:
I know this has been addressed but anything new on this. ?
thanks and sorry for asking again

**Comment by mlyle** [comment]
The previous bug (#935) was closed as a duplicate of other issues.  This one will be too.

Feel free to ask for more details on forum, IRC, elsewhere...

**Comment by tracernz** [comment]
See #155 for the original issue and discussion.
