### ISSUE TITLE
UAVOMSPBridge sends altitude with wrong sign on F3/F4, Speed scaling wrong

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1023]
Sends PositionActual.Down as altitude, which is opposite direction to MSP protocol and what MWOSD expects. See ShikOfTheRa/scarab-osd#245

https://github.com/d-ronin/dRonin/blob/014d78244bc98f566394e4d8f56c1fe3ac202255/flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c#L461

MSP_RAW_GPS message specifies GPS_speed in cm/s whereas we send the value from GPSPosition.Groundspeed directly which is in m/s, needs multiplied by 100.

See MSP protocol spec: http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol

**Comment by dustin** [comment]
By opposite, do you mean the sign is just flipped?

**Comment by tracernz** [comment]
Yeah, AttitudeActual.Down is how far below our reference point we are, whereas MSP wants how far above.

**Comment by tracernz** [comment]
GPS speed is also not right.

**Comment by henn1001** [comment]
I knew i forgot something ...  never tested it myself as stated in #892 and then forgot it because of merge :/

**Comment by cpusmith** [comment]
Once the speed is fixed I'll test it.

**Comment by tracernz** [comment]
@henn1001 no prob, do you want to fix?
