### ISSUE TITLE
GCS not built with SDL support

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1065]
- [ ] The SDL support in the GCS makefiles looks exceptionally sketchy and requires too much build hackery to use...
- [ ] The build servers do not have SDL installed.
- [ ] The build does not happen with the proper options to use SDL.

Marking Samsara initially but this looks like a real pain to fix right.

**Comment by mlyle** [comment]
Not gonna make it.

**Comment by tracernz** [comment]
Probably best to use this when it's stable (looks like 5.8): https://doc.qt.io/qt-5/qgamepad.html

**Comment by mlyle** [comment]
Superseded #1535
