### ISSUE TITLE
GCS not detecting new devices

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#1078]
- Seen in version (release version or githash): 04bd9b38ef842cf3440ebcea6959777d246739a3 and latest release
- On flight controller (if applicable): sparky
- Mac OS X 10.11.5

Issue details:

I was helping someone with a sparky and consistently wasn't able to connect to a sparky that was plugged in after GCS was running.  We had two sparkys that worked fine, but only if I plugged the board in before starting GCS.  I could connect to each one only once (i.e. rebooting the board required restarting GCS).

Everything seemed to work correctly, except for having to restart GCS to connect.

**Comment by tracernz** [comment]
Yep, dup of #1048 and helped by #1075. This part remains to be fixed: https://github.com/d-ronin/dRonin/pull/1075#issuecomment-229858933. The USB stack has always been flaky, needs a lot of work next cycle and some patch-up to make it work well enough for this one.
