### ISSUE TITLE
Make StabilizationSettings.CameraTilt configurable in GCS

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#1085]
We need to make this configurable in the GCS. Forcing users to go to the UAVO browser to set the angle is not acceptable IMO.

**Comment by mlyle** [comment]
I do not think UI for a new feature should ever be a blocker.  And there are advantages for experimental things to be somewhat hidden at first release IMO.

**Comment by mluessi** [comment]
But we added the option to set Camera-Tilt based reprojection to the flight mode UI, so it's IMO not intuitive that we hide this option.

**Comment by tracernz** [comment]
If we have the option to enable it, doesn't make sense to not allow the angle to be set, given that it's a basic requirement for operation.
