### ISSUE TITLE
GCS:Welcome: Bad PNG

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1099]
One of the PNGs brought in by @mlyle has a bad colour profile, causing a warning when GCS starts.

**Comment by DTFUHF** [comment]
Addressed this issue with #1103 hopefully it works :)

**Comment by tracernz** [comment]
Sorry @DTFUHF, misdiagnosed this and it was actually https://github.com/d-ronin/dRonin/commit/8dfa22edf8fe5de92ef8db8a7ffffef5a8876e84
