### ISSUE TITLE
Remove Virtual Machine from wiki

### ISSUE THREAD

**Issue by jhitesma** [d-ronin/dRonin#111]
Anyone object to removing the virtual machine information from the wiki developer info pages?  It was out of date last time I tired it over a year ago and hasn't been updated since.

Unless someone wants to step up and build a new VM and actually maintain it we should just remove that stuff since it's just going to confuse people.

**Comment by mlyle** [comment]
No objections.  I think our focus should be on making build setup on an existing install easier.

**Comment by tgreer** [comment]
I'm all for removing it. Go nuts. Just close the issue when you're done :)

**Comment by jhitesma** [comment]
It's gone!
