### ISSUE TITLE
DSM + MotorInputOutputCurveMapping spills autotune points on F1

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#112]
GCS receiver + MotorInputOutputCurveMapping doesn't spill points
DSM + MotorInputOutputCurveMapping.B=1 doesn't spill points.

powf / expf must be made cheaper for these features to work well on F1.

**Comment by mlyle** [comment]
Just a thought-- may not be DSM, may be my use of MotorInputOutputCurveMapping / powf

**Comment by jihlein** [comment]
FWIW, I looked at the Naze code.  It's an easy fix to separate PPM and DSM.  Will work on getting a pr written and tested.

**Comment by mlyle** [comment]
:) Cool, thanks!

**Comment by mlyle** [comment]
Unfortunately running just SERIAL does not prevent spilled points.  The search continues.
