### ISSUE TITLE
BrainFPV in-flight reset

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1123]
- Seen in version (release version or githash): Build 455
- On flight controller (if applicable): BrainFPV

Issue details:
My son and I have experienced in-flight resets of the BrainFPV FC.  Initially I thought that it was a power issue to the FC, but it it happening randomly across 3 different quads.  Build 455 was used to see what the initial startup message is after an in-flight reset.  Screenshot attached.

![brain-reboot](https://cloud.githubusercontent.com/assets/7434287/16896857/dc51fd56-4b54-11e6-81e1-de7dc6e94631.png)

**Comment by ufoDziner** [comment]
BOOT: UNDEFINED appears to be the normal startup message as well.

**Comment by dustin** [comment]
Just to be extra clear, are you able to see this in the UAVO as well?  I
don't know why it'd be wrong, but if the UAVO disagrees, then it's a
different bug.

**Comment by ufoDziner** [comment]
Requested screenshots

![stackremaining1](https://cloud.githubusercontent.com/assets/7434287/16897859/93ae7776-4b74-11e6-9bb7-a17e156f1319.png)
![stackremaining2](https://cloud.githubusercontent.com/assets/7434287/16897858/93ad25ce-4b74-11e6-845e-82035dd80dcb.png)

**Comment by ufoDziner** [comment]
@dustin Where would I check for a uavo?

**Comment by dustin** [comment]
I can't quite remember which one it is (on my phone), but it's system
something and has a boot reason in it.

**Comment by mlyle** [comment]
SystemSettings.RebootCause I think.  Doesn't need a flight -- just is the startup reason.

**Comment by ufoDziner** [comment]
Normal startup screenshot.

![rebootcause1](https://cloud.githubusercontent.com/assets/7434287/16898418/b49d4fb0-4b8e-11e6-9bfa-72fe350feba3.png)

**Comment by mlyle** [comment]
Not awesome :/

**Comment by fujin** [comment]
#1126 should make it so we can see the proper reason now yea? @ufoDziner if you could upgrade to nightly tomorrow :sunglasses:

**Comment by mlyle** [comment]
fw_sparky2, static stack analysis (with my dodgy tools) on next:

```
>$ stabilizationTask                   456      312        7
```

vs tanto:

```
>$ stabilizationTask                   432      304        7
```

So stabilizationtask stack usage has increased by 24 bytes.

Other notable differences:  picoc task improved from 4536 to 4168.   Autotune task went from 864 to 872.     Loggingtask from 416 to 528 (!), ActuatorTask from 424 to 464.

**Comment by ufoDziner** [comment]
Copied from #1125 because I think it belongs here as well.:

My son flew 5 packs and I flew 4 on two different quads using build 459 that includes this PR with no issues. Funny thing is that I broke mine after the 4th flight, so I took out the backup quad that was still on 455 without this PR. Halfway through the first pack it rebooted. So, I'm pretty confident that the issue is fixed.

**Comment by ufoDziner** [comment]
Flew 2 more packs today, with no resets.

**Comment by mlyle** [comment]
Believed to be resolved.

**Comment by ufoDziner** [comment]
Had 1 in-flight reset, and 2 resets after a crash.  I don't believe that the crash was caused by the reset, but it's possible that they were.  The in-flight reset was with an OG brain using bfe4b825.  The 2 crash resets were with an RE1 was using 5f25d7d4.  "INDY WDOG" was displayed on the screen as the reboot reason each time.  These reboots happened somewhere mid-flight (I don't have an accurate time), but powered on for at least 5 min.
