### ISSUE TITLE
Output #1 set to 0/0/0 on update

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1127]
- Seen in version (release version or githash): 3e21fdf7
- On flight controller (if applicable): Brain
  Issue details:
  When doing an auto-update from e8170680 to 3e21fdf7, the values of Output #1 are set to 0/0/0 instead of 125/131/250 as they were prior to the update.  Outputs 2,3, and 4 are correct.  Screenshot and uav file attached.

![output1_missing](https://cloud.githubusercontent.com/assets/7434287/16903722/d27f8366-4c3a-11e6-9f18-89d2f078afe4.png)

**Comment by fujin** [comment]
from @ufoDziner:
[test_saved_backup.zip](https://github.com/d-ronin/dRonin/files/368181/test_saved_backup.zip)
