### ISSUE TITLE
OSX: breakpad catches EXC_BREAKPOINT

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1133]
This makes it incompatible with debugging generally, and causes it to crash the app immediately when starting a debug session through QtCreator.

**Comment by mlyle** [comment]
https://github.com/google/breakpad/blob/67649c61853108eb0c29703f6ff0db42e9d69f10/src/client/mac/handler/exception_handler.cc#L120

**Comment by tracernz** [comment]
So I want to just disable (or rather, not enable) crash reporter when a debugger is connected. There is some good Apple sample code in their docs but I could not find what license it came under. Any ideas where to find that info?

**Comment by mlyle** [comment]
https://developer.apple.com/library/content/qa/qa1361/_index.html   is the sample code in question.

You can't really copyright "how to invoke an API" so it's OK to use that as a reference IMO.

**Comment by mlyle** [comment]
Other sources:
https://books.google.com/books?id=K8vUkpOXhN4C&pg=PA734&lpg=PA734&dq=get+kp_proc+mac+os+x&source=bl&ots=OMjgSWZuYD&sig=FpyioyFpOxWumh55WvMDivCCo80&hl=en&sa=X&ved=0ahUKEwj9mPv-iPXZAhUIi1QKHVmfBLIQ6AEIUDAJ#v=onepage&q=get%20kp_proc%20mac%20os%20x&f=false

https://gist.github.com/s4y/1173880/9ea0ed9b8a55c23f10ecb67ce288e09f08d9d1e5

**Comment by tracernz** [comment]
Yup, this is one I can quite easily handle if you like (and one that's been a regular annoyance for me!).

**Comment by mlyle** [comment]
I love it when you handle things :D
