### ISSUE TITLE
BrainRE1 does not init BSS stuff in CCM-SRAM properly!

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1139]
This has triggered a bug on next with the new manualcontrol stuff, but---- probably triggers lots of undefined behavior elsewhere.

Putting it into Samsara.  We will have to hotfix.  Even though ill effects have not been observed on Samsara, tehy're surely there.

**Comment by tracernz** [comment]
Ick.
Nobody zeros it:
https://github.com/d-ronin/dRonin/search?utf8=✓&q=_cmm_start

How normal BSS is zeroed: https://github.com/d-ronin/dRonin/blob/080150a5b271fcfb3fe36aa1e20f92fc0d956aca/flight/PiOS/Common/Libraries/ChibiOS/os/ports/GCC/ARMCMx/crt0.c#L326

**Comment by mlyle** [comment]
For clarity, other targets have CCM and it actually comes up zero (though we should explicitly zero it to be "careful").

'446 doesn't have CCM, and we've moved some of the BSS away from the other stuff so it's not zeroed.. where it lands on other ram that has undefined contents on startup.

**Comment by mlyle** [comment]
While this is still super bad, closing in favor of just #1140 based on further understanding.

**Comment by mlyle** [comment]
reopened, because it is indeed bad.
