### ISSUE TITLE
Invalid version error when replaying log files

### ISSUE THREAD

**Issue by muratozkan** [d-ronin/dRonin#1160]
- Seen in version (release version or githash): 20160720.1
- On flight controller (if applicable): Openpilot Revo (using firmware for 20160720.1)

Issue details:

I enabled the logging module and downloaded the flight log file after a short flight. When loaded in GCS, GCS shows the following error:

`The log file was made with branch Release-20160409.2:b04a62e2 20160428, UAVO hash 02cf59ebb14892dc3e52c39c48f32b675361397a. GCS will attempt to play the file.`

<img width="1678" alt="screen shot 2016-07-30 at 12 32 43" src="https://cloud.githubusercontent.com/assets/3296168/17269500/c0deec92-5652-11e6-8170-9af2e4fe3828.png">

Then these messages appear: 
- `GCS cannot find the separation byte. GCS will attempt to play the file`
- `Timestamps are not sequential. Playback may have unexpected behavior`

I am using GCS on OSX Yosemite. Log file is attached.

Regards,

[dRonin-2016-07-30_12-11-03.drlog.zip](https://github.com/d-ronin/dRonin/files/391801/dRonin-2016-07-30_12-11-03.drlog.zip)

**Comment by mlyle** [comment]
Unfortunately, the GCS log playback is not the best.   It's not really useful, but also flight firmware and logs recorded with GCS have slightly different formats, and I don't think the GCS one understands flight logs well.

If you're familiar with the command line there's a new log viewing tool you can play with-- not quite finished but still useful.

Commands to get it on OSX should be:

```
pip install dronin[all]
dronin-logview
```

**Comment by mlyle** [comment]
@muratozkan PS if you try this please let us know how it goes-- whether good or bad.  Feedback on the log viewer tools would be really helpful, as I hope to ship them relatively soon.

**Comment by muratozkan** [comment]
Thanks for the reply @mlyle.

I've prepared a `virtualenv` with Python3 (3.5.1) and tried installing dronin. First, dronin-logview complained aboud `lxml` package not being present. Maybe you could include it as a dependency? 

I couldn't get PyQt4 or PySide installed, which are required by `pyqtgraph`. PyQt4 has no packages in pypi and PySide only supports Python up to 3.4 Is there a guide for setting up this package?

**Comment by mlyle** [comment]
Woops--- both on lxml (will fix) and pyqt4.  Pyqt4 is tricky because it includes the qt4 libraries and so doesn't fit into pypi so well.  

Personally I just use anaconda which includes everything (pyqt4 etc) except pyqtgraph.

I am also working on a pyinstaller-package of the log viewer, which works but is a little clunky (this is how we will probably officially release it)

**Comment by muratozkan** [comment]
Is there any WIP commit or branch regarding the installer? I'd be glad to help with that.

**Comment by mlyle** [comment]
Unfortunately I have not committed the spec file.. it's mostly makefile and jenkins-ci stuff to do now.

Current code in github works with pyqt5 which has wheels for python 3.

There is an interim package Windows at http://jar.lyle.org/~mlyle/logview.zip , too.

I've been working on flyingpi quite a bit but this is on my list to get onto our build server for the next release.

**Comment by mlyle** [comment]
Dup #1310
