### ISSUE TITLE
PiOS: SPI broken on F3

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1164]
Affects LUX and DTFc, and sadly they are both difficult to debug (DTFc has no debug connector, and LUX has an oddball one). They currently won't boot on next (Sparky1 does since it uses I2C). Broken in #1107.

**Comment by tracernz** [comment]
FlyingF3 would have been a nice platform to debug this. ;-)

**Comment by mlyle** [comment]
Was fixed by #1169.
