### ISSUE TITLE
Enabling Autotune causes boot fault

### ISSUE THREAD

**Issue by emaugain** [d-ronin/dRonin#1182]
- Seen in version (release version or githash): Samsara
- On flight controller (if applicable): CC3D

Issue details:
Recently when I try to enable autotune I follow the instructions to the letter
But when I reboot all my settings are wiped (hardware tab - ibus and mcp are reset) and I see a BOOT FAULT error

**Comment by mlyle** [comment]
CC3D doesn't have much ram.  Odds are you have other modules enabled (MSP on hardware pane? TxPid?  Sbus and PPM both at the same time unnecessarily?)
