### ISSUE TITLE
Quad size drops from saved autotune parameters

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1184]
- Seen in version (release version or githash): 20160720.1
- On flight controller (if applicable): 

Issue details:
When on the last "Details" page of the autotune submission, many of the fields maintain the information from the prior submission, but the quad size resets to 0.

**Comment by dustin** [comment]
We've been seeing the weight being sent up as the size.  e.g. two tunes here:  http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoPf6-AkM
