### ISSUE TITLE
Investigate MultiOSD Support

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1185]
Looks cleaner and more featureful than MWOSD, is cross-platform, and has a nice build toolchain setup. Might allow us to distribute binary OSD builds for easy installation. MSP support is WIP, UAVTalk and MAVLINK already done.
[MultiOSD](/UncleRus/MultiOSD)

**Comment by mlyle** [comment]
Marking WONTFIX.  It looks like MultiOSD development has slowed down, and these types of OSD issues have become much less important to us.
