### ISSUE TITLE
Logviewer crashes opening log file with one open

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1191]
- Seen in version (release version or githash): 
- On flight controller (if applicable): 

Issue details:
When opening a log file, with one already open, the logviewer crashes.  It starts to load the new one, then shuts down.

**Comment by mlyle** [comment]
This doesn't happen for me-- it may be running out of memory.  The issue fixed in #1211 probably wastes some RAM which doesn't help.

**Comment by mlyle** [comment]
closing worksforme pending new artifacts, etc.
