### ISSUE TITLE
GCS scaling issues at 3000x2000 resolution 

### ISSUE THREAD

**Issue by joeynuggetz** [d-ronin/dRonin#1193]
- Seen in version (release version or githash): Release-20160720.1: 20160723-74b7422c
- On flight controller (if applicable): Revo

Issue details:
Running GCS on Windows 10 Surface Book at native resolution of 3000x2000 exhibits some scaling issues. Also, the dialog boxes during automatic firmware upgrade process need to be resized in order to read the text properly. I don't have a screenshot of that however...
- Channel dropdown boxes only displays 6 characters 
- Font size for section headers appear much too small when compared to the rest of the text on the page. For example, the words "Calibration and Configuration Options" sort of seem unusually small.q

![image](https://cloud.githubusercontent.com/assets/14797846/17578678/9fafa298-5f51-11e6-9a13-a089b200b274.png)

![image](https://cloud.githubusercontent.com/assets/14797846/17578646/31d52f22-5f51-11e6-817d-7b6d58922bf8.png)

![image](https://cloud.githubusercontent.com/assets/14797846/17578803/8b8b1660-5f53-11e6-9497-c910b2ed090e.png)

**Comment by tracernz** [comment]
Note: Don't see these issues on OSX with Hi-DPI.

**Comment by mlyle** [comment]
Dup #533
