### ISSUE TITLE
(GCS) Scopes and Advanced icons appear on Welcome screen in Basic mode 

### ISSUE THREAD

**Issue by joeynuggetz** [d-ronin/dRonin#1194]
- Seen in version (release version or githash): Release-20160720.1: 20160723-74b7422c
- On flight controller (if applicable): 

Issue details:
When running GCS in Basic mode, the Welcome screen contains the Scopes and Advanced icons which do nothing when clicked. They should be removed when running a Basic install of GCS.

**Comment by tracernz** [comment]
Probably requires making the list of modes (in Core::ModeManager) available to QML.
