### ISSUE TITLE
There's code to integrate with the TL forum that should point at something of ours

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#12]
* [x] Autotune sharing
* [x] Forum panel on welcome screen
* [x] Crash dumps

**Comment by fujin** [comment]
Autotune, notably

**Comment by VArcht** [comment]
We could use my gist idea.

Have it post anonymous gists with a thumbprint that we can find back.

Then we can have a web page to search them by size, motor, whatever .

Can have a tau hall of fame, some peeps might like that... :)

**Comment by tracernz** [comment]
That would be quite cool actually. Gist for crash dumps would also be good.

**Comment by mlyle** [comment]
I never thought about gist for autotune.  That sounds nice.

**Comment by VArcht** [comment]
Yeah. crash dumps is where I first thought to use them but guil was afraid people would post fake ones to mess with him.

bonus, could replace this stuff with something sane like json https://github.com/d-ronin/dronin/blob/next/ground/gcs/src/plugins/config/configautotunewidget.cpp#L124

**Comment by mlyle** [comment]
While we're at it-- we should add pulldowns for vehicle size and how well it flew with the autotuned settings.. so we can search for good tunes for "200-300 size quads".

**Comment by VArcht** [comment]
yeah, nice to have known enums

**Comment by dustin** [comment]
#38 should hopefully be quick and easy.  We can own and query the data.  Maybe make a usable interface (I can make a non-usable interface to start).

**Comment by tracernz** [comment]
Nothing pointing at Tau Labs anymore.
