### ISSUE TITLE
RE1 LEDs randomly wrong color

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1208]
- Seen in version (release version or githash): Release 20170720.1
- On flight controller (if applicable): BrainFPV RE1

Issue details:
LEDs will be multiple colors on powerup rather than the selected color.

Example:
Color set to yellow for a bank of 8 LEDs.  On boot the first 2 were blue, 3rd magenta, next 5 yellow (I think that was the mix/order).

**Comment by mluessi** [comment]
I assume this can happen due to power sequencing when connecting the battery. I.e. the LEDs don't have full power, bc they need 5V and the RE1 starts earlier (3.3V), so if the power ramp is not very fast, the LEDs may not function properly. We should add a actual LED module that keeps updating the LEDs, then this shouldn't happen.

**Comment by mlyle** [comment]
Curious to know if any BOR fix helps this..

**Comment by mluessi** [comment]
@mlyle One way to fix this until we have a more proper RGB LED module could be to start a callback timer on boot so the LEDs get set again after 1s or so after boot. WDYT? Too much of a hack?

**Comment by AlessioMorale** [comment]
When working on ws2811 I had a lot of troubles with leds powered with slightly more than 5V. Looks like logic levels are referenced to supply voltage. a simple diode may do the job.

![image](https://cloud.githubusercontent.com/assets/1367650/18788915/0fa32f6a-81a9-11e6-8d99-fd126a12b36e.png)

**Comment by mluessi** [comment]
@AlessioMorale this should not be a problem on RE1, it actually uses a FET to generate 5V logic output for the LEDs.

**Comment by mlyle** [comment]
@mluessi -- I'm fine with an approach like this-- we have other modules that are callback-only effectively.  Should stay within the target for now.

But I'd also like to see appropriate BOD programming for RE1 as part of this release. 

We're supposed to be functionally complete today-- which we won't make-- but ASAP please.
