### ISSUE TITLE
Safety-Related  Motors spin when connecting battery

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1216]
- Seen in version (release version or githash): f1c776c9
- On flight controller (if applicable): DTFc

Issue details:
  While plugging in the battery on a few occasions the 2 back motors spun.  @mlyle suggested testing the "reboot" button in the GCS with the battery connected to see if they spin.  I tried this 3 times, and all 3 times at least one motor spun up, like it was armed then disarmed immediately.

**Comment by mlyle** [comment]
@DTFUHF What do you think of this?

**Comment by tracernz** [comment]
What kind of setup (e.g. Oneshot125?)? ESC firmware?

**Comment by ufoDziner** [comment]
Oneshot125, V-Good 30A with their latest firmware.

**Comment by tracernz** [comment]
Thanks, seems likely this isn't DTFc specific @mlyle. Sounds like TauLabs/TauLabs#1821...

**Comment by mlyle** [comment]
@tracernz yes, except we had #719 which cured it on sparky2

**Comment by mlyle** [comment]
@jihlein pointed out we spend longer in bootloader (500ms) on dtfc even though we have a sense line..  Which should be fixed.

**Comment by tracernz** [comment]
vsense is defined too :/ https://github.com/d-ronin/dRonin/blob/next/flight/targets/dtfc/board-info/board_hw_defs.c#L838. @DTFUHF Why the 500 ms delay?

**Comment by DTFUHF** [comment]
@tracernz @jihlein probably copypaste fail. Changing to 2 (like sparky1) sounds OK to me.
