### ISSUE TITLE
flyingpi: easy to lose configuration data

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1227]
- Seen in version (release version or githash): 51bfc90ea
- On flight controller (if applicable): flyingpi

Issue details:
Haven't tracked this down yet.  Have lost configuration objects a few times.  My theories are:
1. We don't commit things to "flash" robustly, and it's possible when I unceremoniously drop power on the pi filesystem data is getting lost.
2. This is TCP telemetry-- could be a bug.
3. Could be a bug with GCS object saving state machine.
4. Could be a bug with uavo browser.

**Comment by mlyle** [comment]
OK.  I still believe there's probably a problem, but I just realized that I was running the program from two different directories / two different theflash.bin's.--- and that certainly some of the failures came from that.

**Comment by mhv-shared** [comment]
I think this happened to me - I flew an autotune without GCS connected, but when I landed and connected the prompt to apply did not come up. I restarted the simulator (without powering down the pi) and the prompt came up, but my input settings had been lost.

**Comment by mlyle** [comment]
The flush operations introduced fixed this.
