### ISSUE TITLE
OSD: RSSI Displays Unhelpful Number on Failure

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#1232]
On Samsara, OG Brain, I've got OpenLRS feeding SUMD into the FC and sending RSSI over channel 9.  When I go into failsafe, channels go to 0xffff and the OSD displays 4754 instead of something more helpful.

(Well, in addition to something more helpful, since it also shows `MAN:NO RX`)

**Comment by tracernz** [comment]
Should only print 3 digits? https://github.com/d-ronin/dRonin/blob/next/flight/Modules/OnScreenDisplay/onscreendisplay.c#L1347

**Comment by mlyle** [comment]
If the RSSI channel is a receiver error condition it should read 0, too..
