### ISSUE TITLE
Quixote Errata/Notes

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1243]
Some notes so we don't forget later...
- MSVC builds use Windows 8.1 SDK, which supports only Windows Vista or later. Only workaround to get it running on XP would be to build Qt ourselves with XP support (http://xpam.pl/blog/?p=106). Not worth it for a 15 year old EOL OS.

**Comment by mlyle** [comment]
>  Not worth it for a 15 year old EOL OS.

Looks like only 36 user records on XP.

**Comment by mlyle** [comment]
Added to errata
