### ISSUE TITLE
New users usually don't configure rates; usability help; controls "level up"

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1248]
Proposed solution:

```
20:59 < icee> A) we do expoM this cycle.
21:00 < icee> B) we have 3 parameters.. 'maximum rate', 'center stick rate', and 
              'stick break point'
21:00 < icee> and show a nice graph
21:00 < icee> C) we force people to review it as part of autotune wizard
21:00 < icee> D) we leave leveling defaults alone
21:01 < icee> E) we move this stuff ABOVE pids on teh stabilization basic pane.
21:01 < icee> F) we kill the horizon rate visualization graph
```

connects #108

**Comment by mlyle** [comment]
Review needed for the interface given to set rates---

https://www.desmos.com/calculator/ytix9ao0kd   is the 3 sliders I propose to give for an axis.

**Comment by jhitesma** [comment]
I like the demo.  Would be nice to have a display that shows what the effective rate is numerically at various stick settings without having to read the graph.  Or at least a clearer indication of what center stick rate is.  

I like graphs for a quick "gut feeling" check, but hard a hard time relating them to how things actually feel in practice.  I'd almost rather have a chart showing stick percentage and rate at various points than a graph.  But I also accept that most people like graphs.

The three sliders do make a lot of sense and seem easy to use.

**Comment by mlyle** [comment]
I don't know how to describe or name center stick rate well.

It's "if the whole stick was linear at this slope, how many degrees/second you'd be asking for at full-stick travel".

That is, if you set center stick rate to 150, the middle of the stick, until you hit the transition region, acts like you had configured 150 deg/s with no expo.
