### ISSUE TITLE
Consider updating to Qt 5.5.1 or 5.6

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#126]
Even if we decide not to follow Qt 5.6, staying up-to-date on the 5.5 branch is still a good idea. Relevant changes:
- http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.5.1
   * [QTBUG-46379] Tooltips on OS X are now transparent for mouse events.
 - [QTBUG-47775][Darwin] Fixed Info.plist creation when bundle name
   contains spaces.
 - ?
- http://code.qt.io/cgit/qt/qtquickcontrols.git/tree/dist/changes-5.5.1
- ?
- http://code.qt.io/cgit/qt/qtserialport.git/tree/dist/changes-5.5.1
   * [QTBUG-46875] Fixed crash while enumerating available ports
     on OS X 10.10
   * [QTBUG-47127] Available serial port information is not duplicated
     anymore on Windows.
- https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/dist/changes-3.5.1.md?h=3.5
 * Fixed crashes with code completion (QTCREATORBUG-14991, QTCREATORBUG-15020)
 * Added support for MSYS2 compilers and debuggers

**Comment by jhitesma** [comment]
So I've apparently been building with 5.5.1 on windows all week inadvertently and haven't noticed any issues (other than the one command missing a .exe extension when building standalone from #119 - but that issue doesn't exist building just gcs or building release.)

![gcs_ver](https://cloud.githubusercontent.com/assets/2054286/11609345/9c53d080-9b41-11e5-8bb0-21c48781ace1.jpg)
