### ISSUE TITLE
GCS: need to make it obvious not to use non-delay arming modes

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1266]
This is a big source of support overhead and user frustration.  Needs a fix for Quixote.

**Comment by tracernz** [comment]
Is it feasible to remove them? I guess they could be useful for ground vehicles.

**Comment by mluessi** [comment]
I don't see a harm in removing them. For a ground vehicle, always armed could be an option and delay shouldn't hurt either.

**Comment by mlyle** [comment]
Non-delay modes are useful for aircraft which are not likely to be static during arming-- e.g. perhaps planes.  But I think the tab can be adjusted be be nicer.

**Comment by tracernz** [comment]
We could also consider hiding the non-delay options for multis. If anyone really wanted them they can use the UAVO browser.

**Comment by mlyle** [comment]
Here's what I'm thinking of:

![http://i.imgur.com/xs4qpkv.png](http://i.imgur.com/xs4qpkv.png)

**Comment by tracernz** [comment]
I think the "Arming Settings" box is better but the options are still much too confusing for somebody new to us... I'll whip something up when I get home tonight to see what you think. I like the "Disarming Settings" box, especially the separate failsafe and idle timeouts. I'd change the text for the idle timeout to "Automatically disarm if throttle is low for:" though, to match the other two. Also, it would be nice to hide everything that is inapplicable e.g. when switch arming is selected.

**Comment by mlyle** [comment]
Connects to #447

**Comment by mlyle** [comment]
While I'm sympathetic / hope we can get this perfect.. I'm happy with anything easy to implement that reduces the rate of end-users running into this problem by, say, 50%.
