### ISSUE TITLE
Tools: Build Breakpad from source

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1268]
Problematic due to requirement for Google depot tools.

**Comment by mlyle** [comment]
I think .. just having the corresponding source and binaries somewhere in a github repo .. plus any obvious bits of procedure for reproducibility.. would fix #1267

**Comment by tracernz** [comment]
Ohhhhhhh, I thought #1267 was about the symbol files and the debug information they're generated from! :laughing:

**Comment by tracernz** [comment]
You can close this as a dup if you like.

**Comment by mlyle** [comment]
:) dup #1267 (but with better explanation)
