### ISSUE TITLE
About GCS crashes on windows on latest next

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1282]
Whiskytango.  Maybe something to do with MSVC.

**Comment by jhitesma** [comment]
Just experienced this on the expoM build and mentioned it in another issue.

**Comment by tracernz** [comment]
I get a QList out of range assert failure. This is the thing I suspect https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/coreplugin/versiondialog.cpp#L67lL68

Latest gcsversioninfo.h on Jenkins:
http://jar.lyle.org:8080/job/dronin/Nodes=osx/ws/build/ground/gcs/gcsversioninfo.h

Example:

``` c
#define GCS_REVISION_PRETTY "(HEAD detached at a0e399a)%@%20160903-a0e399a6"
```
