### ISSUE TITLE
opengl init not working on windows software accelerated env

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1284]
reported by @jhitesma 

![image](https://cloud.githubusercontent.com/assets/90903/18223175/815021aa-7163-11e6-8dde-b8f5f15aa448.png)

**Comment by tracernz** [comment]
Unfortunately can't repro this running under RDP (RDP requires ANGLE/GLES).

**Comment by mlyle** [comment]
No repro, but not ready to close either.

**Comment by jhitesma** [comment]
Any benefit to me trying a more recent build?  I assume nothing has changed but haven't tried to repo with any newer builds in a few weeks.

**Comment by mlyle** [comment]
Nothing has changed.

How much RAM do you have?  I wonder if that is really an out-of-memory error.

**Comment by jhitesma** [comment]
That machine only has 4G, and it's hurting.  I could try with everything else shut down to see if it works then.

**Comment by mlyle** [comment]
Would be helpful to see if it cures it-- then we could easily close this.

**Comment by jhitesma** [comment]
Just tried it with everything else shut down (even chrome's background stuff) and same error.

Watching Taskmanger my memory usage never went past 56% 
So doesn't look like a memory issue. 

The video card on this computer is old enough that there aren't official drivers for it for W10 so I'm not surprised it's having issues related to video.

**Comment by tracernz** [comment]
Playing with different Qt OpenGL backends a bit... GLC_Lib doesn't play nice with any except the software one. Will be good to get rid of it soon (WIP) and then we can probably fix this quite easily.

**Comment by mlyle** [comment]
Still broked-- too bad

**Comment by tracernz** [comment]
#1540 should be interesting.

**Comment by tracernz** [comment]
This was fixed for @jhitesma by https://github.com/d-ronin/dRonin/pull/1540

**Comment by mlyle** [comment]
Not seen in 5ever
