### ISSUE TITLE
The Modules tab sometimes warns about changed settings that aren't saved yet

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1289]
- Seen in version (release version or githash): http://jar.lyle.org:8080/job/dronin/577
- On flight controller (if applicable): AQ32

Issue details:

However, I haven't changed any settings.
Just reproduced it, I think: It is when you are at the Modules tab, and unplug and replug the board. Try to change to another tab, and the GCS warns.

**Comment by cpusmith** [comment]
Yes, I see this as well in the Samsara .1 release but have been ignoring it.
