### ISSUE TITLE
Autotown calculates yaw values whilst the GCS isn't

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1301]
- Seen in version (release version or githash): http://jar.lyle.org:8080/job/dronin/589/
- On flight controller (if applicable): AQ32

Issue details:

The GCS says it can't calculate the yaw values, however autotown does.
Are they using different calculations? 

I am not sure if it's actually an issue, or by design.

**Comment by mlyle** [comment]
Autotown's threshold for refusing to calculate yaw values is different, like I said on IRC.

Autotown is a nice to have / developer tool.  It doesn't need to exactly match.

**Comment by yamahabest** [comment]
Fair enough, but are the values from autotown usable, or should I stay far from them?

**Comment by mlyle** [comment]
The output is currently the same, but the conditions on which they are displayed is different.
