### ISSUE TITLE
RE1 bootloader-- how does it work?

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1320]
Doesn't it use the '405 linker scripts/memory map/startup code?  Are we just getting incredibly lucky that it doesn't fail?

**Comment by tracernz** [comment]
F4 linker scripts are messy too. BL uses a different set to BU/FW.

**Comment by tracernz** [comment]
It works because BL doesn't use CCM RAM I guess? And it only uses the beginning of the flash. Pretty dodgy.

**Comment by mluessi** [comment]
Other than the linker script, what is wrong? The clocks get set up by `cmsis_system.c` in the board info dir. Are there other files that should be different for RE1 than for F405 targets?

**Comment by mlyle** [comment]
I don't know.  The linker script/memory layout is definitely wrong at minimum.  Are register maps for all peripherals we touch right, etc?

**Comment by mluessi** [comment]
The register maps should be correct; they are selected by defining `STM32F446xx` vs `STM32F40_41xxx` for F405 targets. This is done correctly in the BL and the BU makefile. I will look into selecting the correct linker file for the BL/BU.
