### ISSUE TITLE
GCS:Stab Tab: Tweaks to basic page

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#133]
We should add derivative to the basic page and give it a suitable scaling. This is a good page for ex-MultiWii users with this change. 

Should also review the limits as most people report that autotuned integral gains show up red.

Also to consider:
* Add full stick rate and expo.

**Comment by mlyle** [comment]
Maybe boost the limits some.  Boring craft they're still normal-- it's just when you have crazy-high bandwidth that the integral is so big.

**Comment by jhitesma** [comment]
I was going to suggest adding stick scaling/expo but that would add a lot more to the page leaving it not very different from advanced other than the scaling/interface.  So I'm tempted to suggest just ditching basic all together.  

Reason I suggest it is it's something that confused me coming from *flight and other people I've got to try Tau over *flight have been confused by it.  Increasing "rates" is one of the first things they tend to want to do and hiding it on the advanced tab just seems like we're burying important functionality.

The whole Basic/Advanced/Expert separation just feels kind of arbitrary to me.  Maybe it's just me though.

**Comment by tracernz** [comment]
The scaling is the important thing. People don't deal well with a gain of 0.00000543.
