### ISSUE TITLE
max7456 support on aq32 and revolution

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1332]
For Airbot F4 board with integrated OSD, etc.

Currently in mpl-7456 branch

cc @dustin 
- [ ] Get the targets to turn it on and off appropriately in hw settings
- [ ] Confirm playuavosd still works
- [ ] Download fonts to '7456.
- [ ] Make the OSD widgets do actual OSD-ish things

**Comment by dustin** [comment]
What's special about AQ32?

**Comment by mlyle** [comment]
AQ32 has an external SPI "OSD" port that the users have hooked max7456 boards to in the past.  If we can secure testing (@yamahabest ? ) it would be nice to support this.

**Comment by jihlein** [comment]
The AQ32 external SPI port was used to drive this:

https://www.sparkfun.com/products/retired/9168

Not sure if anything like this is still available or not.

**Comment by mlyle** [comment]
Yup, on AQ32 it'd be purely for existing users (and to get additional early OSD help/feedback).

**Comment by yamahabest** [comment]
Sure, I can test this. I just have to plug it in again.
I am using the Sparkfun version.

**Comment by yamahabest** [comment]
This one seems to be available still: http://www.hobbytronics.co.uk/max7456-osd-breakout

**Comment by yamahabest** [comment]
Whilst this is nice, why is this going to be supported?
With those MinimOSDs and the PlayUAV OSD support on its way, are there still people interested in this?

**Comment by mlyle** [comment]
@yamahabest there are flight controllers coming out with '7456 on the board, as stated above, which require no additional components for OSD if we add software support.

**Comment by yamahabest** [comment]
Ah, sounds good, thanks.

**Comment by mlyle** [comment]
We also talked about it on IRC before, I think... saying that I'd support it because of those boards... :P

**Comment by yamahabest** [comment]
Ehhh.. Could be, yes. Let me know when I can test something.
