### ISSUE TITLE
Naze32 gets "would you like to upgrade" notice...but can't

### ISSUE THREAD

**Issue by jhitesma** [d-ronin/dRonin#1334]
- Seen in version (release version or githash): Samsara.1
- On flight controller (if applicable): Naze32

Issue details:
When connecting GCS correctly identifies an old release and gives the usual "would you like to upgrade" notice.  But selecting upgrade just kind of quietly fails without doing anything since Naze32 doesn't use our bootloader.

Would be nicer if we could detect Naze32 and give a message like the pre-autoupdate message warning that it's out of date and needs to be updated but explain that it should be done manually.  

The silent failure mode could be confusing for users.  I know Naze32 is ultra limited and sucks...but it is our 3rd most popular target so it may be nice to fail more gracefully.

**Comment by mlyle** [comment]
already fixed in 90b5eb32f0f
