### ISSUE TITLE
Import UAV settings process gives no progress feedback to the user

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1348]
- Seen in version (release version or githash): -
- On flight controller (if applicable): -

Issue details:
After selecting a file to import, it start importing. However, there is no progress feedback to the user, and the GCS seems to hang.

Importing itself works fine though.

**Comment by mlyle** [comment]
Is this actually slow for you?  When I import a .uav file it's close to instant..

**Comment by yamahabest** [comment]
Let me check again.

**Comment by yamahabest** [comment]
Not reproducing anymore, maybe it was in my local build version.
