### ISSUE TITLE
Possible to have multiple instances of the GCS running, causes issues

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1371]
- Seen in version (release version or githash): -
- On flight controller (if applicable): -

Issue details:
It is currently possible to have multiple instances of the GCS running at the same time, which causes issues during auto-upgrade and stuff.

Possible fix: Check against a shared object (named mutex/file/etc), or check for processname when starting a GCS. When it is not there, continue startup. When it is there, abort start.
Same could be used for the installer.

**Comment by mlyle** [comment]
Fixed in #1477  :D  Nice to hopefully not run into this anymore
