### ISSUE TITLE
Receiver Type and Mode on RE1 image

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#1398]
- Seen in version (release version or githash): Quixote
- On flight controller (if applicable): RE1

Issue details:
  Win 10, Hardware tab, Receiver Type and Mode are on the image.

![screenshot](https://cloud.githubusercontent.com/assets/7434287/19090902/50c09aa2-8a35-11e6-94dc-24373f826fc1.png)

**Comment by mluessi** [comment]
@ufoDziner what's your screen size? I can see that when I make the window quite small on my screen.

**Comment by mlyle** [comment]
@mluessi you should drop a scroll widget in (and move messages up to be more visible)

**Comment by ufoDziner** [comment]
@mluessi 11" 1366x768

**Comment by mluessi** [comment]
@ufoDziner please test #1399 once the artifacts are built. I was only able to test it on Linux

**Comment by ufoDziner** [comment]
@mluessi Works great!  Thanks!
