### ISSUE TITLE
Flight[ChibiOS]: Clock init is ineffective since PLL is running after bootloader

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1454]
ChibiOS function `stm32_clock_init` attempts to setup the PLL, assuming that it is inactive. PLL is usually already activated by the bootloader when we jump to firmware. Writes to PLL configuration registers are ineffective when the PLL is active. 

Low priority since, as long as the bootloader clock configuration matches firmware, everything will be fine.

Relates to #1448.

**Comment by mlyle** [comment]
Yes.  Arguably this is WONTFIX/SHOULDNTFIX.

Question is, is there an anticipated benefit from de-initing the PLL?  I'm not even 100% comfortable with toggling back to internal clock and then back to PLL.

**Comment by tracernz** [comment]
The best thing I think would be to properly integrate ChibiOS so it shares ALL of the same clock/PLL settings/headers as the bootloader. That will minimise the chance of anything bad happening due to this.
