### ISSUE TITLE
RE1 crashes immediately upon providing S.bus input

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1492]
Reported by user on next; confirmed on seppuku branch.  Don't know if it was the LED changes or what.

**Comment by mluessi** [comment]
Did some tests: I can run the setup wizard until the point at which the sticks have to be moved to the maximum extents, then the FC resets. Doesn't seem to be related to #1488, as I can also reproduce it using the version before it merged (d74c5701a).

**Comment by mluessi** [comment]
Couldn't reproduce it on sparky2

**Comment by mlyle** [comment]
Yah I've been flying next a fair bit (but not on RE1) without issue.  Can try a little to bisect later today.

**Comment by mluessi** [comment]
The ManualControl stack was overflowing by 100 bytes. Bump it by 200 bytes? Not sure what caused the stack increase.

**Comment by glowtape** [comment]
Must have happened past November 30. I have a next build of that date on my RE1-quad and am using S.Bus without any issues.
