### ISSUE TITLE
Sparky2:Pathplanner:Setting a preprogrammed path (box) causes reset and setting not saved

### ISSUE THREAD

**Issue by pug398** [d-ronin/dRonin#156]
On every attempt Pathplanner can be enabled and put on switch but when 10M box is selected and saved fc resets and setting not saved.

**Comment by pug398** [comment]
Still having this problem on Sparky2. Enable PathPlanner module. Put PathPlanner on switch. Reboot. Set system>settings>PathPlannerSettings>PreprogrammedPath>10mBox and save. Board resets and setting is lost. Can anybody repro on sparky2 or another fc?

**Comment by mlyle** [comment]
I can't reproduce.

Note the way the UAVO browser works is really janky though.. You need to click on something else inside 'pathplannersetings' after selecting that value before clicking the disk to save.  Else it doesn't pay attention to the value you selected in the pulldown.

**Comment by pug398** [comment]
Interesting. I just repro'd it on a new sparky1 just out of the bag. 
I will double check to see if it is something wonky I am doing...
