### ISSUE TITLE
Consider asserting/hanging on flash errors / ERRIE

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1562]
As discussed / reported by @mindnever / #1560 --- if we have a null dereference bug we access flash, with undefined behavior.

If it's a write, it just doesn't happen, but also sets the flash error flag.  This causes us to hang on future flash programming operations (e.g. saving a config item).

It would be more helpful to crash immediately, because 1) we'd spot more bugs, and 2) the actual failure/crash would be more proximal to the actual problem code.

Also it's the eeriest flag.

**Comment by tracernz** [comment]
Kind of annoying that ST choose 0x0 as the program memory remap. :/ I guess it would actually write (over your code!) if you were running from RAM rather than flash?

**Comment by mlyle** [comment]
@tracernz It's ARM's fault, since the initial vector table is at address 0.  A common choice, really, that happens to be super bad for c.  You could make the choice to mask writes to the remapped addresses, though.

And yes, it even risks writing to flash if we've happened to unlock programming, etc.
