### ISSUE TITLE
Lists on the Authors screen are empty

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1563]
* Seen in version (release version or githash): Artifice Preview
* On flight controller (if applicable): 

Issue details:
GCS logs the following errors:

21:40:18[WARNING] QFSFileEngine::open: No file name specified
21:40:18[WARNING] QTextBrowser: No document for c:%5CProgram Files (x86)%5CdRonin%5Cshare%5C%5Cgcsrelauthors.html
21:40:18[WARNING] QFSFileEngine::open: No file name specified
21:40:18[WARNING] QTextBrowser: No document for c:%5CProgram Files (x86)%5CdRonin%5Cshare%5C%5Cgcsauthors.html

Files are indeed not in that path, or any other path. Probably not included in the installer?

**Comment by DTFUHF** [comment]
can reproduce on windows

**Comment by tracernz** [comment]
Sigh https://github.com/d-ronin/dRonin/blob/next/package/winx86/dronin.nsi#L168
Any reason that shouldn't just copy the entire share directory?
