### ISSUE TITLE
OSD: Default custom text on Seppuku is 'BrainFPV'

### ISSUE THREAD

**Issue by DTFUHF** [d-ronin/dRonin#1564]
* Seen in version (release version or githash): artifice preview
* On flight controller (if applicable): all with OSD

Issue details:
OSD 'Custom Text' defaults to BrainFPV, which is not appropriate for Seppuku and presumably PlayUAV, even if Custom Text is disabled by default

**Comment by yamahabest** [comment]
Can probably be closed, since the PR is already closed: https://github.com/d-ronin/dRonin/pull/1565

**Comment by mlyle** [comment]
thx .  fixed #1565
