### ISSUE TITLE
Sparky2 WS281x Support

### ISSUE THREAD

**Issue by Cro2230** [d-ronin/dRonin#1578]
* Seen in version (release version or githash): 
* On flight controller (if applicable): 

Issue details:
Will next release "Artifice" support WS2811 LEDs for Sparky2

**Comment by yamahabest** [comment]
Hi, it would be better to ask this on the forum: https://forum.dronin.org/forum/.

However, I don't think there is support for ws2811 leds on Sparky in the upcoming release.

I would say the following have support right now:
- Seppuku
- BrainRE1
- Quanton
- Revolution

**Comment by mlyle** [comment]
I agree this should go to the forum. 

Currently no sparky2 ws2811 support.  Someone would need to step up to implement and/or test it, and what pin is correct for it would need to get figured out.
