### ISSUE TITLE
Seppuku: OSD Vsync issue can cause OSD crash FC WDOG reboot

### ISSUE THREAD

**Issue by LitterBugs** [d-ronin/dRonin#1588]
* Seen in version (release version or githash): 4721d629
* On flight controller (if applicable): Seppuku

Issue details:
Under the right lighting conditions, OSD looses vsync with camera or switches from NTSC to PAL and disappears.  Four seconds later the FC reboots.  This looks to be similar to the issue we had with the RE1.

I can reproduce this with the sun in the upper right corner of the screen.

EDIT: Add Build Details
RMRC Hellbender 204 V1 frame
Seppuku pre-release test FC/OSD
TBS zero/zero camera
RMRC cricket 200mw VTX
Omnivision 3 lobe RHCP antenna
BrainFPV mPB PDB
Speedex ES 25A   OS125
Spektrum FPV Racing diversity RX
Sunnysky x2204s-16 2300kv motors
DALPROP 5045 triblade
Tattu 1550mah 4S 75C

screen grabs from video:

Just before OSD glitch
![justbeforeosdloss](https://cloud.githubusercontent.com/assets/22078840/23107157/fcc5dbd0-f6c5-11e6-9a14-7a8c029f6fb4.jpg)

OSD format shift
![justbeforeosdloss2](https://cloud.githubusercontent.com/assets/22078840/23107160/0371bc6a-f6c6-11e6-91fb-8fddff5388e0.jpg)

OSD Loss
![osdloss](https://cloud.githubusercontent.com/assets/22078840/23107161/0b011980-f6c6-11e6-97d5-62e365f2ab8b.jpg)

WDOG after FC rebooted in flight
![wdog](https://cloud.githubusercontent.com/assets/22078840/23107163/1128da14-f6c6-11e6-9ac4-8d26c04d299d.jpg)

Two videos demonstrating the issue
https://youtu.be/EOTPI6e50Zo

https://youtu.be/BubItLA9I7U

**Comment by LitterBugs** [comment]
Just received released board.  Going to retest on the "official" board.

**Comment by mlyle** [comment]
I'm just back from vacation now and am thinking about this.

Seppuku isn't vulnerable to the same things that RE1 was in this area.

But all three of the graphic OSD boards employ the same approach-- try to clamp video to a correct DC level, compare to a (dynamic or static) threshold, and then that fires interrupts that do stuff on the FC.  If the bias level drifts from extreme levels the thresh level can start hitting other features on the video signal which creates an interrupt storm and ties up the FC from doing other things.

I don't know if you have a scope but it would be interesting to know the p-t-p levels your camera is outputting-- if they are very high ( >2 V peak-to-peak) it would be interesting.  It looks like you're using a CCD camera from the types of bloom artifacts you're getting on bright light so that's interesting too.

There are some defenses to this type of situation I've been wanting to implement for awhile.  @mluessi long ago on original brain implemented a quick return from the vsync interrupt when it arrives too early (and this logic is used on Seppuku), but it would be better to disable the interrupt entirely and then enable it when it is reasonable.

Doing that "right" will take some thought / a little time.

**Comment by LitterBugs** [comment]
Grabbed some shots off the scope of the TBS ZeroZero signal with various lighting.  Have not been able to get it to reboot on the table yet.

Lens covered:
![cameraoutlenscovered](https://cloud.githubusercontent.com/assets/22078840/23582108/0e7fb014-00f1-11e7-841f-4dedad5da3ef.jpg)
Normal scene:
![cameraoutnormalscene](https://cloud.githubusercontent.com/assets/22078840/23582116/256fc96c-00f1-11e7-80e6-9a9b979fbffa.jpg)

Bright Light in center of screen:
![cameraoutbrightlight](https://cloud.githubusercontent.com/assets/22078840/23582118/33f9bb14-00f1-11e7-86d0-56e292bc215d.jpg)

Bright light in upper right of screen:
![cameraoutbrightlightupperright](https://cloud.githubusercontent.com/assets/22078840/23582121/46b1f3c0-00f1-11e7-9d01-7ac03abdbce5.jpg)

Hope to get out to the field tomorrow....

**Comment by mlyle** [comment]
@litterbugs -- I've passed lots of bad video to Seppuku of various forms and cannot reproduce.  Have you had any luck?

**Comment by LitterBugs** [comment]
Mike,
Just gave it another shot with a flashlight on the bench and was able to 
duplicate a reboot unarmed.

Karl

**Comment by LitterBugs** [comment]
Seems to happen when there is a vertical line lens flare and it crosses the right edge of the screen.  Here are some screengrabs from the 2nd video I posted at the time of the reboot.  I was able to duplicate this scenario with a flashlight close to the camera.  I'll try to get it on DVR, and also see if I can rig my scope up to capture the raw video.

![crashb01](https://cloud.githubusercontent.com/assets/22078840/23839306/7008c752-0773-11e7-868d-5915e2800050.jpg)
![crashb02](https://cloud.githubusercontent.com/assets/22078840/23839305/70045bc2-0773-11e7-8c0b-31cc32313553.jpg)
![crashb03](https://cloud.githubusercontent.com/assets/22078840/23839303/7003edf4-0773-11e7-8401-a5fe82731461.jpg)
![crashb04](https://cloud.githubusercontent.com/assets/22078840/23839308/700b718c-0773-11e7-803f-a6e84fe3d25b.jpg)
![crashb05](https://cloud.githubusercontent.com/assets/22078840/23839304/70042828-0773-11e7-9251-a44d0ae11897.jpg)
![crashb06](https://cloud.githubusercontent.com/assets/22078840/23839307/700ae74e-0773-11e7-88dc-56693b434aff.jpg)
![crashb07](https://cloud.githubusercontent.com/assets/22078840/23839309/70173da0-0773-11e7-98cd-644e7e035046.jpg)

**Comment by LitterBugs** [comment]
Was able to duplicate on table again.  This time lens flare in center of the screen was able to trigger.

https://youtu.be/hkfNiIBXTcU

**Comment by LitterBugs** [comment]
Single stepping through the frames just before the OSD droppout, I noticed that this time there was a "Sensors" alarm this time that did not happen on the previous times.  One other thought, could it be possible that something on the FC is photo sensitive?

![crashc01](https://cloud.githubusercontent.com/assets/22078840/23854740/22ad80be-07c9-11e7-9bc0-2c272532fdea.jpg)
![crashc02](https://cloud.githubusercontent.com/assets/22078840/23854741/22afaa56-07c9-11e7-9d35-41565dabe578.jpg)
![crashc03](https://cloud.githubusercontent.com/assets/22078840/23854743/22bc713c-07c9-11e7-9f35-97a8565ef1e9.jpg)
![crashc04](https://cloud.githubusercontent.com/assets/22078840/23854744/22bcdb04-07c9-11e7-9e80-a383e5561ce5.jpg)
![crashc05](https://cloud.githubusercontent.com/assets/22078840/23854742/22b9bb4a-07c9-11e7-9f38-8002b0444f7a.jpg)
![crashc06](https://cloud.githubusercontent.com/assets/22078840/23854745/22bf05b4-07c9-11e7-8d0a-1a81fe718582.jpg)
![crashc07](https://cloud.githubusercontent.com/assets/22078840/23854746/22c5af36-07c9-11e7-9d47-fb2de5daca61.jpg)
![crashc08](https://cloud.githubusercontent.com/assets/22078840/23854747/22cb5026-07c9-11e7-9940-1b3f7c5a11d7.jpg)
![crashc09](https://cloud.githubusercontent.com/assets/22078840/23854748/22d15066-07c9-11e7-97d1-ee3fb68afc1e.jpg)
![crashc10](https://cloud.githubusercontent.com/assets/22078840/23854749/22d658d6-07c9-11e7-88f0-0a90b6115fd2.jpg)
![crashc11](https://cloud.githubusercontent.com/assets/22078840/23854751/22d94776-07c9-11e7-8a31-66ba5bde69c3.jpg)
![crashc12](https://cloud.githubusercontent.com/assets/22078840/23854750/22d8e998-07c9-11e7-9914-605b95ec070a.jpg)
![crashc13](https://cloud.githubusercontent.com/assets/22078840/23854753/22e7d9e4-07c9-11e7-8d1d-ac541d4a356c.jpg)
![crashc14](https://cloud.githubusercontent.com/assets/22078840/23854755/22ecdb74-07c9-11e7-840a-0b2bb41caa1d.jpg)
![crashc15](https://cloud.githubusercontent.com/assets/22078840/23854754/22ebcac2-07c9-11e7-87f0-91a74e4e3796.jpg)
![crashc16](https://cloud.githubusercontent.com/assets/22078840/23854756/22ee60e8-07c9-11e7-96ff-86e0a91f6894.jpg)
![crashc17](https://cloud.githubusercontent.com/assets/22078840/23854757/22f58eb8-07c9-11e7-87f2-a0767e3c22c3.jpg)
![crashc18](https://cloud.githubusercontent.com/assets/22078840/23854758/2301e06e-07c9-11e7-8881-537c3c641078.jpg)
![crashc19](https://cloud.githubusercontent.com/assets/22078840/23854759/231e940c-07c9-11e7-924f-0d2ebaa5e641.jpg)

**Comment by LitterBugs** [comment]
I am going to going to try exposing the FC to light and see if it can be triggered.  Also will wire up my "released" Seppuku tonight and move this camera over to it to try to duplicate it on another controller.

**Comment by tracernz** [comment]
Thanks for your effort @LitterBugs 👍 .

**Comment by mlyle** [comment]
Yes-- thank you @LitterBugs.

I think you may have hit the nail on the head here-- very very clever.  It can't really be a sync issue if the OSD is still displaying up to the moment of reset and is even able to communicate an alarm-- if sync was garbage the OSD would be tearing or missing.

cc/ @DTFUHF 

> One other thought, could it be possible that something on the FC is photo sensitive?

The baro definitely is-- the holes on the package open up to the die and it's on the same bus as the other sensors.  Every other IC would be photosensitive also if their package was damaged/cracked-- more to UV than other light, but even just to visible light.

Usually the photosensitive stuff on the baro has only been seen to mess up altitude/analog stuff (this is a primary reason for foaming the baro in builds), but if it were to get "stuck" on the SPI etc it would cause a lot of problems.

(I am also going to look over datasheets-- we're not using any CSP packages, which are known to not completely protect the chip from light-- but just to make sure)

**Comment by LitterBugs** [comment]
I will also enclose the FC and see if it can still be duplicated just with light hitting the camera....

**Comment by LitterBugs** [comment]
Both times when it happened in the air,  The quad was still completely controllable for about 4 seconds after the OSD disappeared.  That makes me think this is an OSD crash....

**Comment by LitterBugs** [comment]
Tried shining light on FC only.  Did get chanages on the Baro, but no crashses.  As soon as I started back on the camera, I was able to get it to reset several times almost on command.  Going to try grabbing the raw camera signal stream with my scope and work on wiring up my other Seppuku later tonight.  In theory, can play back the stream from my scope for testing too.  Will give that a shot too.

**Comment by pug398** [comment]
Just disable the osd module and repeat what you know will cause reset as a test. My early revision board also had sensor issues and resets under the right conditions. I just got the new seppuku soldered up and hope to test it shortly.

**Comment by LitterBugs** [comment]
I was able to duplicate this with a fresh Seppuku FC, clean install of Artifice, and the same camera.  Shining light on the FC does not trigger it.  I can make the Baro readings vary by 100+ meters, but it does not crash/reboot.  Will be much easier to get the scope on it without a frame and excess wiring in the way.   Going to throw a couple different cameras at it too.

@pug398 Disabling the OSD isn't really an option.  That's the first indicator that the problem has happened.  Still have full control 4 seconds after OSD goes away.

**Comment by pug398** [comment]
If you connect the test setup to the gcs and wave the flashlight in front of camera does the sensor warning go red? If it does then go to OSD tab and untick enable OSD. Reboot and try again and see if sensor still goes red.

**Comment by tracernz** [comment]
Good idea @pug398. If it still crashes without OSD module running...

**Comment by LitterBugs** [comment]
Not sure the sensor warning was cause or effect but really leaning twords effect based on what actually triggers the problem.   I just tried a Runcam Swift in place of the TBS ZeroZero and can not duplicate it with the settings it has.   I'll hook up the Runcam OSD cable and crank the contrast to see if it will do the same thing.  It's quite obvious the ZEROZERO contrast is too high.  It is currently something specific to the signal of the ZeroZero camera when it blooms badly.  Most of these cameras are based off the same sensor and chips but have different default settings.  So if it can happen for one, it may happen for others.

**Comment by LitterBugs** [comment]
The GCS link drops when the reboot happens.  I'll be able to test with OSD disabled as well.  Working on that now.

**Comment by mlyle** [comment]
This does look more like OSD-- I looked at the video and there are sync artifacts.

One other thing that could be related-- if the camera in question is AC coupled (has a big capacitor on its output), the relatively large capacitor we have on video input could perhaps be a problem with level drift.

We have a relatively large ceramic (2.2uF) capacitor on the input because it's good for video quality in general-- but if there's already a coupling cap on the other end of the wire the net effect can be to do odd things vs. a smaller cap (0.1uF).

[BTW, I have not looked at code but I am not sure disabling OSD actually disables the parts of the pios_video driver that would be the problem)..

**Comment by LitterBugs** [comment]
Disabled the OSD and no reboot.

Changing contrast on Runcam swift did not cause it to be problematic.

**Comment by LitterBugs** [comment]
Looking through my box o parts for other cameras to test with.

**Comment by LitterBugs** [comment]
So far none of the other cameras I've tried will result in this problem.  Going to work on capturing video with the scope to see if playing it back through my scope will duplicate the issue.  If it will, I can attach the capture file.  If not, I can at least get a sample screengrab of what the signal looks like that is triggering it.

**Comment by LitterBugs** [comment]
Would hooking up an OpenLager be of any use?

**Comment by LitterBugs** [comment]
Harder to duplicate with the scope attached, but still possible.  Is the signal level supposed to drop down to  sync level in the middle of a line?
![badvideo](https://cloud.githubusercontent.com/assets/22078840/23882863/cd11fbdc-0839-11e7-8edc-b1ba3be31297.jpg)

**Comment by mluessi** [comment]
It definitely shouldn't drop down to sync level. Maybe try scoping the HSYNC and VSYNC signals coming from the sync detector on seppuku; it may detect spurious hsyncs when the level drops low.

**Comment by LitterBugs** [comment]
This must be some of the special sauce that is baked into the ZeroZero.  It is on my $#!t list for this and lack of adjustability.

**Comment by mlyle** [comment]
@LitterBugs -- no, it definitely should not.

Where were you scoping this?  The video test point on the bottom of seppuku, or straight from the camera?

If it's straight from the camera that's definitely no good.

We do need some kind of fix for too-quick-interrupts.  

@mluessi -- does RE1 do anything other than thresholding?  It looks like to me this has to be vsync (since hsync doesn't fire an interrupt except on overflow/update)

**Comment by LitterBugs** [comment]
This was scoped directly from the camera at the input to the Seppuku.    Anything else you want me to check?

**Comment by mluessi** [comment]
@mlyle yeah, the sync detector in RE1 needs the signal to be low for at least 1us for hysnc to be detected, so it may get rid of some spurious detections.

One way to fix this could be to disable the hsync interrupt until the DMA SPI transfer is complete, but it would need a 2nd interrupt for line to re-enable it, which is not ideal.

**Comment by LitterBugs** [comment]
I guess the good news in all of this is it takes some really bad non-spec video to trip it up.  I'll throw it on a RE1 tonight and see how it handles it.

**Comment by mlyle** [comment]
@litterbugs -- yes, I think that about says it.  I do think we need protection against lines toggling too quickly.  People have crashed FCs before by hooking up frsky high frequency pwm (90KHz) to serial or pwm decode lines, or there's this kind of issue.  It's just tricky to do in a general way.

**Comment by LitterBugs** [comment]
Tested RE1 with same camera for over 5 minutes and could not get it to trip up. On a side note, Trappy put out a hack for the ZeroZero to enable the settings menu, so I may be able to adjust the bloom out of it and use it on the build this RE1 is going in.   I'll keep it on hand for future testing.   Just received a couple runcam Minis that can go into my beater Seppuku Test mule and my Seppuku clean build.

**Comment by LitterBugs** [comment]
I've tested a handful of other cameras on the Seppuku other than my ZeroZero and have not been able to duplicate the problem.  I put a support ticket in with TBS.  Will be getting a V2 version of the camera which I will test when it arrives.  Will also try enabling the config of the V1 camera to see if changing the settings can "fix" the camera output.  This camera has some really good low light properties, but obviously the bright properties have issues with it's current configuration.  

Testing results:
TBS ZeroZero V1 - Fail
STRIX Ochi 650 - Pass
Runcam Swift  - Pass
Runcam Swift Mini - Pass
HS1170  - Pass

I have a handful of other cheap non-adjustable CMOS cameras which I will test as well.

**Comment by pug398** [comment]
The only thing I can add to this is the composite sync pulse can be scoped coming off the sync detector (pin1) and when there is a sharp contrast change you can see the horizontal pulse distorting coming up off of low level maybe a 100-150mv and then going back to low again. Without any hysteresis I could easily see this detected as 2 horizontal pulses instead of 1.

**Comment by mlyle** [comment]
@pug398 I don't think extra hsync should be a problem, because all it does is starts a counter for when clocking out the line should actually begin (and this is hardware, no interrupt, etc).

Extra, frequent vsyncs could be very, very bad though-- which the timing of this at the end of the line as happens to @LitterBugs is about worst case.

The scoped artifact seems to be "very colorful black"-- e.g. colorburst frequency on a black signal causing it to poke down.  I actually have pads down for a lowpass filter because I thought it might be required in some cases.  @dtfuhf may decide based on this to populate the extra passive for that filter to make us more robust to this kind of thing.

I am going to mark this as duplicate of #1340, as it's the same core issue and should-- ideally-- be solved together.

**Comment by LitterBugs** [comment]
I'll scope the H&V sync at the LM1881.  Should be able to get both at same time since this is a dual channel scope.  Would you like it added to this thread, or #1340 ?

**Comment by mlyle** [comment]
Here is fine, #1340 will refer to it.  (And this can be a useful place to note for hardware revisions, though this bug tracker isn't relaly hardware focused).

(You might want to compare video & csync, to see if it's easier to catch the anomaly.. and then if so video & vsync).

@LitterBugs I really appreciate all your help and patience with this.  I know it's been a pain.  All in all, a very strange problem.

**Comment by pug398** [comment]
A few vertical sync pulses are dropped but don't really see any added ones.

**Comment by mlyle** [comment]
@pug398 -- do you have a repro of the crash from overpeaked video?

**Comment by LitterBugs** [comment]
@mlyle Really not a pain and very glad to help.  I'm getting a better understanding on how it all works and eventually I'd like to get into some light coding.  Helping find problems and diagnose them has been a big part of my life.

**Comment by mlyle** [comment]
@litterbugs We'd love the help :D

**Comment by LitterBugs** [comment]
My coding skills are very outdated....  Better at reading, tracing, and debugging than developing.  Still trying to get a good mental map of how it is all layed out and linked together.  Started putting together a dev environment once.   Need to get back to that after I get all my builds done.

Yeah, I should have said C/V sync.  If those are logic rather than analog, I can actually capture them all.  I can do a total of 8 channels, but only two can do analog.

**Comment by mlyle** [comment]
@LitterBugs they're "logic"-- though @pug398 sees a slight movement on one of the signals with no pulse.

re: dev-- It's a big codebase and it's a bit arcane.  We're steadily removing code that does nothing and reorganizing ;).  When you get around it, if you have any particular area of interest I'd be glad to show you around that part of the code.

**Comment by LitterBugs** [comment]
So here's a quick sample of good video with the lens cap on.   Video on input A (top),  Csync on input 0, and Vsync on input 1.  Set trigger on Vsync and it works like a charm.
![mixedscope](https://cloud.githubusercontent.com/assets/22078840/24024186/bb57c368-0a87-11e7-90ab-e95726df58ca.jpg)

**Comment by LitterBugs** [comment]
VSync seems to be normal even during an incident.  Going to zoom in on Csync to see if anything shows there.
![bigsampleglitched](https://cloud.githubusercontent.com/assets/22078840/24024510/60d7c07a-0a8a-11e7-906b-1aa3fb815a56.jpg)

**Comment by mlyle** [comment]
I've never used bitscope, but is the sampling rate high enough to capture csync correctly?  It looks like lots of csync edges are missing / jittered out.

(I also wonder if we could be missing similar, short edges on vsync)

**Comment by LitterBugs** [comment]
Yes, but my display isn't big enough so the screen shows aliasing.  Need to get my bigger monitor hooked up to my laptop.

**Comment by LitterBugs** [comment]
I'm also trying a couple other tools to see if I can get a better sample.

**Comment by LitterBugs** [comment]
It's a balancing act trying to get the most on the screen and being able to look at what is going on.  Not the best software but the hardware is plenty capable.
![zoomedin](https://cloud.githubusercontent.com/assets/22078840/24025504/2f640cc2-0a91-11e7-9961-f9bdefdb5d5e.jpg)

**Comment by mlyle** [comment]
Is purple csync?  That indeed looks bad.  -mpl

**Comment by mlyle** [comment]
I am away from my test environment right now-- but I committed some things in #1640 that may be helpful.  If all goes well, artifacts may spit out there in an hour or so.

**Comment by LitterBugs** [comment]
I'm not really finding anything odd on Csync either.  Are there any other points to check?   I'm open to shipping this camera to you @mlyle if you want to give it a look.

**Comment by mlyle** [comment]
@litterbugs --- Is purple Csync-- because it looks to be toggling a lot in that screenshot you sent earlier...

Or is white/grey.  They both look like csync signals, but the purple one looks bad :P  

In auditing the old brain OSD code that we're using, I definitely see deficiencies in hsync (csync) handling.  I tried to fix that in #1640 but just realized I got it subtly wrong.  I might have a build to look at tomorrow to see if it makes a difference.

**Comment by LitterBugs** [comment]
I tried turning off all fields but leaving the OSD enabled.   Still resets.

**Comment by LitterBugs** [comment]
Odd/even and backdoor look good as well....

**Comment by LitterBugs** [comment]
Purple above was the digital equivalent to the Video signal.  Csync is bottom.  Logic 0

**Comment by LitterBugs** [comment]
How and when is NTSC/PAL being determined?  What would happen if the signal changed from one to the other or if the detection algorithm thought it changed?

**Comment by LitterBugs** [comment]
One thing I notice in _all three_ examples above, is the frame just before the OSD drops out, the size of the OSD screen shrinks inwards from both sides....  It's almost like the OSD is expecting more pixels and/or rows and gets stuck when the Vsync comes too early....

**Comment by mlyle** [comment]
@litterbugs re: NTSC/PAL-- on RE1 it talks to an FPGA and reprograms some registers to make it do different things.  On original Brain and Seppuku, we just load the registers for the current mode at the start of each frame.  Current mode is chosen by seeing how many lines were counted in the previous frame.

Found a deficiency in the old Brain code that Seppuku also runs, though-- if that line counter were to overflow 65535 very bad things would happen.  That would require a very rapidly toggling csync, but it's possible.  Once overflow was reached, an interrupt would fire continuously (it would not clear the interrupt flag) and an infinite loop would result.

I've changed the code to clear the interrupt flag in all cases (we'll detect PAL, though, for the next frame if this happens, and then change back, but this is no big deal  ;).  I've also enabled a hardware glitch filter on the hsync line on Seppuku.  I'm curious if this fixes the problem.  Can you please try with the evil camera?  Artifacts are here: https://github.com/d-ronin/dRonin/pull/1640#issuecomment-287274367

**Comment by LitterBugs** [comment]
Evil camera?   It is the "Black Sheep" after all.   Will test tonight.

**Comment by LitterBugs** [comment]
Just tested the artifacts.  The screen jumps around a bunch more than it did previously and when the glitch gets triggered, it locks up and never comes back.  LED quits flashing on the FC too.

**Comment by LitterBugs** [comment]
Curious what you would use to capture and play back raw video.  I may have some other gear laying around to provide test files.  Pretty sure I have an old tuner dongle that I could use to record with, but can't remember if it did composite or component input.  (maybe both)

Also, would it be of any value to attach an OpenLager?

**Comment by pug398** [comment]
@LitterBugs with my "bad" 12v camera I get vertical sync loss with repeated high contrast change but have yet to get sensor warning or crash since loading new artifacts. My test setup is a little different now but I felt things were better. Still have more testing to do.

**Comment by pug398** [comment]
@LitterBugs ok I take that back. A few flicks of the light in front of the camera just now caused severe vertical sync loss and osd crashed with status led freezing on. Came back on after a long delay. Still no sensor warning or gcs disconnection which I had on previous releases.

**Comment by LitterBugs** [comment]
It appears the the LED stays in the state it was in when the OSD crashes.  It does not disconnect from GCS on my setup either.  It takes roughly 40 seconds for the OSD to come back.  Barometer is still light sensitive and reactive on GCS.  Wonder if adding a LED strip if the LED strip would hang at the same time.   Looks like the status LED output feeds the LED out from the board.
  
Going to add LED strip and RX to my test rig.

Screen s rock solid with my other CCD cameras under similar circumstances.

**Comment by pug398** [comment]
![newfile1](https://cloud.githubusercontent.com/assets/3682100/24068006/a6a2eb9a-0b5a-11e7-884b-2fecb036493c.png)

Shows video and vertical sync as contrast changes sharply.

**Comment by LitterBugs** [comment]
@pug398 I think your setup may be behaving different than mine.  I never loose Vsync.

**Comment by pug398** [comment]
when you said your picture was more "jumpy" it wasn't jumping up and down?

**Comment by LitterBugs** [comment]
It is more of a format change.  Up/down yest, but the OSD is squeeded too.  Always shifts up when the sides squeeze in.

**Comment by LitterBugs** [comment]
![crashc17](https://cloud.githubusercontent.com/assets/22078840/24068070/5143ae76-0b5c-11e7-9dfd-92f280958f2c.jpg)
![crashc18](https://cloud.githubusercontent.com/assets/22078840/24068069/514201a2-0b5c-11e7-8541-6e6d80bd1ff6.jpg)

**Comment by LitterBugs** [comment]
Nuts.... just triggered a migraine.....  Going to have to stop for the night.

**Comment by pug398** [comment]
A good friend of mine has those...I feel for you. Rest up.

In the pic above each of the 3 bias changes is when the light is waved in front of the camera and results in a missing sync pulse. Still trying to determine whether the sync pulses are truly doubled up like some of them appear to be or whether that is something caused by the software of the DSO.

**Comment by LitterBugs** [comment]
It takes quite a bright light (700 lumens) to get my camera to easily trigger the OSD issue.  Unfortunately, bright enough that it can also trigger an Ocular Aura which is a precursor to a migraine.  Between the Status LED which is very bright, and my bike headlight, It set it off.  Think I stopped just in time.  Vision is coming back and no headache.  Should be able to sleep it off.

**Comment by mlyle** [comment]
:( @LitterBugs 

So, interesting all in all.  Will give it some thought.  

@pug398 -- where was that video scoped?  Test point or before entry to board?

**Comment by LitterBugs** [comment]
@mlyle Where are these test points that you mention?  I've been clipping on to the LM1881 for the sync signals and the video signal wire where it is connected to the FC.  Are there any other points we should try scoping?

Also, I've noticed that the default config for seppuku analog inputs is reversed for V and I.  V defaults to ADC1 and I to ADC0.  I'm always having to flip those after clearing all settings......  I can create tickets for little things like this if you want, or would you rather just have a quick heads up?

**Comment by mlyle** [comment]
@litterbugs Unfortunately the default-analog-ticket thing I can't really fix for historical reasons.  Heads up is better.

There is one test point of the buffered, clamped video on the bottom of the board.

**Comment by pug398** [comment]
@mlyle where video enters the board. I will take the fc off the carrier plate and try to get to the test point. 
vsync compared to video at test point when light passes in front of camera.
![newfile3](https://cloud.githubusercontent.com/assets/3682100/24075390/d38158b8-0bf0-11e7-85cf-6cf6e4fe94a0.png)

![newfile4](https://cloud.githubusercontent.com/assets/3682100/24076601/3e245e1c-0c0b-11e7-83d5-9af67c027525.png)

**Comment by LitterBugs** [comment]
Got an LED strip and an RX hooked up because I wanted to make sure nothing else was going bad even though the GCS was not disconnecting.   The LED strip does hang during the time the OSD is gone just as I expected.  The RX appears to be working correctly along with the gyro, baro and acc.  I was able to arm, disarm, and verify the RX inputs were responsive on the inputs tab.  I have not wired up any ESCs or motors yet.  Guess I could use my beater alpha hellbender with props off to make sure the motors are still responding correctly when the OSD is gone.

**Comment by mlyle** [comment]
Oh, how long of a delay without LEDs?  We usually update the LEDs during vsync, but if vsync is missing, after 400ms will resume doing it in the system task.

**Comment by LitterBugs** [comment]
40 seconds, just like the OSD.  They stay at the same color/brightness they were when the OSD disappears until the OSD comes back.

**Comment by mlyle** [comment]
OK, I found two more issues--

first, that if we're in PAL mode (which-- assuming the issue is many extra csync pulses, seems likely-- though missing vsync could also do it) and out of video sync, while receiving NTSC video it could take a long time to go back to NTSC.  I can't really explain 40s-- 10s seems possible.

second, if we're in PAL mode receiving NTSC video we wouldn't update the LEDs since we would never get "far enough down" in the frame.

Both **hopefuly** fixed.  All these bugs apply to original Brain, Seppuku, and PlayUAVOSD.

Confirmed basic function on PAL/Seppuku.  Artifacts will show up at https://github.com/d-ronin/dRonin/pull/1640 in about an hour.

**Comment by LitterBugs** [comment]
With the "evil camera":
The LEDs are working now even when the OSD is hung.   The OSD does not always start, and when it does, It will still hang under the right lighting.  When the OSD hangs, it never comes back.  Rebooting controller from GCS will make the OSD come back.  When changing settings in the GCS OSD screen, clicking apply, and clicking save can hang the OSD.  The OSD will sometimes hang on it's own when Y offset is set to 8 or 10 but not when set to 9.  (even/odd issue?)

**Comment by mlyle** [comment]
Urgh.  I should just rewrite all of this stuff.

**Comment by LitterBugs** [comment]
With a formerly "good camera",  Unplugging evil cam and plugging in good cam will hang OSD.  Making changes in GCS to OSD screen can hang OSD.  Still looks like even/odd issue with Y offset.

**Comment by LitterBugs** [comment]
LEDs are fixed!  You got that right!  :+1:

**Comment by LitterBugs** [comment]
Unplugging and replugging good cam will hang OSD...

**Comment by mlyle** [comment]
I'm just going to pull out the code that's been sitting for 3 months waiting to get merged..  as it's pretty much a rewrite and of much higher quality than what's been in the OSD before.

**Comment by LitterBugs** [comment]
Initial testing with the artifacts posted on #1640 at 10:37 look very good.  Continuing to test......

**Comment by LitterBugs** [comment]
8 minutes of intense trying and unbale to get the problem to occur.  I've seen some very light artifacting but it is localized and there is no format shift or OSD hangs happening any more.   Unplugging and replugging camera causes no issues.  Changing cameras while FC is up causes no issues.   

MOST EXCELLENT JOB @mlyle !!! :+1:

**Comment by pug398** [comment]
Yeah I don't care what others say @mlyle is the man! :)
Looks good here also.

**Comment by mlyle** [comment]
Heh, thank you both for your patience and test time..

and sorry for my frustration/being a bit short above.  Will work to get the fix landed.

**Comment by LitterBugs** [comment]
No worries!  Glad we are making solid progress!

**Comment by LitterBugs** [comment]
Interesting problem today out at the field.  Went to fly my pre-release FC based quad with the "evil NTSC camera" and the OSD hung up on boot.  OSD detected it as PAL and just sat there with the initial logo screen.  Quad flew fine LOS other than that.
![hungosdboot](https://cloud.githubusercontent.com/assets/22078840/24592604/641f5a08-17e7-11e7-8bc6-f156b2757cf9.jpg)
Will try a different camera....

**Comment by mlyle** [comment]
@LitterBugs -- with what build?  Did this just happen once or was reproducible?

**Comment by LitterBugs** [comment]
This was the build that was working on the bench previously.  I tried another camera and it is doing the same thing. 
20170319 01:46
GIT Hash 35bec65e
I'm going to go back to stock artifice and see if it still does it.  Maybe something else is going on with this board.

**Comment by LitterBugs** [comment]
I re flashed the test image and cleared all settings and it is working OK at the moment.   I backed up the settings before re-flashing.  Will try restoring settings to see if it comes back and do some other testing tomorrow.

**Comment by LitterBugs** [comment]
I was able to reproduce this pretty easy by restoring the pre-flash settings.  Narrowed it down to the "Y Offset" of the initial OSD settings page.  Can easily duplicate it even with complete default settings by changing the Y offset to a value > 4 and power cycling the board.

**Comment by LitterBugs** [comment]
FWIW,  changing the Y offset from GCS > 4 will not hang the OSD until the next cold boot of the board.  OSD hangs at the PAL/NTSC detection shown in the picture above.

**Comment by LitterBugs** [comment]
Could it be because the text at the bottom of the boot screen gets pushed off the bottom for an NTSC signal with the Y offset > 4 causing a line count overflow

**Comment by mlyle** [comment]
@litterbugs-- good find.  will not be able to look at the code just now but that shouldn't be too hard to fix.
