### ISSUE TITLE
Package: Windows Installer Missing Serial Driver (#1581)

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1604]
NSIS scripting didn't work for some reason and it doesn't show up on Windows 7 (haven't tried 8/.1).

**Comment by mlyle** [comment]
Win10 is 44% and still climbing by more than a percent per month.  Do we just say this is WONTFIX rather than deferring

**Comment by tracernz** [comment]
I'll take another quick look and if that fails let's WONTFIX it.

**Comment by mlyle** [comment]
parfait, thx

**Comment by mlyle** [comment]
Too hard, diminishing returns (w10 is big now)

**Comment by tracernz** [comment]
Windows 8.1 is now out of mainstream support so Windows 10 is the only real option.
