### ISSUE TITLE
Dynamically generating udev rules breaks people who download it from repo

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1606]
As our relnotes currently suggest.

**Comment by tracernz** [comment]
It's included in packages, so no need.

**Comment by mlyle** [comment]
Is it in the zip?   If nothing else the link in the relnotes for the past
release needs to change.

**Comment by tracernz** [comment]
Yep, should be at `$(PACKAGE_DIR)/rules.udev`, wouldn't hurt to check though. Should update past rel-notes to link to the file at the correct tag (we probably should have done this anyway).

**Comment by tracernz** [comment]
Fixed Artifice.

**Comment by tracernz** [comment]
All fixed and added a TODO to https://github.com/d-ronin/dRonin/wiki/Release-process to remind us for Neat. That should be enough to close this?

**Comment by mlyle** [comment]
Sounds good :)
