### ISSUE TITLE
Moving Horizontal Stripes on OSD layout RE1

### ISSUE THREAD

**Issue by RoadyFPV** [d-ronin/dRonin#1623]
Issue details:
Hi i have flashd latest dronin on my BreinFPV re1. Here i have n OSD issue, moving Horizontal Stripes from up to down on OSD layout. With the vido sync detector i cant fix it. 
when i flash the older firmware dRonin 2016-10-04.1 Release ("Quixote"). The OSD is fine.

**Comment by mlyle** [comment]
Do you have any screenshots so we can better understand?

Are you running dshot?

**Comment by mlyle** [comment]
(Have many users on RE1 on Artifice with no reports of this issue, so I suspect it's something unique to your configuration...)

**Comment by RoadyFPV** [comment]
I running D-Shot600.
screenshot coming tomorrow.
Thx for fast help

**Comment by mlyle** [comment]
dshot support is preliminary and I wouldn't really recommend it for OSD targets.  It's almost certainly your problem.
