### ISSUE TITLE
Fix QT version stuff over at readme.io

### ISSUE THREAD

**Issue by glowtape** [d-ronin/dRonin#1629]
Both v20170213 and v999-dev still refer to QT 5.6.1 and MinGW 4.9.2. Not that there's people running down our door, writing code, but @yamahabest is currently having a ball with that one.

**Comment by yamahabest** [comment]
Yeah, thanks.
And while we're at it, I can't seem to solve the following compile error:

dRonin\ground\gcs\src\libs\libcrashreporter-qt\libcrashreporter-handler\Handler.cpp(33): fatal error C1083: Cannot open include file: 'client/windows/handler/exception_handler.h': No such file or directory.

The file seems to be there on that path, but the compiler can't find it, it seems.

**Comment by tracernz** [comment]
I've been working on making Windows environment setup easy (Qt SDK download and install is taken care of like on Linux and Mac) and not breaking old branches every time we upgrade a tool. Current progress is at https://github.com/tracernz/dronin/tree/mrc-win-ng (CAUTION: don't clone this, I'll be force-pushing to the branch). I think it's pretty close.

**Comment by tracernz** [comment]
Remaining work is to check for a valid MSVS installation before installing Qt etc. (if setting up an MSVC environment), and maybe look into MS Build Tools as an alternative to installing MSVS.

**Comment by mlyle** [comment]
superseded d-ronin/d-ronin.github.io#47
