### ISSUE TITLE
Add Team Black Sheep BST telemetry support

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#164]
The [TBS Crossfire LRS](http://team-blacksheep.com/products/prod:crossfire_tx) uses a new telemtery protocol based on I2C. It would be nice to add support for this protocol.

Reference: https://github.com/PX4/Firmware/pull/2939

**Comment by tgreer** [comment]
I can test this if someone can code it.

**Comment by tracernz** [comment]
It's a bastardised version of MSP IIRC? If so could probably create a PIOS_COM interface to the I2C device and use the existing MSP library and maybe even the existing UAVOMSPBridge.

**Comment by jhitesma** [comment]
I seem to remember something about it not quite being I2C just based on I2C with some extra goofiness added in.

**Comment by Siytek** [comment]
Did the BST implementation every get completed? Last time I checked perhaps 9 months ago and it was still only sending the minimal messages. Glancing over bst.cpp it looks to be the same.

Would be good to have this support to free up the USART on the xFire receiver for SBUS.

**Comment by mlyle** [comment]
Is there any strong reason to do this now that we support Crossfire Telem?

**Comment by glowtape** [comment]
Sends exactly the same things over BST, AFAIK. If the use case is solely Crossfire, instead of other stuff using BST (what is there, anyway? just their GPS?), it seems pointless to implement it.

**Comment by mlyle** [comment]
I think you can change VTX channels over BST, but we prefer smartaudio to that.

Closin'.

**Comment by tracernz** [comment]
BST was never a good protocol to begin with. We already have better alternatives. :+1:
