### ISSUE TITLE
PikoBLX: Missed cleanups in #1656

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1664]
First doc build since #1656 and it's already regressed. :cry: 

Fixing would clash with #1660.

**Comment by mlyle** [comment]
Is this fixed now, did #1660 take care of it?  lux doesn't seem particularly worse than other targets looking at the doxygen stderr  (from here https://travis-ci.org/d-ronin/doxygen )

**Comment by tracernz** [comment]
Yeah I think so.
