### ISSUE TITLE
VCP Oddities

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1679]
* [ ] If you read with a long timeout (e.g. PIOS_QUEUE_TIMEOUT_MAX), the port locks up for at least Linux users.
* [ ] The port is unusable for several seconds after connection when using Liunx
* [ ] VCP to BLHeliSuite doesn't seem to work (cabled serial does).

All experienced on F4 on Seppuku

**Comment by tracernz** [comment]
Hmmm, I think I was doing the 4w-if stuff over VCP with BLHelisuite. Although I do tend to use a hardware serial for Dev work because USB ports dissappear when the firmware stops so can't be sure.

**Comment by mlyle** [comment]
I get "SetCommState function failed"   With Windows Message : "System Error.  Code: 31.A device attached to the system is not functioning" 

Probably some nuances of VCP implementation that need work..

**Comment by tracernz** [comment]
I ran under WINE which probably explains why it would work for me. :wink:

**Comment by mlyle** [comment]
Looks like when opening with blhelisuite, URB requests 33 (GET_LINE_CODING) is sent twice unanswered pertaining to the IN endpoint, and 32 (SET_LINE_CODING) is sent once, and SET_CONTROL_LINE_STATE is sent once.

**Comment by mlyle** [comment]
![image](https://cloud.githubusercontent.com/assets/90903/24481940/c02ed0be-14a2-11e7-8410-28132cd5613e.png)
