### ISSUE TITLE
Pathway for ChibiOS Adoption

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#169]
Several targets are still using FreeRTOS. We should come up with a plan to move these onto ChibiOS. Additionally we need to decide if F1 will move to Chibi. We have noted increased RAM usage in some tasks with Chibi (although overall RAM usage seems to be low at least on F4 targets). I think a good approach here would be to convert either Naze32 or CC3D and compare real changes in resource usage and then make a decision. If we do convert everything to Chibi we could then begin replacing quite a few of the ST peripheral library drivers with ChibiOS HAL drivers. I am happy to do the DiscoveryF4 conversion ASAP leaving just F1 targets.

Targets awaiting transition to ChibiOS:
- [x] ~~coptercontrol~~
- [ ] pipxtreme
- [x] ~~naze32~~
- [x] revomini (pending #166)

**Comment by mlyle** [comment]
Not simulation, right?

**Comment by tracernz** [comment]
I just did grep -r PIOS_INCLUDE_FREERTOS and those were the targets that showed up, didn't look further. ;-)

**Comment by mlyle** [comment]
With discussion of fundamental changes to F1 support, it would be just pip that needs particular attention-- post-artifice.
