### ISSUE TITLE
Handling of upgrade of unitialized FC could be improved

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1697]
Issue details:
When saving the "upgraded" settings, the GCS complains that it has no settings.
Only way to get out of the wizard is to abort.

If there are no settings, the last step of saving the "upgraded" settings can be omitted probably.

**Comment by tracernz** [comment]
I thought there was already a bug for this but I can't find one. Have encountered it many times but it's a little messy to fix.
