### ISSUE TITLE
Strange size of textbox on System tab

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1698]
* Seen in version (release version or githash): a08a62cd

Issue details:
It seems to be overlapping some text?

![image](https://cloud.githubusercontent.com/assets/17543838/24742409/667a51b6-1aaa-11e7-8672-7de9d5fd5aad.png)

**Comment by mlyle** [comment]
This is fixed in #1686.

**Comment by yamahabest** [comment]
Ok, great!

**Comment by mlyle** [comment]
When #1686 is closed this will auto-close. ;)

**Comment by yamahabest** [comment]
Whoops :-)
