### ISSUE TITLE
Couple of small UAVO-related niggles

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1711]
1. RGBLEDSettings isn't marked optional in modules so you get a warning on saving modules on non-LED targets.
1. I've seen this, but have no repro at this second (perhaps fixed, perhaps my sim case doesn't work)-- attempting to save one of input settings or output settings fails because it can't persist the data object providing the values/positions.

**Comment by tracernz** [comment]
1. Ah, should do that.
2. Yah, UAVO relations in ConfigTaskWidget are two-way binding, no way to make them one-way currently.
