### ISSUE TITLE
vtolpathfollower: navigation should use altitude settings for maxclimb/maxdescent rate

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#174]
1. Gets the benefit of differing climb and descent rates for navigation as was added to altitude hold settings.
2.  more importantly, get the additional resolution on rates, which right now are limited to m/s resolution.

**Comment by mlyle** [comment]
Need to ensure loiter does the right thing with the new rates.

**Comment by pug398** [comment]
That should work well with the cm resolution and autonomous climb/descent rates in one place.
