### ISSUE TITLE
Mention of Tau Labs in the Options dialog

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#1751]
Issue details:

Shouldn't this be dRonin by now? Or Tau Labs/dRonin?

![image](https://cloud.githubusercontent.com/assets/17543838/25542632/a7b037ee-2c53-11e7-9f96-97ab8bf8cbfb.png)

**Comment by tracernz** [comment]
Or just "Automatically connect recognised USB devices".
