### ISSUE TITLE
Highlights in UAV browser broken

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1775]
My fix in the static analysis PR, and subsequently sucked.  Need to look at, but can't now.

**Comment by tracernz** [comment]
Added a comment on the PR (#1774).

**Comment by jihlein** [comment]
I don't know if it's the proper fix but in treeitem.cpp changing:

*m_currentTime = *currentTime;

back to:

m_currentTime = currentTime;

restores correct operation.   Can put together PR if it helps.

**Comment by mlyle** [comment]
No.. will get something together in the next couple of days.. this code is not good and will require something systemic to fix.
