### ISSUE TITLE
Radio Configuration Wizard Accessory2 taking input from Accessory1

### ISSUE THREAD

**Issue by yds** [d-ronin/dRonin#1812]
* Seen in version (release version or githash):  908e5eed
* On flight controller (if applicable):

Issue details:  When going through the Radio Configuration Wizard I get the following correct mapping:

Accessory0: Chan 7
Accessory1: Chan 9
Accessory2: Chan 10

However the on-screen representation toggles **both** _Accessory1_ and _Accessory2_ when the _Chan 9_ switch is toggled and does not toggle anything when _Chan 10_ gets toggled.

To be clear: this is only an issue with how the toggle verification is represented on screen.  The actual mapping after the wizard completes is correct.

**Comment by yamahabest** [comment]
Sounds similar to this: https://github.com/d-ronin/dRonin/issues/1272

**Comment by mlyle** [comment]
Dup #1272, thx
