### ISSUE TITLE
Make sure DC gain of lowpass filter is unity

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1838]
cc @glowtape 

Since there's a copy of the same code in GCS used for autotune, it could perhaps explain gains being too high with the 1.3 noise-sens that was validated before.

**Comment by glowtape** [comment]
As per IRC, I've done that feeding million of 10s resulting in 10 thing, does it just fine. As per various documentation on the web, the DC gain of a BW filter is supposedly always 1.

What lowpass filter was used in an earlier neotune prototype, before the new lowpass filter stuff went in, that resulted in an 1.3 noise sensitivity?

**Comment by mlyle** [comment]
Was a false alarm, it seems.  In the future we should have unit test for similar changes.
