### ISSUE TITLE
revolution: SPIPeripheral to MAX7456 bootloops

### ISSUE THREAD

**Issue by glowtape** [d-ronin/dRonin#1848]
Per this thread on the forums:

https://forum.dronin.org/forum/d/56-led-strip/8

Trying to track down an issue that suddenly stopped being reproducible, it appears that my Revo clone doesn't like SPIPeripheral set to MAX7456 at all. Configuration erased on bootloader, boot, set that option, reboot, and voila, it's stuck in a bootloop. Even with a dummy quad configuration, it goes haywire, once set.

**Comment by mlyle** [comment]
Per forum thread, it was actually WS2811?  And we fixed it, maybe?

**Comment by glowtape** [comment]
Wow that's an old thread. Yeah, it's fixed.
