### ISSUE TITLE
Neat test issue

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1872]
Rolling up results from light test.

**Comment by mlyle** [comment]
* Lux / 180 lasered frame: lost mixer during upgrade(but was on weird intermediate build).  Default PIDs wobbled; autotune worked despite constant wobble
* original brain on blade 150: worked great
* TBS Vendetta (Lux/Colibri Race): flight was great. '2811 LEDs worked-- but blinked 'I' or similar during flight for undetermined reasons.  Could not repro on bench.
* Seppuku small quad: all great.  Tested stacked tune, and that was pretty good too.
* Seppuku HUGE quad: all great.  Sounds terrifying :P 
* RE1 Owl-style: Required change to sensorsettings-- cutoff=48, filterorder=3 to tune-- had TONS of vibration before that / bumpy autotune part.  Flies great after tunem but the actual aircraft is falling apart.
* Navigation plus quad: all good.

**Comment by mlyle** [comment]
It's been a long time coming--- but we're pleased to announce the new "Neat" release of the dRonin flight controller firmware and ground control station.<br/>

A lot has changed, so please read the release notes carefully. <br/>

Please see the documentation at: [http://dronin.readme.io](https://dronin.readme.io/v20170213)<br/>

@jhitesma has produced an excellent [upgrading video](https://www.youtube.com/watch?v=TZR0TCC8NOw) that you may want to watch if this is your first time upgrading dRonin!.<br/>

Jump ahead to: [Changes](#changes) /  [Errata & troubleshooting](#errata)<br/><br/>  

<a name="changes"></a>**Major changes since last release:**
* Core flight firmware improvements
  * "NeoTune" next generation cross-correlation based tune algorithm yields better results-- even in the presence of vibration and other anomalies.
  * Improved sensor filtering implemented in the Sensor module.
  * Improvements to attitude estimation performance in the presence of vibration.
  * Support 4WIF passthrough for ESC programming across 'MSP' protocol interface.
  * Improvements to realtime behavior and removal of jitter.
  * Mixer architecture changes improve performance and allow custom mixers that use "accessory" data across outputs (and lays the groundwork for future control improvements).
  * Several fixes made to telemetry/configuration protocol performance across flight and GCS.
* Changes in supported targets
  * Support added for PikoBLX micro flight controller
  * Support added for Seriously Pro F3 EVO ("SPRF3E") and various clones (e.g. FrSky XSRF3E).  Note that only the "EVO" SPRF3 variants are supported.
  * REMOVED SUPPORT FOR F1 FLIGHT CONTROLLERS (CC3D, NAZE).  Use "Artifice" for these controllers. 
* Target improvements
  * Support for WS2811/2812 LEDs added to select F3 targets (Lux, SPRF3E)
  * DShot using DMA implemented for OSD targets (original Brain, Seppuku, and BrainRE1)
  * Improvements to on screen display reliability on original Brain and Seppuku flight controllers.
  * Various improvements to the AQ32 target: flash erase, DAC annunciation, and WS2811 features.  However, PWM RX support was removed.
  * Moved all Invensense targets to a common, improved sensor driver.
  * Simulation/flyingpi: move to OS-native threading model instead of embedding ChibiOS; put the simulator binaries for ARM and x86 in the Linux packages.
* External hardware support
  * Support for TBS Crossfire receiver protocol
  * Preliminary support for OmniPreSense millimeter-wave radars.
  * Improvements to IBus protocol reliability.
* Miscellaneous
  * Simple UI added for annunciator (LED, buzzer) settings.
  * Various bugfixes and performance improvements.
  * Improvements to UI styling.

<a name="errata"></a>**Errata & Troubleshooting**
*  THIS RELEASE REMOVES SUPPORT FOR F1 FLIGHT CONTROLLERS (CC3D, NAZE).  Use "Artifice" for these controllers.
* USB/F4: A long-standing bug prevents reconnecting the flight controller by USB without a FC reset (e.g. when powered by external power).  This can worsen communications when using a flaky USB cable.  We intend to devote significant effort to fixing this soon.
* Windows: Windows XP is no longer supported; Windows Vista or later is required for operation.
* Windows: If you are on Windows Vista, 7, or 8 and receive a message "api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer," please see https://support.microsoft.com/en-us/kb/2999226
* Windows: If you are unable to communicate with the flight controller after plugging it in, please see [this procedure](https://github.com/d-ronin/dRonin/wiki/Windows-driver-troubleshooting) for a possible solution.
* OS X: OS X Version 10.9 ("Mavericks") or later is required to run GCS.
* OS X: the application is unsigned; it is necessary to open `Applications`, right-click on `dRonin GCS` and select `Open` on the first launch. 
* Linux: **NOTE THE UDEV RULES HAVE CHANGED ONCE AGAIN** you will have to install .udev rules for the device. The .deb package attempts to do this automatically.  To do this manually (e.g. from the tarfile), from the package `sudo cp rules.udev /etc/udev/rules.d/45-dronin-permissions.rules && sudo udevadm control --reload-rules` .  Also please ensure your user is in both the `plugdev` and `dialout` groups as is appropriate for your distribution.

**Comment by tracernz** [comment]
Preview build runs okay on macOS 10.13 beta 3. Restoring my laptop to 10.12 because beta 2 and 3 were too unstable for normal use so can't test anymore.
