### ISSUE TITLE
GCS/Autotown: Record tune sample data in Autotown

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1876]
Would be nice to grab at very least the raw tune data (a few kb binary blob) and stick it in autotown as a blob (cloud storage, linked to the datastore entries we already do?). @dustin

**Comment by tracernz** [comment]
@dustin I wonder if `handleStoredTune` could return some kind of key in body and GCS could then send a PUT request with the big blob to /storeTuneBlob/<secretkey>. storeTuneBlob would store the blob in cloud storage, then decode the key and attach the blob to the tune record already in datastore?

**Comment by mlyle** [comment]
Is it unacceptable to just put the tune data base64 encoded in a json field?  would be about 44kbyte

**Comment by tracernz** [comment]
It seems undesirable to mix binary and JSON data, and especially to make it bigger by base64 encoding. Whatever is easiest for @dustin works for me though.

**Comment by mlyle** [comment]
Yah, it's yucky.. but it involves no new work and no new indirection, and the total size isn't something completely ridiculous-- datastore is 18 cents per gigabyte * month, so about 100 user tunes for a penny per year.  (Blob storage is 1/10th the price, but our time is worth something).
