### ISSUE TITLE
Tooltip for attitude algorithm doesn't match options

### ISSUE THREAD

**Issue by expipiplus1** [d-ronin/dRonin#1907]
The tooltip for the attitude algorithm lists "Simple" and "INSGPS" however the actual options are "Complementary", "INSIndoor" and "INSOutdoor".

https://github.com/d-ronin/dRonin/blob/9663d62eb6723f8fd2d906ce438184b57cd9b7d8/ground/gcs/src/plugins/config/attitude.ui#L518-L519

![image](https://gist.githubusercontent.com/expipiplus1/ad32b285c9def77af75c39129616f02e/raw/bfe49854588f629fc73c4a2a3038570830b7c795/tooltip.png)

**Comment by tracernz** [comment]
Thanks.

Best fix would be to delete the tooltip from the .ui file, and add a description element under the field in https://github.com/d-ronin/dRonin/blob/next/shared/uavobjectdefinition/stateestimation.xml#L5.
