### ISSUE TITLE
dR setup wizard shows serial ports

### ISSUE THREAD

**Issue by rlesac** [d-ronin/dRonin#1911]
* Seen in version (release version or githash):  Release-20170717: 20170715-1283f272
* On flight controller (if applicable): SR F3

Issue details: 
Upon starting the wizard, all the available ports are grayed out and can't be chosen.

![dronin-wizard-err](https://user-images.githubusercontent.com/10945003/29071234-ec980bf4-7c42-11e7-8b78-db7084b74a2e.png)

**Comment by mlyle** [comment]
We should probably filter out serial from here--- only USB attached (autoconnected) flight controllers are supported by the wizard, I think.

**Comment by tracernz** [comment]
https://github.com/TauLabs/TauLabs/issues/1861 would be nice, may look at it one day.

**Comment by mlyle** [comment]
@tracernz -- flyingpi/sim would benefit.
