### ISSUE TITLE
Wrong flight mode reported by FrSKY telemetry

### ISSUE THREAD

**Issue by nmaggioni** [d-ronin/dRonin#1913]
* Seen in version: 
  * FC: _Release-20170717_ (1283f272)
  * GCS: _20170715_ (1283f272)
* On flight controller: BrainFPV RE1

##### Issue details:

As per [dRonin's FrSKY S.PORT Telemetry docs](https://github.com/d-ronin/dRonin/wiki/User-Guide:-FrSKY-S.PORT-telemetry#data-sent-by-module), the RPM sensor reflects arming state and current flight mode number.

Arming state is reported correctly (leftmost digit `1` if disarmed, `2` if armed), but flight mode is not (at least on my BrainFPV RE1): i guess it should be ordered as set in the GCS - topmost mode is `1`, bottommost mode is `3` - but they are reported as 2-3-1 instead of 1-2-3. An edited screenshot is attached for a batter explanation.

![flightmodes_vs_telemetrymodes](https://user-images.githubusercontent.com/3594528/29168959-be857de2-7dd1-11e7-953d-23fe316bffcf.png)

**Comment by mlyle** [comment]
The mode number is not the switch index, but actually the order of flight modes as provided in the drop-down, that is:

Manual,Acro,Leveling,Horizon,AxisLock,VirtualBar,Stabilized1,Stabilized2,Stabilized3,Autotune,AltitudeHold,PositionHold,ReturnToHome,PathPlanner,TabletControl,AcroPlus,Acrodyne,Failsafe

So manual is 0, acro is 1, leveling is 2, horizon is 3, etc...

Updated the wiki page to make this clear.
