### ISSUE TITLE
brainfpv re1 v2 fc voltage problem

### ISSUE THREAD

**Issue by andro46** [d-ronin/dRonin#1931]
Hello.
I have problems with voltage output on betaflight and osd. It show 3,2V max when go to voltage scale and make it to max 255.. if i have lower numbers the voltage is even lower. Have some one any idea
 what to do?
![ref12](https://user-images.githubusercontent.com/24637180/29806601-8e0f34aa-8c90-11e7-80c7-23610791950d.jpg)
![re1 fc](https://user-images.githubusercontent.com/24637180/29806603-9206a912-8c90-11e7-84ad-7af2fade7c71.jpg)

**Comment by tracernz** [comment]
This is the repo for the dRonin software. Try https://github.com/betaflight/betaflight for BetaFlight issues. :wink:
