### ISSUE TITLE
OSD Menu: PID values are limited 

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#194]
BrainFPV TL Bug: https://github.com/BrainFPV/TauLabs/issues/33

When the user uses PID values that are outside of the range supported by the OSD menu, the menu limits it to the range supported by the menu, which is not ideal. The menu should have a way to detect if the PID terms are outside of the range and increase the range automatically without changing the PID values.

**Comment by tracernz** [comment]
Perhaps we should think about making the data from the limits attribute available in the generated flight code. https://github.com/d-ronin/dRonin/blob/next/shared/uavobjectdefinition/stabilizationsettings.xml#L14

**Comment by tracernz** [comment]
Related to my post above: https://github.com/TauLabs/TauLabs/issues/888
