### ISSUE TITLE
GCS: settings exports are blank?

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1956]
Reported on the forum, seems to be true.

@tracernz -- any chance this relates to recent GCS uav infrastructure changes?  @pug398 says upgrade/import may be broken too but I haven't tried this.

**Comment by tracernz** [comment]
Not sure. Can't really remember anything changing around this?

**Comment by mlyle** [comment]
I'll bisect sometime soon.

**Comment by mlyle** [comment]
Mostly fixed by #1958, but UAVOs still don't import
