### ISSUE TITLE
Reverse on output pane breokn for motors

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1960]

**Comment by tracernz** [comment]
Hmmm, looks simple enough: https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/config/outputchannelform.cpp#L270

**Comment by tracernz** [comment]
breokn how?

**Comment by mlyle** [comment]
The neutral ended up on one side.  Haven't looked at it.
