### ISSUE TITLE
smoothcontrol: fixes needed

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#1974]
* operates on failsafe
* incorrect bounds for non-rate modes
* bounds aren't used

**Comment by glowtape** [comment]
Oh hey, I ought to check the issues more often. Gonna look into this when I get up later today after my shift.

**Comment by mlyle** [comment]
Need to audit this myself to close (with #1950 merged it has a chance of being OK)

**Comment by mlyle** [comment]
OK
