### ISSUE TITLE
GCS/Flight: Remove temperature compensation infrastructure

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#198]
Only works on F1, poorly tested, uses up a tab in GCS.

**Comment by tracernz** [comment]
So this is like the first suggestion you will read on OpenPilot forums re: getting nav. working properly, is it all just rhetoric?

**Comment by mlyle** [comment]
@tracernz I've never done it, and we seem to fly nav without.

Original coptercontrol needed this, I bet.

**Comment by mluessi** [comment]
@mlyle why do you think this only works on F1? The code is definitely used on all targets.

**Comment by mlyle** [comment]
@mluessi I was wrong.  It's factored funny-- it lives down in attitude.c on F1 but in sensors.c on F3.  This is further proof that F1 and F3/F4 targets need to be adjusted to have the common code factored common rather than duplicated into different places as currently happens.
