### ISSUE TITLE
Can't see apply/save buttons on hardware screen

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2008]
* Seen in version (release version or githash): 6b208f+
* On flight controller (if applicable): Seppuku

Issue details:
 Apply/Save buttons at the bottom of the Hardware screen are not visible.

![screenshot](https://user-images.githubusercontent.com/7434287/33754166-d7ee2bf4-db9f-11e7-82df-09f19bd09ec2.png)

**Comment by tracernz** [comment]
Does it scroll?

**Comment by ufoDziner** [comment]
Not that I can see.

**Comment by tracernz** [comment]
Did you try mouse wheel? Not sure if the buttons are missing or just the scrollbar has visibility issues.

**Comment by ufoDziner** [comment]
Just verified.  No scrolling available via mousewheel.

**Comment by tracernz** [comment]
Kinda repros in Linux/X11. The scrollbar is there, and mousewheel works, but the buttons are only half-visible when scrolled all the way down. Looks like the widget encompassing the config form extends to the bottom of the window underneath the tab bar.
