### ISSUE TITLE
Multiple Rate Mode Stick Scaling and Expo settings

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2016]
* Seen in version (release version or githash): 
* On flight controller (if applicable): 

Issue details:
It would be great to have multiple/selectable Rate Mode Stick Scaling and Expo sets for fixed wing aircraft.  They could be programmed into the FC as an alternative to handling it on the transmitter.

**Comment by tracernz** [comment]
This is kind of a subset of an extension of #18, and has the same root problem (no support for multiple instances in LogFS/UAVSettings subsystems).

**Comment by mlyle** [comment]
I agree it's really #18.   Though you could say just about anything to be a subset of an extension of something else ;)

**Comment by mlyle** [comment]
Dup #18
