### ISSUE TITLE
RGB LED count

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2017]
* Seen in version (release version or githash): 
* On flight controller (if applicable): Seppuku

Issue details:
When there are no additional LEDs, the  Total LEDs listed are 0 on the RGB LEDs tab of the Modules section.  However, when additional LEDs are added (say 10 external), the Total LEDs listed must be set to 11 (I'm told to account for the one on the board).  If this box does include the onboard LED, it should default to 1, not 0.

Please set the default Total LEDs to 1, if it is to include the onboard LED, or have the Total LEDs only include the external count.  Thanks!

**Comment by mlyle** [comment]
Unfortunately this isn't so easily done-- we don't have a mechanism to have different defaults for different boards.  And setting the value to a number higher than 0 has the effect of enabling RGB LEDs.  We just have some special code on seppuku to force the LED value to 1 if it's zero to ensure the onboard LED always works.

**Comment by ufoDziner** [comment]
Can a note be added below the Total LEDs line that states:
(For Seppuku FC add 1 to the number of _external_ LEDs installed.)
?

**Comment by yamahabest** [comment]
Isn’t it possible to just always do plus one in the software, for the Seppuku boards?

**Comment by tracernz** [comment]
All of this code is totally generic. You could drop a Seppuku specific adjustment in there somewhere but it'd be a bit ugly. Maybe can do something better on the flight side...
