### ISSUE TITLE
Rename Revomini to Revolution

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#204]
The OP Revolution target had been named Revomini, which is confusing to users as this name is largely unknown. I suggest we rename it to Revolution or maybe OP-Revolution.

**Comment by tracernz** [comment]
Yeah, this is not a bad idea, especially now with Revo nano it might be even more confusing than ever.

**Comment by jihlein** [comment]
I can tackle this one.  Do we want Revolution or OP-Revolution?

**Comment by mlyle** [comment]
revolution sounds great :)

**Comment by tracernz** [comment]
I vote Revolution, it's consistent with our other target names. This will clash with #166

**Comment by mlyle** [comment]
Ah, you may want to build it on top of #166 in the assumption that will merge first

**Comment by jihlein** [comment]
I built this on top of #166, it builds cleanly and the GCS runs.  I don't have a Revolution board to test with.

I'll hold off submitting the PR until #166 is merged, then I'll rebase against that and submit the PR.

**Comment by mlyle** [comment]
Consider submitting it as a PR against the branch @tracernz has used in
#166.  Then we can test/take them together.  (but after first release,
unfortunately, it looks like)

**Comment by jihlein** [comment]
For the GIT challenged, what's the best way to submit this as a PR against tracernz's branch?

**Comment by mlyle** [comment]
To start your work, first you need to be based against #166; it sounds like you are, but if you need help with how to rebase on top of that I can.

Click "open a pull request".  For the base fork, choose "tracernz/dronin" and the base branch "revo-movingup"  (You may have to choose "compare across forks") for this to work.

Then for the head fork, pick your branch.

Then, @tracernz will get your change in his PR queue, and can merge it into his branch and maintain it with his PR.

**Comment by jihlein** [comment]
Thanks, got it completed.

**Comment by mlyle** [comment]
Cool.  I imagine we may not see him today, since it's now Christmas morning in .nz :)
