### ISSUE TITLE
Lux seems to not show hardware pane

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#2047]
Saying "Board detected, but of unknown type."

**Comment by tracernz** [comment]
That happens semi-regularly on all boards for me, disconnect/reconnect gets it right most times. For whatever reason the object that determines the board type fails 3 times in the initial telemetry rush AFAICT.

**Comment by mlyle** [comment]
This seems consistently reproducible on lux, which is strange.

**Comment by mlyle** [comment]
Confirmed on dtfc.  No errors on firmwareiapobject, and when i re-download it I get all 0's.. how strange.
