### ISSUE TITLE
AcroDyne shows as INIT on the CharOSD

### ISSUE THREAD

**Issue by yds** [d-ronin/dRonin#2065]
* Seen in version (release version or githash): Wired
* On flight controller (if applicable):  Omnibus F3 and F4

Issue details: When flipping through flight modes, all the ones I use put something sensible on the CharOSD (e.g. LVL, HRZN, ACRO, ACR+), but when I select AcroDyne the OSD shows INIT. Perhaps DYNE or ACDN or somesuch would be more apropos..

**Comment by mlyle** [comment]
Thx for report.
