### ISSUE TITLE
Should discover actuator curves as part of autotune

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#207]
We currently have TPA, which can reduce the PID gains based on throttle. However, this is kind of a hack and should ideally be handled by autotune. I haven't studied the autotune derivation in detail, but I wonder if we can collect the throttle position during autotune (so we know the stick position for hover) and then extrapolate to determine PID gains at different throttle positions (using an optimization procedure in the GCS). We would then need some way to store this efficiently and generate gains during flight. We could use a lookup table with linear interpolation, or maybe a low order polynomial for this.

**Comment by tracernz** [comment]
We can just use the actuator scaling to achieve this, if we could tune it automatically that would be superb.

**Comment by mluessi** [comment]
@tracernz yes, I guess if the actuator curve fitting makes things perfectly linear, the throttle PID scaling should be linear. Unless there are some other non-linear effects..

**Comment by mlyle** [comment]
@tracernz  So technically the accelerometer gives us a pretty good hint about instantaneous actuator performance...

**Comment by ufoDziner** [comment]
When this feature is implemented, it would be great if the hangtime throttle percentage was set based on the results.

**Comment by mlyle** [comment]
Upon looking at the data, this isn't practical.. and we're doing way better with regards to this anyways. opening a follow-on issue-- superseded #2114
