### ISSUE TITLE
Tiny error

### ISSUE THREAD

**Issue by humanoid2050** [d-ronin/dRonin#2075]
* Seen in version (release version or githash): branch next
* On flight controller (if applicable): 

Issue details:
I think there is a problem with shared/uavobjectdefinition/stabilizationsettings.xml line 52. 

limits="%BE:0:0.2,%BE:0:0.2:%BE:0:0.2"  should be
limits="%BE:0:0.2,%BE:0:0.2,%BE:0:0.2"

**Comment by tracernz** [comment]
Good spotting. :+1:  Do you want to submit a fix yourself?

**Comment by humanoid2050** [comment]
Didn't mean to make a new issue... but there it is.
