### ISSUE TITLE
GCS/Sparky2: Six point data collection timed out

### ISSUE THREAD

**Issue by jpbarraca** [d-ronin/dRonin#2094]
* Seen in version (release version or githash): Release-20180212.2: 20180213-020e58fb
* On flight controller (if applicable): Sparky2

Issue details:
Using OSX, six point calibration always times out after the clicking Save Position for the first time.
Tested with a USB cable and Telemetry through a BT.

The message is: Six point data collection timed out.

**Comment by mlyle** [comment]
After touching checkboxes, it works.  Before it fails.
