### ISSUE TITLE
Display hover % throttle next to hangtime info

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2098]
* Seen in version (release version or githash): 
* On flight controller (if applicable): 

Issue details:
Would be great to have the craft's hover % throttle displayed near the Max Power Add portion of the GCS, and include a tooltip that suggests the recommended Max Power Add.

**Comment by tracernz** [comment]
What about just having autotune tune the max power add to suggested value, or at least offer to?

**Comment by ufoDziner** [comment]
That would be cool to have it offer, and have the user be able to accept/reject.  Would still be nice to have it displayed as well for further incremental changes.

**Comment by jhitesma** [comment]
I was going to suggest what @tracernz said - have it set this automatically.  This would probably cut down on a good bit of confusion and make sure users get a reasonably sane value to start with.

But...I also agree with @ufoDziner that we should still display it to help guide users when/if they change that setting manually.
