### ISSUE TITLE
Need a warning or something for "Collective" on multirotor

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#2101]
At least two people have tripped over this so far.

**Comment by tracernz** [comment]
Collective selected somewhere, or?

**Comment by mlyle** [comment]
As an input channel-- it prevents throttle control.

**Comment by tracernz** [comment]
That's rather a peculiar thing to select unless you actually have collective pitch (e.g. Curtis Youngblood quads).

**Comment by mlyle** [comment]
Lots of people set e.g. all the channels to sbus and then map them, and we behave in a pretty unintuitive way then.

**Comment by yds** [comment]
how about disabling **Collective** in **RC Inputs** if **Vehicle Type:** _Multirotor_ in **Mixer Settings**

**Comment by mlyle** [comment]
No, because there are multirotors with collective.

**Comment by tracernz** [comment]
Is this still valid with #2117? Seems you can't really accidentally configure it now.

**Comment by mlyle** [comment]
#2117 helps mitigate it.  some people put the whole left column "sbus" and left it none, some people configured channels for everything because "why not".  But I think we should still consider doing more.

**Comment by glowtape** [comment]
Move the collective channel to the bottom of the list, followed by a warning about helis and such?
