### ISSUE TITLE
TBS Unify Pro Nano support

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2145]
* Seen in version (release version or githash): 
* On flight controller (if applicable): Seppuku at least.

Issue details:
Looking for support for the TBS Unify Pro Nano.  The following is from the manual.

SmartAudio LITE is used on the tiny Unify PRO nano. The software protocol is the exact same as on
Smartaudio V2.
However there are two limitations/caveats:
● It requires 3.3V level. The standard SmartAudio accepts 0.9V audio level. This means SA Lite is not
compatible with TBS CORE PRO, but compatible with all FC and other devices.
● Some FC targets have hardware incompatibility which does not sufficiently pull logic to zero on idle
or start of SA commands. According to the SA specification, each command has to start with logic
zero. The Unify Pro Nano is more susceptible to incompatibility with SA standard due to different
hardware layout

**Comment by mlyle** [comment]
Works already ;)
