### ISSUE TITLE
Packagework1 Cleanup: Linux

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#216]
Cleanup from #177

* Linux deb packaging doesn't work
* Linux deb menus/icons/etc are mismatched/misbranded

**Comment by PTDreamer** [comment]
Can you clarify if you want me to stand down or can I work on this and open a PR against your branch?

**Comment by mlyle** [comment]
If you want to handle this one, I'd appreciate it.  My branch has merged, so you can open it against the main project.

**Comment by mlyle** [comment]
At the same time, I realize I've left a bit of a mess and I don't expect you to clean it up-- only if you want to work on this.

**Comment by PTDreamer** [comment]
I'll take it :)

**Comment by fujin** [comment]
It would be nice for this to not be Debian specific.

**Comment by mlyle** [comment]
@fujin there's a package_all_compress if you just want the bins in a dir, and there's tools to convert debs to other packages.  I don't think we need to complicate our lives further by maintaining many variant packaging formats.

**Comment by fujin** [comment]
@mlyle that's not what I was suggesting - I meant not maintaining the Debian-specific build capabilities. Let a debian package maintain that in universe or whatever if they like. Produce tars, sigs, shas. Whatever though :cool:

**Comment by tracernz** [comment]
I vote we maintain the Debian packaging. It's very popular and we already steer people towards Debian in all our documentation. There will still be a zip package suitable for non-Debian dists.

**Comment by mlyle** [comment]
Fixed (at least mostly) by #253 .
