### ISSUE TITLE
Fixed wing must have motor

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#2165]
* Seen in version (release version or githash): Wired
* On flight controller (if applicable): Brain RE1

Issue details:
I'm trying to set up a glider, which has no motor.  The GCS does not allow "None" for the motor entry.

![glider](https://user-images.githubusercontent.com/7434287/38878160-27f53ce2-4215-11e8-8f2f-8ec3d067c9ef.png)

**Comment by mlyle** [comment]
Set it up like normally, then pick custom mixer type.  Note it will also expect you to have throttle etc input channels.

Will call this dup #1143 (added a related comment there).
