### ISSUE TITLE
SetupWizard not currently loading on Windows

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#2166]
Probably a DLL circdep thing.

**Comment by tracernz** [comment]
Got Windows VM up, confirmed rev cd7a75d8 is good, rev 7e1292ad is bad (as reported by @yamahabest, thanks!). Tried the dumb thing first and copied SetupWizard + Core plugins from good rev to bad rev, didn't help. Started setting up a dev environment with msys2 to bisect. Will continue after work.

**Comment by tracernz** [comment]
Almost done bisecting this... one or two builds left to do.

**Comment by tracernz** [comment]
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[e31466c9b68962faa803d69cb82483c2b653d2d9] remove RFM22 code but leave OpenLRS impl in
```
