### ISSUE TITLE
Buzzer inverted on HGLRC Zeus

### ISSUE THREAD

**Issue by lrvick** [d-ronin/dRonin#2185]
* Seen in version (release version or githash): 0548c4791 
* On flight controller (if applicable): HGLRC F4 Zeus

Issue details:

Buzzer is inverted. If everything in annuciator config is set to "haironfire" then buzzer is on no matter what. When I set it to other modes like "OK" it does different beep codes depending on if radio is on or off, etc, however they are always directly opposite to the on/off state of LEDs with the same setting.

If someone can point me the right direction in the code I am happy to do some testing myself.

I tried setting ```active_high``` to false with no love: https://github.com/d-ronin/dRonin/blob/next/flight/targets/revolution/board-info/board_hw_defs.c#L117 

Should I actually be trying to invert the GPIO_Mode or GPIO_PuPd  defaults here?

**Comment by mlyle** [comment]
How'd you wire the buzzer?

**Comment by mlyle** [comment]
I've confirmed that this works as expected on other OmniBus F4 targets.  I've also confirmed that, properly wired, switching active_high in the buzzer declaration reverses when the beeper is on.

I don't have that specific board, but there's no documentation to suggest that the buzzer is inverted from other OmniBus targets.  My best guess is that you've got things miswired somehow.

The forum, and to some extent, IRC, are for first-line support-- the issues database is expected to hold actual developer work items and not intended to be a Q&A forum.

**Comment by lrvick** [comment]
I have + to 5v and - to "BB" on this board.

I brought this up on IRC first and it was suggested I file this issue:
```
2018-04-17 02:40:36     lrvick  Oddly: set them all to haironfire and it is one nonstop beep now
2018-04-17 02:41:18     lrvick  Regardless of tx on or off
2018-04-17 02:45:25     tracernz        lrvick: that sounds like the output is inverted..
2018-04-17 02:48:12     lrvick  hmm. Is there a flag somewhere to flip it?
2018-04-17 02:51:08     tracernz        noo
2018-04-17 02:51:59     tracernz        feel free to raise an issue ;)
2018-04-17 02:52:12     tracernz        mention board type etc.
```

**Comment by mlyle** [comment]
Well, if you flipped the active_high in the code and still have an issue, there's something fundamentally wrong.  Possibly hardware, possibly wiring.

**Comment by lrvick** [comment]
@mlyle I was positive I had my wiring correct per labeled pins, but not positive the label/code mappings agree.

After some more trial and error changing annuciator options individually it turns out the pin labeled Buzzer/BB actually maps to "Alarm LED".

This would explain why flipping active_high had no impact.

I was able to get everything working by setting active_high=true on PIOS_LED_ALARM here:

```
diff --git a/flight/targets/revolution/board-info/board_hw_defs.c b/flight/targets/revolution/board-info/board_hw_defs.c
index a4c761e58..b6b01896b 100644
--- a/flight/targets/revolution/board-info/board_hw_defs.c
+++ b/flight/targets/revolution/board-info/board_hw_defs.c
@@ -82,6 +82,7 @@ static const struct pios_annunc pios_annuncs_v2[] = {
                                .GPIO_PuPd = GPIO_PuPd_UP
                        },
                },
+               .active_high = true,
        },
 };
```
Looks like a simple case of a pin mismatch on this board.

Still worth reopening to patch this in as a new board revision with a matching pios_annunc_v3_cfg ?

**Comment by tracernz** [comment]
Yeah, I think the pinout came up in the IRC conversation.
@mlyle I think this is yet another board with a slightly different combo. Has mem chip, but with omnibus-ish pinout.

**Comment by mlyle** [comment]
> Still worth reopening to patch this in as a new board revision with a matching pios_annunc_v3_cfg ?

Can we detect it in any way to do so?

**Comment by lrvick** [comment]
Not sure. Any suggestions on probing the device for unique features or identifiers?
