### ISSUE TITLE
Ubuntu install broken on 18.04 - requires unavailable dependency (libjasper1)

### ISSUE THREAD

**Issue by reubenfirmin** [d-ronin/dRonin#2212]
* Seen in version (release version or githash): Release-20180212.2

Issue details:
The Ubuntu packaged deb requires libjasper1, which is not available in the Ubuntu 18.04 repos. Downloading it manually from 17.10 repos & installing works (for now). Unclear why libjasper1 isn't available in 18.04, but build deps should likely be changed.

**Comment by tracernz** [comment]
Thanks for the report. That dep is from Qt's support for JPEG2000 (https://github.com/qt/qtimageformats/blob/5.9/src/plugins/imageformats/jp2/qjp2handler.pri). Not sure if we can disable that. Maybe we can just delete the jp2 imageformat plugin from our package.

**Comment by tracernz** [comment]
Previous report: https://github.com/d-ronin/dRonin/issues/1866. It's more serious now that 18.04 LTS is out. :/

**Comment by tracernz** [comment]
The relevant Ubuntu Qt packages:
https://packages.ubuntu.com/xenial/qt5-image-formats-plugins
https://packages.ubuntu.com/bionic/qt5-image-formats-plugins
They removed the jasper dep https://salsa.debian.org/qt-kde-team/qt/qtimageformats/commit/217ae80e8b6a650f2aa9147b105b1d81e1e53d1e

**Comment by mlyle** [comment]
Any easy way to fudge / remove the dependency at deb-build-time?

**Comment by tracernz** [comment]
@reubenfirmin Can you please test the deb in http://jar.lyle.org:8080/job/dronin/1798/Nodes=master/ ? Thanks.

**Comment by reubenfirmin** [comment]
That worked fine, and all appears functional. Thanks!

**Comment by tracernz** [comment]
Thanks for checking back, appreciate it. :+1:
