### ISSUE TITLE
AltitudeHold flight mode inoperative

### ISSUE THREAD

**Issue by LitterBugs** [d-ronin/dRonin#2216]
* Seen in version (release version or githash):  Pre-Inconcievable and #2215 
* On flight controller (if applicable): Seppuku

Issue details:
Selecting Altitude hold mode causes motors to drop to Neutral, Throttle is ineffective, And beeper sounds .-. "R" code.

Also noticed that there is still an ALT.H indicator on the Flight Data screen in GCS although there is no longer an AltitudeHold Module.  

If FC is connected to GCS when selecting Altitude Hold mode, Flight mode shows as Failsafe, the RC Input indicator turns red.  Hovering over it gives the message: "Error Code: Undefined      This should not happen"

**Comment by glowtape** [comment]
When I define a Stab1/2/3 with AltitudeHold as thrust mode, it seems to work fine. When I specify AltHold as flight mode, it goes into failsafe. Gonna look into it, must be a slight snafu with the flight mode config.

**Comment by tracernz** [comment]
Thanks for tracking this down @glowtape :+1: .

**Comment by mlyle** [comment]
Introduced by me in 3dc6eb0ad9 when I removed duplicated code (but a little too much) added in 7ca566633d.  Sorry :/

**Comment by tracernz** [comment]
No prob :wink:
