### ISSUE TITLE
disambiguating LQGA and LQGR labels in CharOSD

### ISSUE THREAD

**Issue by yds** [d-ronin/dRonin#2223]
* Seen in version (release version or githash): Next
* On flight controller (if applicable):  Omnibus

Issue details:

In CharOSD the labels `LQGA` _LQG Leveling_ and `LQGR` _LQG Acro_ are not consistent with the GCS labels.

Adding to the confusion, uppercase `A` and `R` in in the default CharOSD font are almost indistinguishable.

How about changing the CharOSD labels to `LQGL` _LQG Leveling_ and `LQGA` _LQG Acro_?
or leave it as `LQGR` _LQG Acro_ 

The main issue is that one has to squint and double take to tell the difference between `LQGA` and `LQGR` -- changing to `LQGL` for _LQG Leveling_ takes care of that.

**Comment by mlyle** [comment]
Fixed by #2224
