### ISSUE TITLE
SmartAudio for non graphical OSD

### ISSUE THREAD

**Issue by error414** [d-ronin/dRonin#2235]
* all versions
* HGLRCF4 mini

It would be nice to add support for smartaudio to non graphical OSD. And settings over OSD menu or better, over LUA script and frsky telemetry like in BF.

Lot of people are used to use LUA script or OSD menu for settings FC, it is very common in kiss/F1/BF world.

**Comment by fxbisto** [comment]
I would like to see this also.
I've got a bunch of time at the moment but my coding isn't necessarily the best :)
beta/clean/butter/XYZflight uses a stick command to enter an OSD character menu which is navigated by pitch/roll stick inputs. It works very well.
The ability to manipulate video transmission channel and output power over UART is very desirable in a modern flight control firmware.
