### ISSUE TITLE
GCS: Save Log to File error

### ISSUE THREAD

**Issue by raemin** [d-ronin/dRonin#2237]
* Seen in Inconceivable build #1975: 
* On flight controller : Seppuku and PikoBLX

Issue details:  GCS successfully logs the setting objects, but constant stream of errors while trying to log the data objects.

https://forum.dronin.org/forum/d/578-gcs-logging-issue

**Comment by tracernz** [comment]
https://github.com/d-ronin/dRonin/blob/d654e8831499ca74ae5bd24dd739033873a72d22/ground/gcs/src/plugins/uavtalk/uavtalk.cpp#L579

TX_BACKLOG_SIZE (2 * 1024) seems to be smaller than the QFileDevice buffer/chunk size, so it starts failing and never recovers after the first few objects. We should probably only do that check for non file devices.

**Comment by raemin** [comment]
Tested build 2238 on Seppuku, bug fixed.
