### ISSUE TITLE
Brain: Make connection diagram

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#230]
~~Currently uses the Sparky one?~~
Doesn't have one.

**Comment by tracernz** [comment]
https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/boards_brainfpv/brain.h#L69

**Comment by tracernz** [comment]
Re-opening this because #239 didn't add a connection diagram, just removed the false one.

**Comment by mlyle** [comment]
There's no new OG brains, and other un-covered targets.  Any objection to WONTFIX?

**Comment by tracernz** [comment]
Yeah, it's unfortunate that this will likely never happen.
