### ISSUE TITLE
GCS: select flash file window opens behind main window

### ISSUE THREAD

**Issue by jhitesma** [d-ronin/dRonin#236]
rev e58985a0 on Ubuntu 15.10

When I'm reflashing a board if I have GCS full screen and hit "Open File" the new dialog opens behind the maximized main window making it kind of a pain to use.

**Comment by tracernz** [comment]
Interesting, this issue doesn't occur on 14.04.

**Comment by jhitesma** [comment]
Upon further testing it also happens if I'm not full screen, just the main window is big enough to block the file open dialog.

However...it doesn't happen the first time.  

First time I open the "Open File" dialog it open on top like it should.  But if I close it or select a file and the hit "Open File" again then it opens behind the main window.

**Comment by tracernz** [comment]
Okay, that occurs on 14.04 too.

**Comment by VArcht** [comment]
Possibly related open issue here https://bugreports.qt.io/browse/QTBUG-46626

**Comment by tracernz** [comment]
I tried this and still same result (dialog is behind main window on second and subsequent uses):

``` cpp
/**
 *Opens an open file dialog pointing to the file which corresponds to the connected board if possible
 */
QString UploaderGadgetWidget::LoadFirmwareFileDialog(const QString boardName)
{    
    QString fwDirectoryStr = getFirmwarePathForBoard(boardName.toLower());

    QFileDialog dialog(this);
    dialog.setFileMode(QFileDialog::ExistingFile);
    dialog.setWindowTitle(tr("Select firmware file"));
    dialog.setDirectory(fwDirectoryStr);
    dialog.setNameFilter(tr("Firmware (fw_*.tlfw);;"
                            "Bootloader Update (bu_*.tlfw);;"
                            "All (*.tlfw *.opfw *.bin)"));

    QEventLoop loop(this);
    connect(&dialog, SIGNAL(finished(int)), &loop, SLOT(quit()));
    dialog.show();
    dialog.raise();
    dialog.activateWindow();
    loop.exec();

    return (dialog.result() == QDialog::Accepted) ? dialog.selectedFiles().at(0) : QString();
}
```

**Comment by mlyle** [comment]
Won't be further improving this before samsara; deferring.

(Less important with auto-upgrade).

**Comment by mlyle** [comment]
Same rationale used to defer again.

**Comment by tracernz** [comment]
I can't find any reports of this from other Qt users. That + my issues with Qt OpenGL stuff within GCS  main window/uavgadget vs in standalone apps makes me quite suspicious of our main window + uav gadget stuff...

**Comment by jhitesma** [comment]
I'm not even sure if I can repo this anymore...the linux notebook I was using it on where this was happening is 32bit so I abandoned it awhile back.  I haven't seen it happen on MacOS or Windows - and don't have a newer system running Linux to test on right now.

**Comment by tracernz** [comment]
I've seen it recently but never found a reliable repro like the original issue.

**Comment by mlyle** [comment]
I haven't seen this, but here's one you can consistently repro:  if you have setup wizard open, and plug in a FC that needs upgrade or wants to spawn setup wizard, it opens in front of the main window but behind setup wizard, modal, and setup wizard freezes (and must be moved out of the way)

**Comment by tracernz** [comment]
Can you open an issue for that? It's very different to this.

**Comment by mlyle** [comment]
I think it's #1285 actually ;)   We have a lot of modal dialogs with no clear parent; we have a lot of things that can spawn modal dialogs at any time.

**Comment by jhitesma** [comment]
Confirmed I still can't repo this on mac and windows.  But still can't confirm or deny on linux because I still haven't setup a linux machine with a GUI to test on :(  If no one else has noticed and you guys can't repo I'm willing to assume it's no longer an issue.  ( I kind of wonder if it went away when we dropped support for 32bit since that was when I quit using my linux notebooks since they were all old 32 bit machines...)
