### ISSUE TITLE
Widget to choose a configuration often shows up behind splash screen

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#237]
When you don't have a config, the dialog that prompts you to create one is often in a bad place.

**Comment by tracernz** [comment]
.raise() would be the solution I think?

**Comment by mlyle** [comment]
I don't think so.  I think the splash needs to get hidden during this.  Because I can click / drag around that dialog but it's still "under" the splash in Z.

**Comment by tracernz** [comment]
Oh yep, that makes sense.

**Comment by mlyle** [comment]
Put into renatus on the chance i'll get to it.
