### ISSUE TITLE
GCS: firmware tab interface usability

### ISSUE THREAD

**Issue by jhitesma** [d-ronin/dRonin#249]
The buttons on this tab kind of need a full rethink.

The way they appear and disappear isn't very good UI design.

And it's possible to do unintended things.  Like if you hit Halt then "Reset" goes away but "Open File" is still available and active.  Clicking "Open File" opens the open file dialog...but the halt process gets lost.  The board appears to halt, but the GCS never notices and you're left in a funky state.  

At a minimum we should disable "Open File" while a halt is in progress.  But rethinking the entire tab is probably a good long term goal.

**Comment by tracernz** [comment]
I've been meaning to do something about this. I hate how the buttons appear and disappear too.



On Fri, Dec 11, 2015 at 10:30 PM -0800, "Jason Hitesman" <notifications@github.com<mailto:notifications@github.com>> wrote:


The buttons on this tab kind of need a full rethink

The way they appear and disappear isn't very good UI design

And it's possible to do unintended things Like if you hit Halt then "Reset" goes away but "Open File" is still available and active Clicking "Open File" opens the open file dialogbut the halt process gets lost The board appears to halt, but the GCS never notices and you're left in a funky state

At a minimum we should disable "Open File" while a halt is in progress But rethinking the entire tab is probably a good long term goal

-

**Comment by mlyle** [comment]
Mostly fixed by #677
