### ISSUE TITLE
GCS:Configuration: Scrollbar obscures tabs

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#260]
This was reported in TauLabs/TauLabs#1146 and is relevant on Linux as well (OS X is okay due to the native scrollbar style used). The issue is becoming worse as more and more tabs get added. Should be easy enough to fix by applying a CSS style.
![screenshot from 2015-12-13 23 05 24](https://cloud.githubusercontent.com/assets/9995998/11766468/472c7b44-a1ee-11e5-87c6-404572e133a3.png)

**Comment by tracernz** [comment]
For reference, OS X:
<img width="96" alt="screen shot 2015-12-15 at 10 08 58 am" src="https://cloud.githubusercontent.com/assets/9995998/11794021/f31c04da-a313-11e5-8430-f43b54d76551.png">

**Comment by mlyle** [comment]
The styling on OSX is bad too because if it lines up wrong you may not see there's anything to scroll too (since the scrollbar auto-hides)

**Comment by tracernz** [comment]
If we made it have the OSX style and remain visible all the time it could be good.
