### ISSUE TITLE
GCS: Fix Authors Credit

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#271]
In the GCS "Help->About Authors.." is still referring to the TL project and the list of authors seems to be outdated. Ideally, the authors list should be created automatically from git commits.

**Comment by mlyle** [comment]
I think we should really do this for Quixote.

**Comment by tracernz** [comment]
Yes. #336 is the solution?

**Comment by mlyle** [comment]
I think so.  An 18 month half life seems fair, but open for more discussion.
