### ISSUE TITLE
Crash info doesn't include OS

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#287]
Crash reports seem to have omitted what OS the user was running.

**Comment by VArcht** [comment]
Not sure if I dare to dig into crash reporting but do we want OS details or just platform? Compile vs. runtime?

**Comment by dustin** [comment]
It should be really easy to get more info than there is.  OS X vs. Linux vs. Windows (which would be surprising since there's no support for crashes from Windows) would be good.  More info == more better.

Compile would be more than we have.  Runtime info would be pretty great.  `system_profiler -xml` type things would be overkill (TIL, that includes system.log).

**Comment by mlyle** [comment]
Last try: connects #326
