### ISSUE TITLE
POItracking to brushless gimbal via MAVLink

### ISSUE THREAD

**Issue by Ga1j1n** [d-ronin/dRonin#288]
Existing code (Potentially removed) is aimed at direct servo control, Propose enhanced POITracking control via MAVLink or STorM32 protocol directly to STorM32 brushless gimbal.

Project should re-enable and modify existing position tracking / following code with the STorM32 filling the role of the SparkyBGC with a readily available, low cost and opensource project.

Similar basic functionality is currently available for the Pixhawk

http://copter.ardupilot.com/wiki/common-storm32-gimbal/

https://github.com/TauLabs/TauLabs/wiki/User-Guide:-POI-tracking

https://vimeo.com/127901407

http://www.olliw.eu/storm32bgc-wiki/Main_Page

**Comment by jihlein** [comment]
Would love to see this for STorM32 gimbal controller, been thinking about it myself.  I have a STorM32, not sure where to start with code yet, but happy to help test and any other way I can.

**Comment by mlyle** [comment]
It's probably not too hard to get the POI information shoved into Mavlink.
