### ISSUE TITLE
Win 10 GCS Next crashes with "Netbook" selection

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#291]
GCS crashed when selecting "Netbook" from the layout? screen after a fresh "next" compile on Windows 10.  The "Developer" option worked.

**Comment by mlyle** [comment]
Seems to work on Mac.  Will try on Win10 next.

**Comment by mlyle** [comment]
Can you repro this?  I can't reproduce.  Just tried netbook layout on Win10.

**Comment by ufoDziner** [comment]
I will attempt to when I get home.  How do I clear out the default that it now uses?

**Comment by mlyle** [comment]
There is a menu item to import/export gcs settings.  It also lets you reset
the config.

The windows installer also adds a shortcut to clean the config but that was
broken until a couple days ago.

**Comment by ufoDziner** [comment]
Reproduced after resetting the config.  Screenshot attached.
![netbook_failure](https://cloud.githubusercontent.com/assets/7434287/11989513/e919d42a-a9b3-11e5-954c-0d1dfbc8f19e.png)

**Comment by mlyle** [comment]
@ufoDziner Can you try it from the installer package to see if it works on your machine that way?

**Comment by ufoDziner** [comment]
I can, but need some direction as to how to compile it for a package, and/or find it in the build to install.  Sorry for the hassle.

**Comment by mlyle** [comment]
Preview release packages are here:

https://github.com/d-ronin/dRonin/releases/tag/preview-20151218

No hassle-- all bug reports are valuable and your help nailing this down is useful.

If it works in the installer, it's primarily a pain for devs and we'll defer this issue out of Renatus, though, I think.

**Comment by ufoDziner** [comment]
That release installed package works just fine with the netbook configuration.

**Comment by mlyle** [comment]
OK.  So there's probably a problem with some of the paths and how they work in the build directory configuration.  Deferring from Renatus.

**Comment by mlyle** [comment]
Duplicate #352
