### ISSUE TITLE
GCS: welcome screen: None of the "buttons" go anywhere when pushed

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#292]
This wasn't understood before--- it seems that they stop working after visiting the flight data pane.  May or may not relate to these logs:

```
19:09:52[WARNING]"---------------------------------------------------------------------"
19:09:52[WARNING]"ModelViewGadgetWidget::paintGL() "
19:09:52[DEBUG]GLC_OpenGlException : ModelViewGadgetWidget::paintGL() VERY BAD : UNKNOWN ERROR
```

Unknown if specific to OSX.

**Comment by mlyle** [comment]
Seems to JUST be OSX.

**Comment by mlyle** [comment]
Bumping out of Renatus because less severe-- they do work for initial navigation in the GCS.

**Comment by mlyle** [comment]
Doesn't manifest on Linux in current GCS.  need to try on mac again.

**Comment by tracernz** [comment]
I have seen this in the last few months on mac IIRC. Worth checking it since we went to Qt 5.8.

**Comment by tracernz** [comment]
Anybody seen this in the last few months?

**Comment by mlyle** [comment]
It only happened to me on Mac OS X which I've not used in awhile.  Can retest

**Comment by jhitesma** [comment]
Just tried it on MacOS with a build from May 8th (most recent I had on hand) and wasn't able to repo.  Can try again later with a newer build to re-confirm.

**Comment by mlyle** [comment]
I can't repro either!  Woot.
