### ISSUE TITLE
OpenGL / Mesa on windows needs a permanent fix

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#295]

**Comment by mluessi** [comment]
Can you give more details? It isn't clear to me what this means from the title alone.

**Comment by mlyle** [comment]
People still are tripping over the thing where with old Intel and other chipsets that don't ship an OpenGL implementation that the GCS doesn't work.  We need a prominent errata and instructions on how to deal with it.

**Comment by mlyle** [comment]
@PTDreamer -- do you have a fix for this or did you just encounter it?

**Comment by PTDreamer** [comment]
Hi have the dump where it throws the exception so I can try and have behave
more graciously. Also I had a PR once to detect the need for the sw mesa
and download it and install it if needed.
Also there seem to be two different issues, one that causes some widgets
not to be rendered and another which causes a segfault.
Em 31/12/2015 08:04, "Michael Lyle" <notifications@github.com> escreveu:

**Comment by mlyle** [comment]
Won't be further improving this before samsara; deferring.
