### ISSUE TITLE
"0 module is in warning state"

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#296]
Need to run this down / make it helpful.  @5PAZT1C

**Comment by 5PAZT1C** [comment]
I cant find any indication of what this warning is in the GCS. everyhing seems to be working fine, maybe this is just a bug? is it specific to cc3d?

**Comment by jhitesma** [comment]
I've seen it on Naze32 and Sparky so it's not just cc3d.  Probably on everything.

**Comment by pug398** [comment]
This is inherited and on many platforms. Has not affected flight but has been previously mentioned. It is good you would like to try and get it fixed. The problem is not in TL 6e3d but is in TL 630C. I will try to narrow the gap...

**Comment by pug398** [comment]
The closest I can get at the moment is 20151007 b0fc is good and 20151014 555f introduces "module 0" error. A few changes in about a weeks time for you to sort through.

**Comment by mlyle** [comment]
Yah, unfortunately there's nothing interesting in those 5 PRs.  I think I'd seen it before.  Will add an assert to the UI to see if I can figure out why.

**Comment by SystemsGuy** [comment]
Confirmed on Sparky1 on pre-release. 
![0 module is in warning state issue 296 d-ronindronin - mozilla firefox_2015-12-18_21-40-08](https://cloud.githubusercontent.com/assets/2819484/11911092/ffa37dbe-a5cf-11e5-9631-86e758c5576d.jpg)

**Comment by mlyle** [comment]
OK, so this one is figured out / there's a PR open.   Basically, there's a bunch of other fields in systemsalarm that if they weren't 0 or 1 would cause this message because we scanned the structure wrong.  There was a change in that revision range that made it so we almost always have a field with value not 0 or 1.
