### ISSUE TITLE
Support the Naze32 rev6

### ISSUE THREAD

**Issue by hernick-qc** [d-ronin/dRonin#298]
dRonin should support the new Naze32 revision 6 board, which is now the only official Naze32 you can get from many official Abusemark resellers. It doesn't seem like there's a lot of work required to get this working.

The main difference is the use of the MPU-6500 instead of the MPU-6050, and this new chip is already supported by the BrainFPV MPU-9250 i2c driver.

Tracernz has an example hack to get the Naze32 rev6 working at https://github.com/tracernz/TauLabs/tree/naze-rev6-hax

It also uses the BMP280 barometer, for which jihlein has written a driver that can be found on his TauLabs fork at https://github.com/jihlein/TauLabs/tree/myNext/flight/PiOS  - Common/pios_bmp280.c inc/pios_bmp280.h and inc/pios_bmp280_priv.h

**Comment by hernick-qc** [comment]
I'd like to try to get this working over the holidays, and I'd like some guidance as to the best approach.

Should all drivers (MPU-6050, MPU-6500, BMP280, etc..) be included in all naze32 firmware builds, with onboard autodetection of the proper driver to use?

Or should this be a build-time setting (choosing between <=rev5 or rev6), with only the required drivers being included the firmware?

**Comment by CptanPanic** [comment]
Any new updates for this?

**Comment by tracernz** [comment]
Waiting on me to have time to finish driver still.

**Comment by mluessi** [comment]
@tracernz which driver? I have a BMP280 one that I got from @jihlein, maybe he can make a PR for it?

**Comment by tracernz** [comment]
Common mpu driver.

**Comment by jihlein** [comment]
@mluessi I can make a PR for the BMP280 driver, but will most likely need to wait until the weekend, going business traveling again....

**Comment by tracernz** [comment]
We don't currently support barometer on any version of the naze so no rush on that.

**Comment by tracernz** [comment]
Fixed by #757.
