### ISSUE TITLE
Report of wrong (TL) shortcut on Windows

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#304]
from @pug398

**Comment by pug398** [comment]
With a reboot this morning the TL desktop icon (with dRonin text) changed to dR. It was the first reboot after running dRonin PR2 installer.

**Comment by mlyle** [comment]
Interesting.  So some remnants of TL stuck around.

**Comment by mlyle** [comment]
I played a little with reproducing this and wasn't able to get it consistently.. I think we'll ship with this.  It seems to do the wrong thing (until reboot) if you're installing over Tau Labs.

**Comment by VArcht** [comment]
I saw this when I was working on the branding, I think the OS is caching the icon? I googled some and didn't see a clear solution. Perhaps changing the icon name would get around it?

**Comment by mlyle** [comment]
But we changed the name :/

**Comment by VArcht** [comment]
hmm, right, does it get an alias somewhere?

**Comment by mlyle** [comment]
Doesn't seem to happen anymore.  I think it's a short-lifetime thing after upgrade.
