### ISSUE TITLE
GCS : Branding - Vehicle Wizard

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#305]
Still has Tau Labs branding.
![dronin gcs_2015-12-18_20-51-21](https://cloud.githubusercontent.com/assets/2819484/11910894/55d734e8-a5c9-11e5-84d3-cc6ab2529b49.jpg)

**Comment by tracernz** [comment]
Would it be a better idea to remove the branding and make it "Vehicle Setup Wizard" instead of "dRonin Setup Wizard"? I know @PTDreamer has done quite a bit of this where possible.

**Comment by mlyle** [comment]
That's mostly what @mluessi did, I think-- just the window title says dRonin I believe and Tau Labs was just removed from all the text.
