### ISSUE TITLE
GCS : Firmware Screen 

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#307]
After flashing, there is an unlabeled
![dronin gcs_2015-12-18_21-03-11](https://cloud.githubusercontent.com/assets/2819484/11910932/2b901356-a5cb-11e5-8c5f-6c8a9235e845.jpg)
 text entry box on the "Loaded" box.

**Comment by mlyle** [comment]
Have you tried filling that in, and then flashing?  I think it may show up in the "user defined" on device then, for now on.

**Comment by tracernz** [comment]
It's labelled on the left in the info box? It allows you to put a custom string on the board.

**Comment by mlyle** [comment]
Tested this and it works-- after filling in "icee rocks" on the right and flashing I have "Icee rocks" on the left side on the "on device"
