### ISSUE TITLE
openpilot wiki links rename / replace with something useful

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#308]
ESC Signal selection screen in GCS has "more information" link which links back to d-ronin github that then points to the deaded OpenPilot wiki
![onlinehelp turbopwm esc s d-ronindronin wiki - mozilla firefox_2015-12-18_21-08-41](https://cloud.githubusercontent.com/assets/2819484/11910952/d384e2f8-a5cb-11e5-8f76-261d925343bc.jpg)

**Comment by mlyle** [comment]
@hernick-qc Would you be willing to look at this?  It'd be a big help :)

**Comment by hernick-qc** [comment]
I'll take it.

Actual issue is that there are still many links to the old OpenPilot wiki inside the dRonin wiki. I will update the OnlineHelp: pages' content to include useful information rather than dead links.

**Comment by tracernz** [comment]
As @hernick-qc says, there are quite a number of Online Help pages that point to the now dead OP wiki.

**Comment by mlyle** [comment]
@hernick-qc -- feel free to create subissues and maybe some of us can take some of the load.

(I can't really look at doc myself much though until closer to release date)

**Comment by tracernz** [comment]
We should rename this page to OnlineHelp: ESC Refresh Rate or similar before our first release, doing it after will break old release help links. I removed the OP link and added a link to our Oneshot125 page for now. https://github.com/d-ronin/dRonin/wiki/OnlineHelp:-TurboPWM-ESC's

**Comment by mlyle** [comment]
Renaming and deferring based on a lot of stuff done already.

**Comment by joeynuggetz** [comment]
Also broken.......

Help button on "Output" page in GCS links to http://wiki.openpilot.org/display/Doc/Output+Configuration which is non-existent.

Broken link on the main help page for "Input" screen in GCS. Link to "Input Configuration" points to http://wiki.openpilot.org/display/Doc/Input+Configuration which is non-existent.

**Comment by jpbarraca** [comment]
Should we/can we salvage some information from the old openpilot wiki to speed up these issues?

**Comment by joeynuggetz** [comment]
All links that appear on bottom of the landing page after clicking on ? on the Vehicle page all point to old OpenPilot URLs. GCS version (20160323-fc5c8e83)

![image](https://cloud.githubusercontent.com/assets/14797846/14057693/4297f606-f2d6-11e5-95f8-4b8a0bc98007.png)

**Comment by mlyle** [comment]
Removed the last vestiges of openpilot from the wiki and improved documentation some.
