### ISSUE TITLE
Able to ARM with Critical Input Error.

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#309]
Not sure what I did to go "invalid", but I'm able to stick arm..
![_2015-12-18_21-26-21](https://cloud.githubusercontent.com/assets/2819484/11911036/3672ab5a-a5ce-11e5-873e-27820cc8c28e.jpg)

**Comment by pug398** [comment]
I had similar on sparky1 doing firmware upgrade. In my case the r/c input alarm stayed red even though there was valid input and hardware selection was correct and rx input type was correct. Should have changed to yellow. With red alarm I could still run input wizard successfully at which time it went from red to green.

**Comment by mlyle** [comment]
Haven't repro'd this stuck-alarm-in-GCS issue, closing for now.
