### ISSUE TITLE
Tricopter setup incorrect after power cycle(s).

### ISSUE THREAD

**Issue by jihlein** [d-ronin/dRonin#315]
Setup AQ32 for Tricopter from clean eeprom.  PPM rx, batt monitor, FrSky sensor hub, openlog, gps, external mag.

On Vehicle tab, Vehicle type multirotor, Frame type Tricopter Y.  Motor output channels 1,2, and 3 set to Channel2, Channel1, Channel3, respectively.  Tricopter Yaw Motor channel set to Channel5.

On Output tab channel banks 1, 2,and 3 set to SyncPWM, SyncPWM, 330 Hz respectively.  Resolution 12MHz for all channels.  Channel min/neutral/max set at 120/131/250 for motor channels, 2000/1500/1000 for servo.

Flew basic stability checks, including autotune.  Flight and autotune went well.  Applied the autotune gains, and flew them.  After flight (and a few power cycles) while creating autotune report, noticed that the GCS reported my configuration was quadx.  Looking at the Vehicle tab, Quadx is now the selected frame type, the 3rd motor channel and tricopter servo channels are set to none.  Output tab is as originally configured, and motors and servo still respond correctly for the tricopter configuration.

Inspection of SystemSettings.AirframeType showa QuadX config.

After power cycling again, the same erroneous configuration is reported, but the vehicle still behaves as a tricopter, motors and servo working as configured.

**Comment by mlyle** [comment]
Initially triaging into renatus, but probably punting out.

**Comment by jihlein** [comment]
Can't replicate this issue any longer after rebasing to current next and rebuilding.  The legacy TauLabs issues are still there.  I've managed to fix the extra motor definition, but have not made any progress on the missing servo channel display.  Working on getting somewhat familiar with the GCS code.

I'll leave this issue open a little longer to see if the original problem reappears while testing.

**Comment by jihlein** [comment]
Looking back into this, it appears to be caused by the fact that out of the SystemSettings->AirframeCategorySpecificConfiguration UAVO, only the 1st 32 bits out of the 128 bits of data are actually getting saved.  The tricopter servo configuration is stored in bits 33-36.  I've also noticed that in order for SystemSettings->AirframeType to be reliably saved, the save button on the GCS Vehicle setup page has to be selected multiple times.  

Setting the servo channel directly in the UAVO browser and saving it there seems to work.  For example setting SystemSettings->AirframeCategorySpecificConfiguration[1] to 5 and uploading and saving it via the browser sets the tricopter servo channel to 5, and it is there on subsequent power ups.

**Comment by mlyle** [comment]
Same as (later, but more information) #1220
