### ISSUE TITLE
Flight: calibrate magnetometer vs. throttle/current

### ISSUE THREAD

**Issue by DTFUHF** [d-ronin/dRonin#318]
Pixhawk has this calibration where you spin up motors while the aircraft is immobilized and it calibrates compass measurements as throttle increases. It seems to have reduced heading drift on multirotor takeoff for me, but I also think improper implementation of this calibration could cause problems. An interesting idea to persue however.

**Comment by mlyle** [comment]
Gonna call this dup #488 ; it's not exactly, but #488 will cover it, so...
