### ISSUE TITLE
Map gadget should point to bing 

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#324]
Bing actually works well.  Google does not.

**Comment by mluessi** [comment]
Can you elaborate? Google is working fine for me.

**Comment by tracernz** [comment]
We are actually using the TL API key ATM and from what I understand the way the API is (ab)used is not in accordance with the TOS.

**Comment by mluessi** [comment]
@tracernz yes, this is something that needs to be fixed.

**Comment by mlyle** [comment]
@mluessi At some levels of zoom the OP map gadget works.  At full zoom out or some inbetween levels it doesn't work for me (just shows the default "background").  The bing settings work across all levels and load more quickly.  Does it work at full zoom-out for you with Google?

**Comment by mluessi** [comment]
Google seems to be working for me. However, @tracernz brought up a good point. We shouldn't be using gmap if it is against their TOS. Even if we use it, we would need to update the API keys, as we currently don't have control over them. We should check the Bing TOS to make sure we are in the clear.

**Comment by mlyle** [comment]
Google doesn't issue new maps api keys, I believe, too.

No one lets you embed maps free-- except open street map.  So technically
we need to pull everything, which we should probably do... But maybe ship
our first release close to as is before we  deeply audit things

**Comment by PTDreamer** [comment]
The map graphics don't use/need an API key. It is only used for geocoding which is used even when Bing is set as the map provider.
Google maps are working fine for me,  I would try to clear the cache.

**Comment by tgreer** [comment]
I've never had a reliable Map in GCS. it's always screwed up as soon as I've zoomed out.

**Comment by PTDreamer** [comment]
Can you make a video of the issue?

**Comment by mlyle** [comment]
Meh, it's been reliable for me recently.

**Comment by PTDreamer** [comment]
Fyi api key is only used for geocoding (i.e. string to location) not for
map tile fetching

Em 24/09/2016 06:38, "Michael Lyle" notifications@github.com escreveu:

**Comment by mlyle** [comment]
@ptdreamer -- Hey!  Glad you're still around.

Yes.  I think the main problem I was encountering is it was possible to try and fetch illegal tiles on the furthest zoom level out if your resolution was high enough and it made it do weird things.  We've corrected that (if the window is too big we force people to zoom level 2).
