### ISSUE TITLE
We should build GCS with -Bsymbolic-functions

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#328]
It can be expected to improve GCS startup times and initial performance significantly.

**Comment by tracernz** [comment]
Seems to be a bit faster. :+1:

**Comment by mlyle** [comment]
Wanna submit a PR since you tried it? ;)

**Comment by mlyle** [comment]
(I made one attempt but it only seemed to do anything on Linux; having trouble convincing Windows to build plugins with it)

**Comment by tracernz** [comment]
Can do, I just hacked it in and tested on Linux only at this stage.

**Comment by mlyle** [comment]
Measured as not much of a win on Linux and difficult to do equivalent elsewhere.
