### ISSUE TITLE
Need minimum deadtime on syncpwm output

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#337]
re: issue #323 

My proposed fix is, around here:

```
        if (output_channel_mode[servo] == SYNC_PWM_TRUE) {
                TIM_Cmd(chan->timer, DISABLE);
        }
```

To ensure that the count value is past max+10us.  This implicitly assumes the max values for the things in the same bank are the same.

It's super unfortunate that we're not using hardware oneshot/single count functionality which I think exists on all of our targets.

**Comment by mlyle** [comment]
How it would work with hardware oneshot:

A) don't disable the timer explicitly there
B) set the count period to be that max+10us or max*1.25 or whatever value.
C) only enable timer if already disabled.

**Comment by tracernz** [comment]
Yeah, that's what I had in mind when discussing a deadtime in the other issue. :+1:
