### ISSUE TITLE
GCS: unit tests

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#345]
Should be updated to run:
1. There should be one command line to run all
2. all_ut_run should run them
3. Existing one(s) should be changed to pass.

**Comment by mlyle** [comment]
They also should probably not be compiled into release builds.

**Comment by tracernz** [comment]
1 and 3 are covered AFAIK, 2 could be done trivially (add `<gcs exe> -t all` to all_ut_run recipe).

**Comment by tracernz** [comment]
Done I believe?

**Comment by mlyle** [comment]
Yes thx
