### ISSUE TITLE
"Upstream" tracking: need a magical merge commit

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#350]
After #348 and #349's fates are known, we should do a merge from TL `-s ours` to "ignore" everything that has drifted since in future rebases.

Those commits, right now, are:

```
pick 92ebf05 GCS/OSX: updates from comments
     Not really applicable
pick 893ef25 Ground-Updated license template
     Different project / separate changes
pick cdfe9cc Fix project credits file
     Ditto
pick de0413c Fix project credits file
    Ditto
pick 0a505b4 More granular alarm messages (subtypes).
    We have this independently / factored cleaner
pick 30f4286 FlyingF4: Use new ADC
    N/A removed target
pick e56e200 GCS: USBInfo remove unused fields
    We have a different solution
pick b32e4a1 VehicleConfigHelper: add default value
    We already have this
pick d382b81 UAVObjects Plugin: Update copyright
    N/A
pick b6db52e Main: Update copyrights
    N/A
pick ce31fc0 SysAlarms: Update copyright
    N/A
```

**Comment by mlyle** [comment]
@dustin What you think here could be particularly valuable.

**Comment by dustin** [comment]
I'd just try it and see what showed up.  It could be awful, or do very
little. The diff would tell.

**Comment by mlyle** [comment]
The goal would be zero-diff but to get the commits into the rev history so future rebases or merges would ignore them.

**Comment by dustin** [comment]
Does "-s ours" keep the tree, or just resolve merge conflicts that way?  I
don't know that I've actually tried this.

**Comment by mlyle** [comment]
I'm pretty sure it'll do the right thing.  The main problem (but also benefit) is we'll have things in our git log that were never actually done here / ignored.

**Comment by dustin** [comment]
Well, they'll just have been undone.
