### ISSUE TITLE
Win 10 GCS Next crashes on startup

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#352]
Running windows 10 on an older Alienware laptop.  Built a current "next", but am experiencing crashes on startup.  After the build, I navigated to build->ground->gcs->bin and double click on drgcs.exe.  The following is my git information, and a screenshot of the message I get when it crashes.

ufo@Wes-M11x MINGW32 ~/Documents/GitHub/dRonin ((2b9582a...))
$ git describe
preview-20151218-70-g2b9582a

![gcs-crash](https://cloud.githubusercontent.com/assets/7434287/12005246/f2369b6e-ab4e-11e5-8ddf-a76f6ab008db.png)

**Comment by mlyle** [comment]
Can you try resetting your config?   The installer has a shortcut for this, or -r as a command line argument to drgcs works

**Comment by ufoDziner** [comment]
I reset the config with -r per your request.  It will then load if I select "Developer", and crashes if "Netbook configuration" is selected.

**Comment by mlyle** [comment]
OK, I see.  So it's the combination of "netbook configuration" and running from your own build tree.  I'll check it out.
