### ISSUE TITLE
Radio Wizard with FC in s.bus mode may detect PPM channels erroneously

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#360]
Hit this on brain tonight while diagnosing for a friend, was able to replicate locally.

Steps:
- install tech preview 2 (https://github.com/d-ronin/dRonin/releases/tag/preview-20151218) on brainfpv
- erase board
- run nvw, set s.bus, restart FC, continue nvw.
- run radio wizard, observe odd channel detection (in my case it was throttle)
- observe rc inputs tab odd channel set to PPM ChXX instead of s.bus

Expected:
- PPM frames are ignored during radio wizard when fc is in s.bus mode

thoughts? I have no idea where the PPM would be coming from. The radio is s.bus only (x4r-sb), perhaps some of the s.bus protocol is being misinterpreted as ppm?

**Comment by mlyle** [comment]
PPM was configured on another port, so presumably this reacted to noise.  Marking duplicate #68 (input wizard too eager to assign a port).
