### ISSUE TITLE
Autotune: would be really nice to gather more data

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#363]
@dustin @tracernz @droidicus 

When we're studying Autotune for developer improvement, more data would be really useful.

At minimum,

1. All the contents of the systemident object.  Raw per-axis betas (yaw is missing now), number of spilled points.
2. Actuator curve setting

**Comment by mluessi** [comment]
I like this idea. In addition, it would be good the IMU frequency used. The best way to implement this would probably be to have the board plugins publish the IMU frequency.
