### ISSUE TITLE
pios_servo should be refactored common between F1/F3/F4

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#368]
@droidicus, you'd started on this-- ideally pios_servo would move to Common/ with a few ifdefs about what prescaler arrangements we use.  Are you willing to pick this up for the release after Renatus?

**Comment by tracernz** [comment]
I should probably do this and #219 in #442.

**Comment by droidicus** [comment]
I am fine with @tracernz doing this since he is already in these files.
