### ISSUE TITLE
CC3D memory alarm when autotune is enabled

### ISSUE THREAD

**Issue by muchzill4** [d-ronin/dRonin#369]
Enabling autotune module seems to consume significant amount of memory on cc3d - the memory alert is red.

I've managed to work around that problem by disabling flexi port telemetry, which is enabled by default.

**Comment by mlyle** [comment]
Yup, things are really tight on F1.  We need to make this better-- both documentation and free up a few more bytes.

**Comment by gregorydulin** [comment]
I just did AutoTune on a CC3D Atom using the current preview build.  With the serial ports off and no other modules loaded, memory is green.  AutoTune gave me reasonable PID settings, and with Damping up and Noise Sensitivity down I get silky smooth flying with just a bit of jitter here and there.  Personally I blame it on my insistence on buying the cheapest hardware and not using a dedicated BEC.

Thanks!

**Comment by nightflasher** [comment]
a few weeks ago i was looking for some new FC to replace all of my CC3D and found dRonin and loved it, but now i'm getting "low memory" error but haven't let autotune do it's job done. i've recently seen bad behavoirs with my attached DSMX satellite receiver which could go beside the memory error: the receiver stops working, CC3D goes into failsafe-mode (not configured => motor stop!) and the receiver is no longer bound.

is there anything i can do to free up some memory? i have no other module aktivated than the DSM on flexi port
