### ISSUE TITLE
Enabling TxPID module causes boot loop

### ISSUE THREAD

**Issue by muchzill4** [d-ronin/dRonin#370]
After successful autotune session (and disabling the module) I wanted to tune yaw using TxPID module, but I was unable to do so, because after enabling TxPID module GCS was not recognising the board anymore. I had to rescue it using LibrePilot GCS to make it boot again.

dRonin GCS was reporting 3 unsuccessful boots alert.

**Comment by mlyle** [comment]
Thanks for the report-- I'll try out txpid on F1.

```>$ updatePIDs                          464      328        8```

I'm suspicious it may be blowing the event stack on F1 (which is 512 bytes).

**Comment by droidicus** [comment]
Reproduced on Sparky2 as well
