### ISSUE TITLE
Camera stabilisation icon misaligned

### ISSUE THREAD

**Issue by muchzill4** [d-ronin/dRonin#371]
One of the options on the left hand side in GCS seems to have a too long title, which misaligns the icon and enables horizontal scrolling.

![image](https://cloud.githubusercontent.com/assets/454838/12071229/6e9bf886-b098-11e5-9dc3-dfac879949b5.png)

Edit: Sorry, I probably should've provided setup details - this is on osx.

**Comment by droidicus** [comment]
On WIndows 10, not seeing a misaligned icon.
