### ISSUE TITLE
Need to ship MSVC runtime...

### ISSUE THREAD

**Issue by droidicus** [d-ronin/dRonin#373]
User reported that he has an error message show up every time he boots the GCS, but can continue beyond that, and the GCS still works:
> Does it matter that I get an error everytime I launch Dronin or Tau that says: "The program can't start because MSVCR120.dll is missing if I hit "OK" it launches and runs fine

![2016-01-01](https://cloud.githubusercontent.com/assets/6981482/12073231/bf3395b2-b0e1-11e5-860f-1d4f5ed58c8e.png)

Same problem exists on Tau as well.

**Comment by tracernz** [comment]
MSVCR(untime)120.dll
Needs the runtime libs, e.g. https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by mlyle** [comment]
Yup.  Which we should probably install.

**Comment by droidicus** [comment]
The thing that is confusing to me is that it still runs even though the error is shown.

**Comment by tracernz** [comment]
Probably one of the plugins will be broken.

**Comment by droidicus** [comment]
BTW, I was able to test this on my friend's computer this weekend, and installing the MSVC runtime fixed the issue.

**Comment by mlyle** [comment]
This one probably will end up as errata this time around.. almost everyone should have the runtime already

**Comment by mlyle** [comment]
Errata in relnotes for Tanto.
