### ISSUE TITLE
GCS Buttons Apply and Save confuse new users

### ISSUE THREAD

**Issue by thunderdan** [d-ronin/dRonin#405]
GCS Buttons Apply and Save confuse new users.  It was suggested to remove the "apply" button.  Here is the chat session on the topic.

<dmorgan_> cool.  i'll just follow your advice and use save.
<icee> apply makes the flight controller start using the settings
<icee> save does that, -and- makes the flight controller save it to nonvolatile memory
<icee> you almost always want save
<droidicus> icee, from a user perspective, is there a good argument for "apply" to exist at all?
<icee> it probably should go away
<icee> it's nice to do something "dangerous" and be able to undo it by rebooting
<icee> but that's an edge case
<droidicus> or maybe a dev-profile only option?
<icee> nah, that's harmful in other ways
<OhmEye> yeah, apply should go away then imho
<OhmEye> If I really want to undo something I can use export/import

**Comment by jhitesma** [comment]
That has caught me more than once when I hit apply but forgot to hit save.  Same thing in the uavobject browser where the buttons are even less intuitive.  That REALLY confused me for the first few months of using Tau and scared me away from using the browser for a long time.
