### ISSUE TITLE
Multirotor motors should spin when armed by default

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#406]
We suggest people do this.  We should make not doing so a conscious decision.

**Comment by mlyle** [comment]
Maybe we should ask about it in the multirotor wizard.

**Comment by jhitesma** [comment]
I constantly forget to set this and then wonder why mine won't arm....and am occasionally unpleasently surprised when I then bump the throttle and realize they ARE armed.  

So I'm ALL for this.  Or at least adding it to the wizard.

**Comment by tracernz** [comment]
+1

**Comment by DTFUHF** [comment]
I'm all for this change. While messing around in this area it would be nice
to make the armed output value user-settable too. So if I want it at 1050
or 1100 it's up to me - or, a custom setting for brushed motors.

**Comment by tracernz** [comment]
It is, it's the neutral value. You want to set it independently to neutral value (which should be the minimum value that causes the motors to spin)?

**Comment by DTFUHF** [comment]
Had no idea it was the neutral value. I thought that was for 3D mode and or
reversible escs like a car.

So this change is about taking the checkbox on that output page and making
it enabled by default, nothing else?

**Comment by mlyle** [comment]
I think it should be disabled by default, and the multirotor wizard should prompt the user (with it defaulting to true in there).

**Comment by pug398** [comment]
I would prefer that myself since I never set them to spin when armed and never use the setup wizard :)

**Comment by tracernz** [comment]
This will likely be bad in always armed configurations. We need to be careful with what happens if different combinations of UAVOs are changed between releases.

**Comment by dustin** [comment]
Do people do always armed multirotors?

**Comment by tracernz** [comment]
> Do people do always armed multirotors?

Unlikely, but the UAVO default applies to all vehicle types.
