### ISSUE TITLE
Sparky Settings not shown in GCS

### ISSUE THREAD

**Issue by Ga1j1n** [d-ronin/dRonin#408]
The Sparky target flashed with preview 2 shows telemetry and movement in the flight data tab but no configuration is available in the configuration tab, it it briefly flashes up on plugin / removal but other nothing.

Tested on 2 separate windows 10 machines with the same results, works A-okay with Taulabs FW and GCS

**Comment by pug398** [comment]
Did you erase settings and reboot the board?

**Comment by Ga1j1n** [comment]
Sure Did, No joy

**Comment by pug398** [comment]
There is an open pull request #403 that has a current test build in it. It has its own issues but you may be able to see if your particular problem is still present.

**Comment by Ga1j1n** [comment]
Yep, that fixed it, glad the bug is squashed, thanks

**Comment by mlyle** [comment]
That's weird-- I used sparky with TPR2.  But glad you don't see it on a current build.
