### ISSUE TITLE
UAVOs should be self-documenting

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#41]
There's a lot of need to use the UAVO browser but it's not clear what fields mean without looking at the code.  It would be nice to have documentation strings in the XML that python & the GCS can use. (for tooltips etc).

**Comment by tracernz** [comment]
Like so?
```XML
        <field name="TimerUpdateFreq" units="Hz" type="uint16" elements="6" defaultvalue="50">
            <description>How often your spinny things get a fresh command.</description>
        </field>
```

**Comment by tracernz** [comment]
Okay I have this 90% done (the quote here was just to test that it is escaped properly).
![screenshot from 2015-11-26 23 49 42](https://cloud.githubusercontent.com/assets/9995998/11421262/882915ac-9498-11e5-8cbc-3c3474554779.png)

**Comment by tracernz** [comment]
The branch is at https://github.com/tracernz/dronin/tree/uavo-howtomakefly if anybody wants to check it out.
