### ISSUE TITLE
Tab isn't mapped properly in expo rate on stabilization settings

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#419]
Tab doesn't do anything when adjusting expos.  Expect to proceed to next field.

**Comment by mlyle** [comment]
https://youtu.be/y7kF-9fpi14   Am I looking at the wrong place?

**Comment by dustin** [comment]
Weird.  I couldn't get it to tan through expo.

**Comment by mlyle** [comment]
Can't repro.
