### ISSUE TITLE
Setup 'new contributor' labels based issue guidance

### ISSUE THREAD

**Issue by fujin** [d-ronin/dronin#42]
See
![image](https://cloud.githubusercontent.com/assets/6873/11408068/b9d359d2-941b-11e5-8b10-05676b2848d2.png)
 for an example from the InfluxDB project.

It would be great to have category and difficulty labels to provide a way for new contributors to find work they can pick up and do without worrying too much about a far-reaching, multi-target(?) change.

**Comment by dustin** [comment]
I like this idea.  Finding low hanging fruit is good for both newbies and boredom.

**Comment by fujin** [comment]
I started adding a bunch of labels.

**Comment by tracernz** [comment]
@dustin difficulty/fix-cleanflight can be the hardest one ;-P

**Comment by dustin** [comment]
Ha.  I try not to dislike stuff.  The organization is nice here, though.

**Comment by fujin** [comment]
Closing this now :) we have a good bunch of labels and I see others are adding new ones.
