### ISSUE TITLE
Throttle Curve on fresh install goes from 0 -> 1

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#420]
I grabbed a fresh Brain, flashed dRonin/next, cleared settings and went through wizard and my throttle curve goes to 1.

Note that I did hit a snag in the wizard -- the outputs weren't working (couldn't find motor idle).  I did that manually and then reran the wizard.

**Comment by dustin** [comment]
Doh, didn't realize I got #420 -- should've titled it, "The top of the throttle curve is too damn high."

**Comment by mlyle** [comment]
Will try to look at this.  I noticed the same earlier.
