### ISSUE TITLE
GCS: Safety: Vehicle setup wizard + test outputs

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#452]
Report from @dustin that he ran vehicle setup wizard while the test outputs box was left checked, and the motors spun up at the completion of the vehicle setup wizard.

Relates to #436, but we'd be looking for a more minimal fix here, I think.

**Comment by dustin** [comment]
I'm not entirely sure how I ended up in that situation, but that's plausible.

I did manually run the motor testing before wizard, and found idle points and stuff.

I did run the wizard after that.  Once it got to the prompt for the radio wizard, the motors were all spinning.

I looked around in the system viewer and saw that it actually did have them all set to idle.  I then saw the test outputs box checked.  It's possible I checked the box before starting the wizard.  I do not have access to this hardware anymore, though.
