### ISSUE TITLE
AQ32 serial ports don't have MSP option

### ISSUE THREAD

**Issue by legospacy** [d-ronin/dRonin#455]
I'm not familiar with this codebase, but I tried basically copying what #34 did, except for aq32 and just for Uart3, and it appears to work (not flight-tested though). Since the ports vary in what items they have, I'm not sure which ports it should be available on.

**Comment by tracernz** [comment]
Yep, following #34 should be fine. MSP doesn't requiring inversion or anything special so any serial port is capable. A PR would be more than welcome when you're ready. :+1: We can review, test, and offer feedback on the PR. :smile:

**Comment by legospacy** [comment]
Awesome! I'll get on that.

**Comment by mlyle** [comment]
Fixed by #456--- thanks again!
