### ISSUE TITLE
X4R-SB latest OEM firmware is doing something funky with HPWM RSSI

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#459]
@tracernz @mluessi have been in discussions. I am able to reproduce on brand new x4r-sb on Shrike. (always shows zero)

**Comment by mlyle** [comment]
Sticking in Renatus --- just for near term visibility

**Comment by fujin** [comment]
thanks, @mlyle

**Comment by pug398** [comment]
@fujin On X4R you are taking rssi off the pad right below antenna?

**Comment by fujin** [comment]
@pug398 sure are

**Comment by pug398** [comment]
I am getting nothing but a high level signal off that pad at the moment no pwm. I will try another X4R to see if I get same. It may be because I am also routing rssi through sbus. I wanted to put a lpf on the pwm rssi out to see if it looked suitable for ADC input.

**Comment by pug398** [comment]
The older X4RSB is outputting pwm rssi off the pad with same setting so I am 50/50 whether it is a change in newer OEM firmware. Need to check if newer one has been flashed with CPPM bind option.

**Comment by mlyle** [comment]
Brain has moved to using ADC for this; punting.
