### ISSUE TITLE
F3 inverters for FrSky protocol reported to be broken

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dronin#46]
by PIOS_HAL

**Comment by jihlein** [comment]
I have a fix for this, it adds another argument to the setup parameters, if that's okay.  Flight tested on Naze32Pro.  Can create clean pull requests if this method is acceptable.

Date: Wed, 25 Nov 2015 13:13:50 -0800

**Comment by mlyle** [comment]
I can live with it for interim and would really appreciate it!

**Comment by tgreer** [comment]
Can this issue be closed now #57 has been merged?

**Comment by tgreer** [comment]
Closing. Whoop Whoop!
