### ISSUE TITLE
Add opt-in for usage statistic and sharing of private data

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#470]
The GCS currently silently publishes usage statistics, including private information like the IP address and flight controller serial number. IMO, this is not acceptable and we should require users to opt-in. The easiest solution would be to add a pop-up dialog asking users for permission with check boxes defaulting to true.

**Comment by dustin** [comment]
Mangling serial numbers is useful.  It's not possible to not share IP addresses, though.

**Comment by mluessi** [comment]
Yeah, if you submit something to a server, you are sharing the IP anyways. The important thing is to ask user for permission.

**Comment by mluessi** [comment]
I just noticed that the settings are also not saved, i.e., restarting the GCS enables sharing again if it was disabled.
