### ISSUE TITLE
Request for comment: change code pattern

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#471]
Very frequently with UAVOs, we do something like:

StabilizationDesiredGet(&stabDesired);
stabDesired.Throttle=...
stabDesired.Whatever=...
StabilizationDesiredSet(&stabDesired);

I think if we intend to set all fields, we should default or bracket initialize things instead of the initial get.  This way we're not tainted by past states, we don't contend the giant uavo lock, and we don't copy data as much.

Thoughts?

**Comment by droidicus** [comment]
One issue I could see here is if new variables get added to the UAVO, then that code block would no longer be setting all fields, and some data could be lost. Could be nasty to track down too.

**Comment by mlyle** [comment]
UAVOs are supposed to have one producer and one consumer at all times, and flight code isn't supposed to set settings objects in general (the big exception being the systemident object).

This would be for things like stabilizationdesired, etc.  Far better things go to defaults than something some other module that was driving the UAVO before set.

**Comment by tracernz** [comment]
We could turn on GCC warnings to tell us about uninitialized fields.

**Comment by mluessi** [comment]
Another option could be to have the UAVO generator create set functions that just set all fields of the UAVO struct. The functions would be inlined (so be efficient) and force the programmer to set all fields.

**Comment by droidicus** [comment]
@mluessi I was thinking about something like that as well, +1 from me

**Comment by mluessi** [comment]
@mlyle WDYT? Lets figure this out and then go through the code and fix the offending places.

**Comment by mlyle** [comment]
Yup, I think we should do it and your suggestion is a good one-- if we put it in the header so it was inlined, the redundant setters (the things we set ourselves jsut after) would be omitted too.

**Comment by mlyle** [comment]
#139 should merge; then we can factor some of the initialization impl out as a next step towards this.
