### ISSUE TITLE
Fix VirtualBar documentation

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#482]
This is a mostly-heli feature, but the docs imply it has benefits for multirotors.  We should be clear about what this is and where you should use it.

**Comment by raemin** [comment]
Just updated the wiki with the appropriate caveats.  

This mode has its own PIDs and default values are way to agressive. The way I see it: duplicating the standard PIDs to vBar PID and delaying gyro deactivation makes this flightmode "kind of safe" to use. This is what I've written in the wiki with some basic instructions.

Documentation issue can be considered as solved. 
This being said, is there any point in duplicating PIDs for vBar?

**Comment by mlyle** [comment]
I skimmed docs and made a couple minor edits.  Looks good.  I don't love the separate PIDs but I see why someone would want different values.  Closing.
