### ISSUE TITLE
Push "Manual" flight mode into stabilization modes

### ISSUE THREAD

**Issue by ekaszubski** [d-ronin/dRonin#495]
Manual flight mode is dangerous for most VTOL aircraft. In the cases where manual control is desirable (flybar helicopters, some fixed-wing aircraft, and many ground vehicles), it's often only desirable on a single stabilization axis (e.g. yaw on flybar helicopters equipped with a gyro).

Thus, we should:
- Remove manual flight mode completely?
- Add per-axis manual stabilization mode to allow for better customization of stabilization
- Update alarms/warnings currently looking for manual flight mode to instead look for manual stabilization mode in stabilization1/2/3 flight modes

**Comment by tgreer** [comment]
I think this is a good idea. Manual is a terrible terrible thing, unless you REALLY know what you're doing.

**Comment by mlyle** [comment]
I don't think it should be removed entirely.  There's existing fixed-wing setups that this breaks.  We already prohibit it entirely on multirotor.

**Comment by ekaszubski** [comment]
@mlyle I went through all the references to manual flight mode; selecting any stabilized1/2/3 flight mode and setting all the stabilization axes to "manual" should result in identical functionality as selecting manual flight mode.

**Comment by mlyle** [comment]
Sure.  But it breaks existing configurations.  By the same logic we could remove most of the flight modes because you can get equivalent behavior by using the stabilization banks.  But that confuses manypeople and in any event breaks people who have existing configuration.

**Comment by ekaszubski** [comment]
IMO having a redundant flight mode that can also be specified per-axis via stabilization modes is more confusing (similar confusion led to a crash for me and I've been using the GCS for a while). If we keep the redundant flight modes, I think any unused stabilization banks should be hidden or grayed-out in the GCS.

As for breaking existing configurations, a minority of users will be affected. How do we decide when it's OK to break existing configurations, or are you saying we need to provide indefinite legacy support for existing configurations?

**Comment by pug398** [comment]
I would ask is there a supported vehicle type that uses "manual" as a primary flight mode or does just about everyone (for that vehicle type) have to go in to stabilize and set custom modes per axis?

**Comment by tracernz** [comment]
The only vehicle type that doesn't use manual is multirotor so it might be wise to keep it around.

**Comment by DTFUHF** [comment]
I'd say manual mode is required for airplanes, I'd never want to fly an
airplane with an autopilot that didn't have a manual mode I could switch to.

**Comment by ekaszubski** [comment]
To clarify, I'm not suggesting we remove full-manual functionality, I'm just saying we should push that functionality into stabilized1/2/3 banks (so make it a stabilization mode instead of a flight mode) so that it can be enabled on individual (or all) stabilization axes. Then you can just set stabilized3 to manual/manual/manual for roll/pitch/yaw and you get the same functionality as selecting manual flight mode.

However, @mlyle makes a good point that we should try to avoid breaking ~~things~~ existing configurations for people unless there's some significant benefit, so I don't see any significant issue in keeping the manual flight mode around at the cost of slightly more complex code (to handle both manual flight mode and manual stabilization mode per-axis).

For completeness, these are the cases I can see for manual/mixed/stabilized modes:
- vehicles that should not use _any_ manual stabilization except for bench testing:
  - multirotors
  - flybarless helicopters
- vehicles that should use _some_ manual stabilization (we currently do not support these configurations):
  - some fixed-wing (any axis _may_ or _may not_ be stabilized via an IMU)
  - most flybar helicopters (manual roll and pitch; yaw _may_ or _may not_ be stabilized via gyro)
  - some ground vehicles (any axis _may_ or _may not_ be stabilized via a variety of methods including encoders, IMU, cameras, etc; differential-drive vehicle: rotate at 30 degrees per second; drive forward at 0.5 meters per second; not sure if we support either of these for ground anyway)
- vehicles that should use _full_ manual stabilization:
  - some fixed-wing
  - few flybar helicopters (throttle+collective->yaw mixing used instead)
  - most ground vehicles

**Comment by mlyle** [comment]
> so I don't see any significant issue in keeping the manual flight mode around at the cost of slightly more complex code (to handle both manual flight mode and manual stabilization mode per-axis).

IMO it should just be like the other ones-- using 'manual' pushes each of the 3 axes into manual modes.

**Comment by ekaszubski** [comment]
> IMO it should just be like the other ones-- using 'manual' pushes each of the 3 axes into manual modes.

Agreed, and this is how I implemented it. Ready for review: #496
