### ISSUE TITLE
Jenkins: complete configuration

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#5]
- ~~PR builder integrated to say "OK to commit"~~
- ~~Run unit tests -- make all_ut_run~~
- Production of artifacts
- IRC notification, better text?
- ~~Windows build~~

**Comment by tracernz** [comment]
Make targets to build release packages which actually work on each platform should be a priority. See TauLabs/TauLabs#1935

**Comment by mlyle** [comment]
depends on #50

**Comment by mlyle** [comment]
#50 is done; sufficient for Renatus release.
