### ISSUE TITLE
Automate production of release artifacts

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#50]
We should get much closer to "push button to ship". Relates to #5

**Comment by fujin** [comment]
While we have the hood up, the Brain fw build needs to be added to the common package per https://github.com/d-ronin/dronin/pull/36#issuecomment-159976618

**Comment by mlyle** [comment]
Release artifacts:

* INTERMEDIATE PRODUCT: firmware zip
* Windows NSIS .exe installer
* Windows .zip file
* Mac OS X .dmg
* ~~Mac OS X zip~~ I see no reason to ship this variant
* Linux .deb package
* Linux .tar.xz
* AndroidGCS [not heavily supported in first release]
