### ISSUE TITLE
Lux: Check UART IRQ configs

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#502]
Appear to be mixed up: https://github.com/d-ronin/dRonin/blob/next/flight/targets/lux/board-info/board_hw_defs.c#L308

**Comment by mlyle** [comment]
@readerror67 how is this supposed to be?  I did not use receiver port for serial..  Which is it?  UART 1 or 2?

**Comment by mlyle** [comment]
Fixed by #526
