### ISSUE TITLE
Make .uav exports diff friendly

### ISSUE THREAD

**Issue by dustin** [d-ronin/dronin#51]
Minor changes often lead to very large diffs.  Need some kind of canonicalization pass.

**Comment by mlyle** [comment]
I remember Kenn did some stuff in this area, to sort elements and attributes.

**Comment by tracernz** [comment]
How about JSON?

**Comment by dustin** [comment]
The format isn't all that important.  I just want small changes to make
small, easy to read diffs.

This does mean in any case some pretty printing and ordering is involved.

**Comment by dustin** [comment]
It seems a fix has gone in.  Maybe this is no longer an issue.  I would occasionally get good diffs and occasionally rewrites.  I'll reopen this if it goes bad again.

**Comment by mlyle** [comment]
https://github.com/TauLabs/TauLabs/pull/1924 
https://github.com/TauLabs/TauLabs/pull/1833 

were the changes that improved this.
