### ISSUE TITLE
Verify experimental outer I calculation

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#512]
I was moving the experimental section from javascript to go (so it just shows up in the API instead of being a UI feature) and noticed the oki looked wrong:

```
oki:  ki = (1/(2*Math.PI*tau*10.0) * .75) * okp
```

That clearly shouldn't be `ki =`, but that's what's been there.  I assume it's either `ki *` or just shouldn't be there, but don't want to make stuff up and change behavior.

**Comment by mlyle** [comment]
It's supposed to be (1/(2_Math.PI_tau*10.0) \* .75) \* okp -- I assume the assignment there is vestigial.

**Comment by dustin** [comment]
OK, thanks.  That's what it is, then.  Done on the backend instead of the
frontend.
