### ISSUE TITLE
gcs: curve2 source always shows "Throttle"

### ISSUE THREAD

**Issue by ekaszubski** [d-ronin/dRonin#513]
Regardless of actual curve2 source, the graph widget in gcs always says that the source of curve2 is "Throttle"

**Comment by tracernz** [comment]
Where are you looking?

**Comment by ekaszubski** [comment]
Configuration -> Vehicle -> Mixer Settings [Helicopter] -> Curve settings -> below curve2 graph

Note that MixerSettings.Curve2Source in the property manager says "Collective" while the label on the graph says "Throttle"

![screenshot from 2016-03-21 10-27-48](https://cloud.githubusercontent.com/assets/666500/13927626/a51ace78-ef4f-11e5-975e-ebe9f0e46e6e.png)

**Comment by tracernz** [comment]
Thanks, will take a look later.

**Comment by ekaszubski** [comment]
To clarify, the GCS in the above screenshot was built from March 17 next (6bee0b131ee6870e1cfcdbda8cd7dcc9b311317a)

**Comment by mlyle** [comment]
Won't be further improving this before samsara; deferring.

**Comment by mlyle** [comment]
It looks like this is half implemented.  mixercurve.cpp has plumbing for 'CBCurve2Source'; configccpmwidget.cpp does `m_ccpm->PitchCurve->setMixerType(MixerCurve::MIXERCURVE_OTHER);`  (there's a flag it doesn't set to enable that widget.

But the value doesn't seem to get stored/restored from uavos, etc.
