### ISSUE TITLE
GCS input wizard should clarify arming switch sense

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#519]
In the "Radio WIzard" "invert axis/switch" input screen, one has the option to invert the arm switch.  Unfortunately there is no way to see which setting results in "armed"...  Would be nice to know if you need to invert it or not by showing the status.

**Comment by mlyle** [comment]
Sorry, not getting to this.

**Comment by tracernz** [comment]
I had a hack at it the other day, just adding some text above the switch in the SVG, but need to actually hook some hardware up to test.
