### ISSUE TITLE
Remove unsupported targets

### ISSUE THREAD

**Issue by tgreer** [d-ronin/dRonin#52]
Remove targets such as sparkybgc

**Comment by tgreer** [comment]
#53 opened to commence this.

**Comment by dustin** [comment]
Any other targets... targeted?

**Comment by mlyle** [comment]
There's some small remnants of the ESC

**Comment by mlyle** [comment]
#97

**Comment by tgreer** [comment]
Closing as all targets we want to remove have been removed for now.
