### ISSUE TITLE
CDC/VCP driver does not work on Windows 10

### ISSUE THREAD

**Issue by droidicus** [d-ronin/dRonin#532]
It looks like in Windows 10, Microsoft has changed the way that USB modem interfaces work, and the current inf based driver install will no longer work:

https://msdn.microsoft.com/en-us/library/windows/hardware/dn707976(v=vs.85).aspx

I can verify on Windows 10 that a Sparky2 is showing up as a valid COM port in the device manager, but I cannot get VCP telemetry working on my setup. My guess is that something will need to change in the GCS, but I have not been able to find what up to this point.

**Comment by tracernz** [comment]
Can also confirm the same issue on Windows 10 using the Microsoft auto-installed driver.

**Comment by tracernz** [comment]
Windows 10 driver in Windows/Inf/Usbser.inf for reference: https://gist.github.com/tracernz/26a5c4343cec83462fed

**Comment by tracernz** [comment]
If I open the port in Putty it's spitting out data so looks like this is an issue with GCS or QSerialPort.

**Comment by tracernz** [comment]
Ahhh, it works on my compiled-from-next GCS, but not with the release one...

**Comment by tracernz** [comment]
Also working on the Hotfix artifact: http://jar.lyle.org:8080/job/dronin/102/Nodes=winx86/

**Comment by mlyle** [comment]
@tracernz That sounds exceedingly odd :/

**Comment by tracernz** [comment]
I think I figured it out. Pretty sure that was the first time I ever plugged a board into that Windows install, and then IIRC I rebooted to install Windows updates after testing the release but before testing next and the hotfix. @droidicus Try rebooting?

**Comment by droidicus** [comment]
@tracernz no joy, still doesn't work here :-/

**Comment by ragd011** [comment]
The only issue I've had was having to drop into a boot option that disables the requirement for driver signing while I install the GCS.  Then I reboot win 10 normally and everything is detected fine.

http://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/

is this what people are experiencing or am I not understanding the problem correctly?

**Comment by tracernz** [comment]
You don't need to install drivers on Windows 10, they are included by default.

**Comment by droidicus** [comment]
I was able to get VCP working this weekend for the Debug console on Win 10 using the default system driver (no driver installation). Will try the VCP telemetry again tomorrow.

**Comment by mlyle** [comment]
@droidicus any idea what you did differently vs. when it didn't work before?

**Comment by droidicus** [comment]
@mlyle I didn't do anything differently, just set the VCP port to the debug console, and fired up putty. It worked the first shot.

**Comment by tracernz** [comment]
So it looks like a telemetry/configuration issue rather than a CDC driver issue?

**Comment by droidicus** [comment]
Yes, I think so.

**Comment by mlyle** [comment]
I had marked this documentation, but in re-reading the issue I don't see an actionable doc issue.
