### ISSUE TITLE
Re-enable setup wizard firmware update capability

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#539]
This relied on the firmware images being compiled into GCS through a .qrc resource file. We have removed this but not replaced it with any alternative. We should teach GCS to find firmware images at the correct installer location depending on platform.

**Comment by tgreer** [comment]
Yes. So many issues with new comers where they need to update the firmware first but it's not clear.

**Comment by mlyle** [comment]
Dup #283
