### ISSUE TITLE
Some UI elements are squished with the netbook stylesheet

### ISSUE THREAD

**Issue by mngrif** [d-ronin/dRonin#547]
Some UI elements are squished with the netbook stylesheet. Screenshot is attached. Screen resolution is 1024x600 which is awfully tiny.

Thank you
![snapshot1](https://cloud.githubusercontent.com/assets/1446008/12627817/e7f26146-c50d-11e5-8920-1ec7acaa620f.png)
.

**Comment by mlyle** [comment]
Thanks for the report!

That one indeed looks bad.  Any other really bad examples?  This one we should be able to just put a scrollbar on the panel.

**Comment by mngrif** [comment]
After a thorough review of everything I can find to review, I found two more display issues.

Thank you!

![snapshot2](https://cloud.githubusercontent.com/assets/1446008/12631980/aa2a930a-c522-11e5-9d8c-fb8239430823.png)
![snapshot3](https://cloud.githubusercontent.com/assets/1446008/12632014/f656f26e-c522-11e5-86ab-f24c6e5d67fc.png)

**Comment by tracernz** [comment]
Should be a case of setting minimum sizes and checking for appropriate size policies on these widgets.

**Comment by mlyle** [comment]
@tracernz on the last one, can you repro-- seems like it'd be a linux stylesheet thing.

**Comment by tracernz** [comment]
I've seen blacked out things in the vehicle widget like that before but it's never repeatable from what I can tell.
