### ISSUE TITLE
Remove MWRate mode

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#56]
It's a bastard stepchild.  If it has any desirable properties, they should be taught to existing modes.

**Comment by tracernz** [comment]
It also uses it's own separate UI elements in GCS which is undesirable.

**Comment by mlyle** [comment]
And uses memory.

I'd say we should deprecate for this release-- put a warning in GCS that it will be removed and to use acroplus instead, to minimize breakage for existing users transitioning.

**Comment by tgreer** [comment]
In agreement with what @mlyle said here.
