### ISSUE TITLE
GCS: Unable to import Systemident values BUG

### ISSUE THREAD

**Issue by henn1001** [d-ronin/dRonin#561]
I can export systemident values http://i.imgur.com/kauRhgI.png but i´m somehow unable to import them successfully.

Even after manually pasting them into the fields http://i.imgur.com/5jfnHqC.png and hitting send/save, reverts them back to 0.

**Comment by mlyle** [comment]
This one is easy I think, GCS permissions on the systemident object.

**Comment by mlyle** [comment]
Would you mind testing #563 please?

**Comment by henn1001** [comment]
Sure thing
