### ISSUE TITLE
RFM22B bind wizard should disable "telemetry" from board serial ports

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#568]
RevoMini defaults to 'telemetry' on mainport; this prevents rfm22b from working.

Alternatively change the revomini mainport default.

Credits to @pug398 for initial report.

**Comment by Ga1j1n** [comment]
I think I'm hitting this bug too, PPM works a-okay but no telemetry at all

**Comment by mlyle** [comment]
@Ga1j1n If you're hitting this bug, it's fixed by not trying to send telemetry to multiple places.  E.g. setting mainport to something other than 'telemetry' on the revomini.
