### ISSUE TITLE
Batterymodule cell-count autodetection [WIP]

### ISSUE THREAD

**Issue by henn1001** [d-ronin/dRonin#575]
Got some barebone code working in my local branch
https://github.com/henn1001/dRonin/commit/b02dc901fb70abdbf0ed9ac08c0fa52884c3096c
Good/bad idea?

The thresholds act now as a limit per cell.

Did some testing and it seems to work fine but need to test some more edge cases.

**Comment by mlyle** [comment]
It looks good at first cut. 

But it should be configurable / something you can turn on and off.

**Comment by henn1001** [comment]
Agree. I will probably repurpose the maxCellVoltage for that. 0=off and  > 0 = var for cell count calc
