### ISSUE TITLE
dRonin Logo

### ISSUE THREAD

**Issue by VArcht** [d-ronin/dRonin#58]
dRonin needs a logo.

**Comment by VArcht** [comment]
Concept 1:


![](https://raw.githubusercontent.com/VArcht/varcht.github.io/ol_test/images/logo_01.png)

**Comment by jihlein** [comment]
I like it!!

**Comment by mluessi** [comment]
I like the logo. However, I think it may be too complex. Ideally, the logo should look good using only 1 or 2 colors, so it can easily be printed on t-shirts, silkscreens etc. Also, it's good if the logo is compact / abstract, so it can e.g. be used in an app icon (without the d-ronin text).

**Comment by fujin** [comment]
one color is also ideal for transparency on youtube (for example, the BrainFPV green.) I do like this though :)

**Comment by mlyle** [comment]
I like the dR here.

http://www.dafont.com/digital-ninja.font?text=dRonin&psize=l

Maybe not the specific typeface, but.. the elements mirrored between the d and r, the diagonal line separating them, etc.

**Comment by mlyle** [comment]
since this was not posted here: https://github.com/VArcht/varcht.github.io/blob/ol_test/images/logo_proof_01.png

**Comment by VArcht** [comment]
Concept 2:


![](https://raw.githubusercontent.com/VArcht/varcht.github.io/ol_test/images/logo_23.png)

**Comment by mlyle** [comment]
Flagging this here since it's liked:

![](https://raw.githubusercontent.com/VArcht/varcht.github.io/ol_test/images/logo_25.png)

**Comment by fujin** [comment]
:+1: for :two: :five: logo25 from me!

**Comment by VArcht** [comment]
Final

![logo_final](https://cloud.githubusercontent.com/assets/828599/11574157/c926a332-99be-11e5-8ce3-f8a663182bf1.png)

**Comment by mlyle** [comment]
need consensus on final "ONIN" too

**Comment by tracernz** [comment]
Perhaps a brighter/less brown orange would be good, and make it look less retro.

**Comment by VArcht** [comment]
pick an orange?

**Comment by mlyle** [comment]
i like current orange.  whatever we decide needs to work with white and black backgrounds

**Comment by mlyle** [comment]
also after we pick a screen color we should pick a pantone color just for reference.

**Comment by VArcht** [comment]
first goes at adding the onin.
![logo_final_full_smfntcntr](https://cloud.githubusercontent.com/assets/828599/11576883/c9fc8b04-99ce-11e5-955c-82e056888041.png)

![logo_final_full_lgfntbott](https://cloud.githubusercontent.com/assets/828599/11576895/d8d0000c-99ce-11e5-894a-8d9cdb86bfb4.png)

**Comment by mlyle** [comment]
Maybe something inbetween?  I like the weight of the second but there isn't enough gap between the characters to look OK on board silk, etc.

Also not sure i like the orange fill / black stroke on the line / perhaps that line has too much weight.

**Comment by tgreer** [comment]
the bar above the o looks stupid.

**Comment by VArcht** [comment]
Horizontal

![logo_final_full_lgfntbott](https://cloud.githubusercontent.com/assets/828599/11591516/34fbccb6-9a4d-11e5-9ace-50d1f0696140.png)
![logo_final_full_lgfntbott_a](https://cloud.githubusercontent.com/assets/828599/11591515/34fa2ba4-9a4d-11e5-8cb9-bcad63e23f9d.png)
![logo_final_full_lgfntbott_b](https://cloud.githubusercontent.com/assets/828599/11591517/34febda4-9a4d-11e5-8271-26fbc1174b1e.png)

**Comment by VArcht** [comment]
Stacked

![logo_final_full_vert_c](https://cloud.githubusercontent.com/assets/828599/11591530/4ee618ca-9a4d-11e5-9846-ed5ff83c1b3f.png)
![logo_final_full_vert_a](https://cloud.githubusercontent.com/assets/828599/11591532/4f01c822-9a4d-11e5-9d6b-b3e953e69d87.png)
![logo_final_full_vert_b](https://cloud.githubusercontent.com/assets/828599/11591531/4efcf734-9a4d-11e5-8bd8-23232424b66b.png)

**Comment by VArcht** [comment]
oh, and hat :)

![droninhat](https://cloud.githubusercontent.com/assets/828599/11591600/e393f97e-9a4d-11e5-8425-92fb6045a6e4.jpg)

**Comment by mlyle** [comment]
I like https://cloud.githubusercontent.com/assets/828599/11591516/34fbccb6-9a4d-11e5-9ace-50d1f0696140.png

**Comment by tgreer** [comment]
I don't like the bar over the O. other than that I agree.

**Comment by VArcht** [comment]
I like H3 as well

**Comment by tgreer** [comment]
The consensus appears to be H3.

**Comment by mluessi** [comment]
I'm with @tgreer, I don't like the bar over the o. For me as a native German speaker, it looks like "dRönin". Also, I'm concerned that if the left part of the logo (dR with stuff around it) is printed in a single color with limited resolution (e.g. silkscreen) it may become one large blob and it may be difficult to make out the letters.

**Comment by VArcht** [comment]
@mluessi 

![image](https://cloud.githubusercontent.com/assets/828599/11600006/ebba2ba6-9a7e-11e5-8eab-8d5cc4f31e13.png)

**Comment by mluessi** [comment]
@VArcht ok, that looks good :)

**Comment by mlyle** [comment]
https://github.com/VArcht/varcht.github.io/blob/ol_test/images/dronin_logo_ob.svg

**Comment by mlyle** [comment]
Closing in favor of other branding issue.  Logo is done, becoming familiar, and looks great!
