### ISSUE TITLE
Next: Re-stabilize after merging tool and lib changes

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#596]
- [x] Smoke test on F1
- [x] Smoke test on F3
- [x] Smoke test on F4
- [x] Smoke test OSD
- [x] Autotune/flight test on F1
- [x] Autotune/flight test on F3
- [x] Autotune/flight test on BrainFPV
- [x] PH test on F4
- [x] S.bus
- [x] PPM
- [ ] MSP OSD
- [x] DSM Satellite
- [x] RF Telemetry
- [x] Bootloader
- [x] Battery module
- [ ] TxPID
- [x] GCS Controller
- [x] Input wizard

**Comment by droidicus** [comment]
Tested on F4/Sparky2, Autotune, SPORT, S.BUS, Battery (voltage only), Altitude-hold.

All lights green.

**Comment by mlyle** [comment]
Nice, thank you very much :)

**Comment by mlyle** [comment]
Good enough
