### ISSUE TITLE
Calibration over radio: can't save afterwards

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#597]
Tried current next with pipxtreme + sparky2, 100kbps, 100mW ; mag calibration proceeded fine over radio.  Subsequent attempts to "save" did not (could not save any object, even from other panes).  I wonder if some objects are left "turned up" in rate.  After turning attitude down from 100ms to 333ms, was able to save objects again.

On a fresh session not after 6 point cal, was able to save.  Then after 6 point cal could not.

Taulabs/taulabs#1474 and TauLabs/taulabs#1475 are possibly related.

**Comment by jpbarraca** [comment]
Also happens when configuring through a Bluetooth radio.

**Comment by mlyle** [comment]
This is still a little dodgy but works.. deferring to look at it more later, though.
