### ISSUE TITLE
Vehicle setup wizard over radio: level calibration times out

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#598]
Reported by @pug398, confirmed on Sparky2 on current next

Connects to #641

**Comment by pug398** [comment]
With pipx but xbee ok

**Comment by jpbarraca** [comment]
In a Sparky2, the Automatic level detection from the Attitude tab also times out frequently if done over a Bluetooth radio. Probably related.

**Comment by mlyle** [comment]
Current next: 100kbps and 192kbps both work on "attitude" pane.  192kbps works in vehicle setup wizard (the timeout there is dumber).
