### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#6]
About box, license file, logo.

* [x] ground/gcs/src/plugins/config/images/TX2.svg
* [x] ground/gcs/src/plugins/config/images/Transmitter.png
* [ ] ground/gcs/src/plugins/config/images/multirotor-shapes.svg
* [x] ground/gcs/src/plugins/coreplugin/images/taulabs_logo_128.png
* [x] ground/gcs/src/plugins/coreplugin/images/taulabs_logo_256.png
* [x] ground/gcs/src/plugins/coreplugin/images/taulabs_logo_32.png
* [x] ground/gcs/src/plugins/coreplugin/images/taulabs_logo_64.png
* [x] ground/gcs/src/plugins/welcome/qml/images/welcome-logo.png
* [x] ground/gcs/src/app/resources/tau_trans.png

~~Blocks~~ on getting logo(s) from fiverr.

### other existing tl logos need replacing, links pointing to 'next' branch'
![taulabs_logo_32.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/plugins/coreplugin/images/taulabs_logo_32.png)

![taulabs_logo_64.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/plugins/coreplugin/images/taulabs_logo_64.png)

![taulabs_logo_128.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/plugins/coreplugin/images/taulabs_logo_128.png)

![taulabs_logo_256.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/plugins/coreplugin/images/taulabs_logo_256.png)

![welcome-logo.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/plugins/welcome/qml/images/welcome-logo.png)

Not sure what this is, transparent? (--@fujin)
![tau_trans.png](https://raw.githubusercontent.com/d-ronin/dronin/next/ground/gcs/src/app/resources/tau_trans.png)

**Comment by tgreer** [comment]
Ref #30

**Comment by tgreer** [comment]
Logo files which are referenced throughout the code are:
taulabs_logo_128.png
taulabs_logo_256.png
taulabs_logo_32.png
taulabs_logo_64.png
welcome-logo.png
tau_trans.png

**Comment by fujin** [comment]
@tgreer thx, added to issue

**Comment by tracernz** [comment]
I will fix the splash screen up to make it look nicer too, I have a branch somewhere that does that to Tau (it seems to be anti-alised etc. already on OSX, but not Linux).

**Comment by tgreer** [comment]
#58 is a prerequisite of this

**Comment by tracernz** [comment]
* [ ] ground/gcs/src/plugins/config/images/TX2.png

**Comment by VArcht** [comment]
Replacements

![dronin_logo_32](https://cloud.githubusercontent.com/assets/828599/11600781/cf0865ae-9a83-11e5-8ec7-9ca428cd091d.png)
![dronin_logo_64](https://cloud.githubusercontent.com/assets/828599/11600780/cf058d70-9a83-11e5-88ac-bbed076f63f3.png)
![dronin_logo_128](https://cloud.githubusercontent.com/assets/828599/11600777/cf0386d8-9a83-11e5-90f1-aab694f33000.png)
![dronin_logo_256](https://cloud.githubusercontent.com/assets/828599/11600778/cf03b05e-9a83-11e5-8482-117340f25de3.png)
![welcome-logo png](https://cloud.githubusercontent.com/assets/828599/11600779/cf03a26c-9a83-11e5-9b0c-272ede94d733.png)

**Comment by VArcht** [comment]
We should do a complete image for the splash screen instead of ground/gcs/src/app/resources/tau_trans.png

**Comment by tgreer** [comment]
Agreed.

**Comment by VArcht** [comment]
more logos... https://github.com/d-ronin/dRonin/tree/next/artwork/Logo/logo.iconset

**Comment by mlyle** [comment]
I don't see why multirotor-shapes needs branding / where it has any existing branding.

If that is good, let's close this issue (and handle other branding things as we encounter them).
