### ISSUE TITLE
pipxtreme target port handling is completely broken

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#600]
Introduced by TauLabs/taulabs#1791 / support for TLM
1. Board hardware revision selected for TLM is used by OPLM.
2. Port configuration broken in various ways.
3. buffer sizes
4. WHo knows what else.

Identified in conjunction with @ukmook in #587

**Comment by ukmook** [comment]
#587 I see Pug had Sparky2 Set as coordinator i have Oplink set as coordinator. Thought i should add this info.

**Comment by mlyle** [comment]
@ukmook Yah, I think it's just the bluetooth layer itself was unreliable because of these issues.
