### ISSUE TITLE
GCS : Brain : Connection diagram missing.

### ISSUE THREAD

**Issue by SystemsGuy** [d-ronin/dRonin#605]
On GCS Release-20160120: 20160119-2831e945, when using the Vehicle Setup Wizard with a Brain, there is no connection diagram - if you click on the connection icon, you get a blank screen.
![dronin setup wizard_2016-02-02_22-18-50](https://cloud.githubusercontent.com/assets/2819484/12773041/3bcf8278-c9fd-11e5-82ea-15c45e91dd73.jpg)

![dronin gcs_2016-02-02_22-34-35](https://cloud.githubusercontent.com/assets/2819484/12773045/4298112e-c9fd-11e5-96f3-3d8804e494a5.jpg)

**Comment by tracernz** [comment]
Yeah, not many boards have them.

**Comment by mlyle** [comment]
Dup #230   (don't worry about reporting duplicates)
