### ISSUE TITLE
Change "futaba sbus" to sbus in setup wizard

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#606]
Now 3 different people on IRC have tripped over this.

**Comment by tracernz** [comment]
But it is Futaba even if some cloners reverse engineered it :/. Probably worth the misnaming for the usability win though I guess.

**Comment by mlyle** [comment]
Yup.  It's also a good question as to whether we can legitimately use their brand names and quasi-logos and not be legally exposed.

**Comment by jpbarraca** [comment]
The same applies to Graupner and Spektrum. Also, if we remove the reference to the brand, sometimes people will struggle to associate the protocol with what they have. This can probably be solved by creating a wiki page.

**Comment by henn1001** [comment]
Just for reference - Librepilot does it like that:
![unbenannt](https://cloud.githubusercontent.com/assets/10023892/12813982/d9139e4a-cb3b-11e5-97d4-37be0d053f87.PNG)

**Comment by tgreer** [comment]
@henn1001 that works quite nicely. Though we'd need a list of types<>makers... s.bus for like frsky, etc.
