### ISSUE TITLE
GCS: UAV import deselect all button

### ISSUE THREAD

**Issue by henn1001** [d-ronin/dRonin#631]
Sometimes i only want to import one set of uavs.
![unbenannt](https://cloud.githubusercontent.com/assets/10023892/12891374/ff369a60-ce87-11e5-92fa-42d7ed388665.PNG)

A select/deselect all button would be great for that :)

**Comment by jpbarraca** [comment]
Can it be closed?

**Comment by mlyle** [comment]
Yes it can.

In the future if you put `fixes #631` in your top PR description, when it gets merged, 631 will automatically get closed.
