### ISSUE TITLE
Flight: Merge Colibri and Quanton targets

### ISSUE THREAD

**Issue by EricB-Arch** [d-ronin/dRonin#635]
Talking with icee he mentioned dropping colibri as a target noting that colibri and quanton were pretty much the same and that at one point it was possible to load quanton fw on the colibri.

**Comment by tgreer** [comment]
@VArcht how different are they? Is this just a case of relabelling things, or is there some subtle differences we need to account for?

**Comment by ernieift** [comment]
The hardware is very similar. But the bootloader version differs here. So there is fewer space for firmware on the colibri. As a workaround you can flash the colibri to a quanton.

**Comment by mlyle** [comment]
We're working on auto-bootloader-update as part of the upgrade process, so this will get easier.

**Comment by mlyle** [comment]
Colibri is gone gone gone.
