### ISSUE TITLE
Need to document how to fix Windows CC3D driver attachment

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#646]
Triple-verified correct procedure was tried.  Used an eraseflash firmware and then flashed back, to no success.  Windows 10 x64.

This is a placeholder for any similar results.

![screenshot](https://cloud.githubusercontent.com/assets/90903/12955797/8e43ab1a-cfd9-11e5-9f14-400df4c468c8.PNG)

**Comment by jpbarraca** [comment]
I have a CC3D and can test the process. The CC3D will be usable (can I flash it again) after this?

**Comment by mlyle** [comment]
@jpbarraca yes.  On the other hand this is something that only happened once so you're not likely to repro it.

I talked to the user yesterday; he solved the issue with this procedure:

https://librepilot.atlassian.net/wiki/display/LPDOC/Troubleshooting

**Comment by jpbarraca** [comment]
@mlyle I tried but I cannot reproduce this issue on OS X.

Maybe it is a good idea to add that info to our wiki.

**Comment by mlyle** [comment]
@jpbarraca Yes-- it's only on Windows, and only happened to about 1 windows user out of 100.

**Comment by matheusrgomes** [comment]
Reinstall driver - all good.
https://librepilot.atlassian.net/wiki/display/LPDOC/Troubleshooting

**Comment by mlyle** [comment]
Documented: https://github.com/d-ronin/dRonin/wiki/Windows-driver-troubleshooting

In errata.
