### ISSUE TITLE
GCS crash when opening additional workspace

### ISSUE THREAD

**Issue by carbogit** [d-ronin/dRonin#648]
adding an additional workspace through Tools/Options/GCS/Workspaces and then going to that new workspace via its tab at the bottom of the screen crashes the GCS (Win 7 64 bit, Renatus release).

**Comment by tracernz** [comment]
Confirmed on Linux. Tries to de-reference a null pointer at https://github.com/d-ronin/dRonin/blob/f801a2c5342ed4cfbc138480b5e5afbcedfb970e/ground/gcs/src/plugins/coreplugin/uavgadgetmanager/uavgadgetmanager.cpp#L135

**Comment by mlyle** [comment]
Well, that's clever. :P

**Comment by jpbarraca** [comment]
Confirmed on OS X

**Comment by tracernz** [comment]
> Well, that's clever. :P

Well, it's cleverer on STM32 where 0x0 points at the base of flash :-P.

**Comment by jpbarraca** [comment]
What is the usefulness of a user adding a new workspace? I digged a little in the interface and found nothing related.

**Comment by tracernz** [comment]
Well the entire UI is fully configurable so you can setup whatever tabs you like in whatever way you like. I think probably 99% of people use the default setups provided though. I'm guessing this is related to #311 but could well be wrong because I didn't even read the diff.

**Comment by tracernz** [comment]
Can confirm #311 is the cause of this crash.

**Comment by mlyle** [comment]
OK.  Probably another instantiation case needs to be handled properly.

**Comment by mlyle** [comment]
```
0   libCore_debug.dylib             0x0000000110c6fa95 Core::UAVGadgetManager::modeChanged(Core::IMode*) + 53
1   libCore_debug.dylib             0x0000000110cdbf49 Core::UAVGadgetManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 249
2   org.qt-project.QtCore           0x0000000107be02e2 QMetaObject::activate(QObject*, int, int, void**) + 2994
3   libCore_debug.dylib             0x0000000110ce21cd Core::ModeManager::currentModeChanged(Core::IMode*) + 77
4   libCore_debug.dylib             0x0000000110c99d15 Core::ModeManager::currentTabChanged(int) + 773
5   libCore_debug.dylib             0x0000000110ce1f78 Core::ModeManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 408
6   org.qt-project.QtCore           0x0000000107be02e2 QMetaObject::activate(QObject*, int, int, void**) + 2994
7   org.qt-project.QtWidgets        0x0000000106eedd96 QTabWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 758
8   org.qt-project.QtCore           0x0000000107be02e2 QMetaObject::activate(QObject*, int, int, void**) + 2994
9   org.qt-project.QtWidgets        0x0000000106ee5303 QTabBar::setCurrentIndex(int) + 387
10  org.qt-project.QtWidgets        0x0000000106ee975c QTabBar::mouseReleaseEvent(QMouseEvent*) + 684
11  org.qt-project.QtWidgets        0x0000000106d8efcc QWidget::event(QEvent*) + 1628
12  org.qt-project.QtWidgets        0x0000000106ee6fd6 QTabBar::event(QEvent*) + 630
```
