### ISSUE TITLE
GCS:Modules: Allow specifying Vbat ratio rather than mV/V

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#658]
^As per. Should probably keep the mV/V box as well.

e.g. 11.0 rather than 90.9 mV/V for 10k/1k divider

**Comment by mluessi** [comment]
I think the mV/V field is quite useful, as most voltage and current sensors available specify mV/V and mv/A, so if a device is properly calibrated the user can just enter the numbers and it works.

**Comment by tracernz** [comment]
@mluessi Agree, that's why I kept both. :)
