### ISSUE TITLE
Input - RSSI field does not support all RX types

### ISSUE THREAD

**Issue by DTFUHF** [d-ronin/dRonin#661]
![untitled](https://cloud.githubusercontent.com/assets/4762910/13029745/bf03caba-d262-11e5-9669-3a26a51b6ae2.png)

Missing: DSM, SUMD, RFM22B (though rfm22b already has its own rssi)

**Comment by DTFUHF** [comment]
Somewhat related, PPM is limited to 12 channels, this can be a little restrictive. Sbus supports up to 18,  SUMD up to 32!

**Comment by tracernz** [comment]
Is DSM useful? I don't think there's any way to make a Spektrum Rx or Tx spit out RSSI to a channel?

**Comment by DTFUHF** [comment]
Heh, I guess not, maybe in a future RX

**Comment by mlyle** [comment]
#856 made progress towards this.  I think the only thing needed really is to turn up the channel count.

**Comment by mlyle** [comment]
This is fixed; we're stuck with channel counts for now...
