### ISSUE TITLE
GCS:Libs: Upgrade to Eigen 3.3

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#664]
When released (currently at beta http://eigen.tuxfamily.org). Previous versions use things that are deprecated in C++11, and cause compilation to fail with GCC 5.3 for @fujin.

**Comment by fujin** [comment]
confirmed

**Comment by jpahka** [comment]
Because of this in order to build current next, I need to add

QMAKE_CXXFLAGS += -Wno-error=deprecated-declarations

to the end of file ...ground/gcs/gcs.pri as per icee's suggestion.

**Comment by mlyle** [comment]
Related: TauLabs/TauLabs#2240

Hopefully Eigen 3.3 will ship soon.

**Comment by fujin** [comment]
you can cherry pick https://github.com/fujin/dronin/commit/34a79bff57af77b915dbea14242cafb5e940831dif it helps

**Comment by tracernz** [comment]
Hopefully not far away https://listengine.tuxfamily.org/lists.tuxfamily.org/eigen/2016/04/msg00017.html

**Comment by mlyle** [comment]
Eigen 3.3 beta-2 was released on July 26, 2016, so maybe there's some hope...

**Comment by mlyle** [comment]
Hopefully soon.

**Comment by mlyle** [comment]
Eigen 3.3 expected to ship next week.

**Comment by tracernz** [comment]
[Wowowowow](http://eigen.tuxfamily.org/index.php?title=News:Eigen_3.3_released!) :open_mouth:
