### ISSUE TITLE
TxPID for Damping and Noise sensitivity

### ISSUE THREAD

**Issue by ufoDziner** [d-ronin/dRonin#665]
Would be awesome to have the ability to adjust the Autotune Damping and Noise sensitivity using the TxPID module.  Thanks!

**Comment by dustin** [comment]
This is another nice aspect of the concept of pushing AT computation into
the FC.  It's quite risky, but a really neat higher level usage of txpid.

**Comment by mlyle** [comment]
Yah, though this one particularly makes me nervous.  It's a bit expensive of math to be doing in the middle of flight, and the tunes resulting may not be "continuous" / a small txpid deflection may do something wonky.

**Comment by mluessi** [comment]
This would probably only make sense on flight controllers with an OSD, so the parameters could be adjusted and new PID gains computed/inspected without needing a computer. This would be nice, but we would need to make sure that the code on the flight controller and the GCS give the same results (the GCS code is probably using double precision math, so we would need to make sure it works with single precision, etc.).

**Comment by droidicus** [comment]
Another option would be to lock the calculated PID values in place at arm, and require a dis-arm/re-arm cycle to load a new set in.

**Comment by mlyle** [comment]
This probably won't play well with neo-autotune.  defer.

**Comment by mlyle** [comment]
Unfortunately, this is the exact opposite direction from what we're thinking-- getting a great offline tune.  Closing WONTFIX
