### ISSUE TITLE
GCS: Importing UAV settings sets all UAVOs

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#668]
When importing an .uav file in the GCS, all objects present in the file are set, even if they are not selected to be saved to flash. This should not happen, as settings are changed without informing the user and attempting to fly without first restarting the flight controller (which will cause the correct settings to be read from flash) can cause a crash/unintended behaviour etc.

**Comment by jpbarraca** [comment]
I have this ready but PR #655 must be accepted (or denied) first as it will change some of the same code.

**Comment by tracernz** [comment]
@jpbarraca, if you could take care of the minor formatting issues in #655 and I'll test+merge after work tonight so you can get on this one. :-)

**Comment by jpbarraca** [comment]
@tracernz I think everything is already fixed in #655

**Comment by tracernz** [comment]
Sorry, missed the last commit, thanks! I'll be home in about 8 hours.
