### ISSUE TITLE
Refactor MSP into library

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#674]
Take TauLabs/TauLabs#2198.
Will be used by:
- UAVOMSPBridge
- BlHeliSuite integration
- Possibly TauOSD
- ???

**Comment by mlyle** [comment]
The one vote against this is that it makes incorporating the autobaud / channel switchover logic to telemetry mode hard.

**Comment by mlyle** [comment]
I think we should consider closing this

**Comment by tracernz** [comment]
I am looking at doing something with MSP for a standalone OSD target (playuavosd), will wait and see what I end up doing there I think.

**Comment by mlyle** [comment]
Whee you did this.
