### ISSUE TITLE
GCS: Setup wizard: Reboot is always requested

### ISSUE THREAD

**Issue by DTFUHF** [d-ronin/dRonin#694]
due to this: https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/boards_brainfpv/brain.cpp#L180-L181

because this sends void instead of 0: https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/setupwizard/pages/inputpage.cpp#L84

the port number itself seem superfluous, as the board type's function has the ability to scan through all available ports (as this specific hardware target does)

**Comment by tracernz** [comment]
Good catch, fancy fixing it? :D We always set port 0 I assume.
