### ISSUE TITLE
Afromini Amaze fails to be detected properly

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#702]
Afromini Amaze is coming up with `hse_value == 8000000`.  AFAICT, the code to figure out the `hse_value` is just about the same as baseflight.  Baseflight seems to also detect this as ≠ rev5, but manages to get i2c working.

If I force it to be considered a rev 5, it works fine.

(note:  I also tried next + one-true-mpu and had the same thing, just to be safe)

I'm sure I can fight with the baseflight code a bit more to figure this out.

**Comment by tracernz** [comment]
STMicroelectronics code detects the HSE freq AFAIK.

**Comment by dustin** [comment]
Right.  There's an odd difference between baseflight and dRonin's copies of the libraries, but it has no effect, AFAICT.  `hse_value` is a red herring.  I've got more work to do here, but I want to use one of these things, and it works if I use the different i2c config, so it shouldn't be _that_ hard to make it work in general.

**Comment by DTFUHF** [comment]
Since close to nobody has rev4 / afrominiv2, the mpuint pin is always on PC13, any other configuration is too old to even matter. The "12MHz detect pin" should only be used to detect which oscillator is used

**Comment by dustin** [comment]
I've got a v2.  It'd be awesome if I could make that work, but haven't got
to it yet.   I wonder how hard it'd be to stuff a hardware option somewhere
for this.

**Comment by DTFUHF** [comment]
I think even afrominirev2 has mpuint on PC13 (maybe you can verify) making rev4 support even less needed ¯_(ツ)_/¯

**Comment by mlyle** [comment]
Wish we could estimate how many R4s there are in our userbase...

**Comment by dustin** [comment]
I think I've got an OK workaround.

**Comment by tracernz** [comment]
> Wish we could estimate how many R4s there are in our userbase...

Well, I have this in the mpu branch, and the first half (runtime setting of revision) is already merged..

**Comment by tracernz** [comment]
Would be trivial to add to current code since we already detect Rev.

**Comment by mlyle** [comment]
Yes, we should add it, but that's not very informative for what we should do in the short term.
