### ISSUE TITLE
ship android GCS

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#705]
- [x] Building / running
- [x] Jenkins build
- [x] Some branding
- [x] Maps API key?
- [x] Store publishing etc?  Or just ask people to sideload.
- [x] Doesn't work in release config?  Wut?

Lots of people want this-- I was surprised.

**Comment by dustin** [comment]
Autotune?
Phone home?

**Comment by mlyle** [comment]
Not interested in spending a lot of time on this, just restoring basic functionality for the release.

**Comment by tracernz** [comment]
If we could find a Java/Android dev we could do some cool stuff. As is we just don't have time.

**Comment by mlyle** [comment]
Yah, I think our best bet long term is smushing down the normal GCS onto phones/tablets.

**Comment by mlyle** [comment]
Branding -- ic_icon.png, ic_logo.png, in ldpi, mdpi, hdpi, xhdpi (androidgcs/res/drawable-...)

**Comment by mlyle** [comment]
Good enough for Tanto.  Haven't addressed signing.

**Comment by mlyle** [comment]
Will watch the download counts and problem reports with AndroidGCS to decide how important this stuff is.

**Comment by ragd011** [comment]
I've been downloading them and trying to use them.  I was hoping that I could adjust tuning settings in the field.   I was able to connect but couldn't seem to do much.  A little while back I tried to mess with the source but it was in an older environment so migrating it and tweaking it is not a good first project :-)  So anyway, what is the AGCS useful for in its current state?
