### ISSUE TITLE
DSM binding on inverter targets (Sparky2, Quanton, Brain, CC3D, Revo) sucks

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#716]
- Some targets silently squash binding pulses when DSM is on an inverter port (S2, Revo)
- Some targets drive the external-inverter port and busfight (Quanton, Brain, CC3D?)
- Revo erroneously configures DSM to an inverter port by default.

@tracernz -- does this cover it?

**Comment by tracernz** [comment]
@mlyle Yeah I think so.

**Comment by tracernz** [comment]
The Revo is really a separate issue IMO and is a regression rather than a pre-existing bug.

**Comment by henn1001** [comment]
Yeah sorry about the revo - i didn´t quite get the logic behind the module :/

**Comment by jihlein** [comment]
In the FWIW category, an easy fix is to remove DSM support on ports with hardware inverters.  That's the path I took on the AQ32 target, no DSM on uart3.  Need to review targets in question, don't know if it would create other difficulties.

**Comment by mlyle** [comment]
We could do that, but if you have an already bound satellite it's a little limiting.  It may be the better of choices, as people will get confused about thigns not binding.

OTOH binding works so damn poorly :/

**Comment by tracernz** [comment]
Might be cleanest just to remove DSM on those ports, although not ideal if it happens to be a dedicated Rx port..

**Comment by mlyle** [comment]
Won't be further improving this before samsara; deferring.  Sorry :(
