### ISSUE TITLE
Report: Hangtime stays engaged in failsafe

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#724]
The hangtime is correct for low throttle while valid signal but failsafe kicks in LPS for ~25 seconds when hangtime is set to 2 seconds. This may be expected behavior just not what I was expecting :)

**Comment by dustin** [comment]
I was kind of hoping for that, actually.  A little surge of ST1 with an
upright descent is kind of nice.  I do wish for magic that would make
landings happen gently.

**Comment by mlyle** [comment]
THe failsafe infrastructure is moving that way.  But if someone configures hangtime for 2s it should never run for 25s.  I wonder what's happening.
