### ISSUE TITLE
GCS: Change welcome screen panels

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#73]
The current information shown on the welcome screen isn't particularly useful to end-users. We should consider replacing the Github panel with github issue titles and a link to the issue tracker. The TL forum stuff should be removed, possibly pending our own forum. If we keep the forum box it should be altered to display titles only so it fits more than one post. We should make it possible to display critical (nice bold red) announcements to users of older versions with known critical bugs.

**Comment by tracernz** [comment]
Related to #12

**Comment by tgreer** [comment]
I'm in agreement with removing the forum box, it's of no use in all honesty. We might not even have a forum.

**Comment by dustin** [comment]
I really want to host some data through autotown.  I don't care as much how it gets there (but I can have automatic polling things if someone has ideas of what they want -- bugs filed, closed, etc...)

**Comment by mlyle** [comment]
Done for now
