### ISSUE TITLE
waypoint upload over pipx doesn't work

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#739]
with or without #654; works on #654 with bluetooth.

connects to #641

**Comment by tracernz** [comment]
I wonder how this goes now.

**Comment by mlyle** [comment]
Doesn't work-- multi-instance ACK doesn't make it back from the FC to ground.  Need to investigate why.

**Comment by mlyle** [comment]
This works over openlrs :D  Still worst UI ever, but no issues specific to pipx.
