### ISSUE TITLE
GCS: Default layouts

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#74]
Reconsider the default layouts. This is one I'd like to change to in particular, the system health bar at the bottom is super useful:
![screenshot from 2015-11-28 21 21 22](https://cloud.githubusercontent.com/assets/9995998/11450901/05d28140-9616-11e5-9562-8460fa80a67a.png)

**Comment by mlyle** [comment]
Netbook can't get this, but the other two could..

**Comment by jpbarraca** [comment]
Very useful! Just got a new default layout for my GCS. Tks.

**Comment by mlyle** [comment]
Depends on #648

**Comment by mlyle** [comment]
Fixed by #1095
