### ISSUE TITLE
Sparky1 may or may not be able to run at 1kHz (with an unknown set of modules activated)

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#763]
Per nog on IRC.

```
08:57:59 <nog> bbumped mpu up to 1000 and im getting cpu overload state
```

**Comment by dustin** [comment]
I had the same issue on mine.

**Comment by mlyle** [comment]
Can someone try with current next / @mluessi's recent optimization?

**Comment by pug398** [comment]
Looks like optimization helped and cpu load at 75-78% running @1000hz. No more cpu warning but still occasional Event warning. That is with flight configuration including AH.

**Comment by mlyle** [comment]
Yes, all of the targets have occasional event warnings.  So it works for basic flight-- that's great.

If it works for autotune we can close this issue, I think.

**Comment by mlyle** [comment]
OK.  1KHz is not really recommended on Sparky1 but at least it seems to work.  Worth leaving the setting in IMO.
