### ISSUE TITLE
Hangtime/LPS throttle-jump / timeout-extend-backoff investigation/discussion

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#768]
Couple of observations/theories in testing so far, just wanted to take note of them.
- with LPS enabled (4.5sec) and max power set to 15%, when throttle 0% is commanded, then 1% (for example), what's throttle do we try to actuate? 1% or 15%? do we ramp up to the current low-power-stabilized level? are commanded throttles below the lps power level ignored?

I feel like if we are doing LPS'd 15% and then start to command 1% we should probably not jump rapidly down to 1% (or maybe we should? haven't reviewed the code yet), similarly we shouldn't jump command massively above the current LPS level (this high side version is arguably less of an issue than the low side one.)
- with LPS enabled (4.5sec), what happens when the timeout is reached?

Anecdotally when the time-out is reached, the previous zero throttle behavior is observed (motors neutral? no stability?).

I'd like to propose that if it's possible to do safely, we should attempt to extend (with a backoff?) the timeout up to a secondary maximum. I think there may be a safety concerned here for crashing while armed. This be a compromise for behaviour compared to an always-on switch.

Please close if this is all silly rubbish. Thanks!

**Comment by mlyle** [comment]
If you command x throttle, it tries to do x throttle.  If necessary, it adds motor thrust, ensuring that the total power doesn't exceed x+max power add.

The tooltip in the UI says:

> This specifies the maximum amount of power to add when stabilization needs more total power than specified by the throttle input.  This is used during HangTime and other maneuvers.
