### ISSUE TITLE
Altitude Hold not working on Naze32 running dronin

### ISSUE THREAD

**Issue by kjoy84** [d-ronin/dRonin#785]
Does anyone on here have experience using the "altitude hold" function on the Naze32 running Dronin. I have put a Naze32 10POF (I think rev 6) that has a magnetometer and barometer on my tricopter. I am using Dronin, not baseflight or cleanflight. The autotune function works great. My problem is that I can't get the altitude hold function to work. The altitude module enables but when add the altitude hold function to my flight mode switch the FC goes into a system configuration error state and will not arm. And it doesn't seem correct even if I am disarm in a different flight mode. Any ideas?

I have two Naze32's, both are doing the same thing.

**Comment by dustin** [comment]
The baro isn't currently supported.

**Comment by kjoy84** [comment]
Thank you both
