### ISSUE TITLE
GCS:Modules: Disable checkboxes for modules unavailable on current hardware

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#786]
Should help with e.g. #785 where the module appears enabled but there's nobody listening to the module adminstate on the flight side.

**Comment by jpbarraca** [comment]
On the current next this seems to be already implemented. 
The following image shows the module interface in a CC3D with some modules disabled.
Oddly, there is no GPS but there is geofence...?

<img width="1788" alt="cc3d-modules" src="https://cloud.githubusercontent.com/assets/497717/14334555/14ba9a38-fc4d-11e5-9593-42fd8474230c.PNG">

**Comment by mlyle** [comment]
The greyed ones are the ones that are either:
- turned on or off on a different GCS page
- automatically turn on when you configure a port to use them

**Comment by tracernz** [comment]
I'll separate the auto-enabled ones in the UI soon.

**Comment by mlyle** [comment]
I think my preferred approach for this would be--
- alter task status, to have 'not present', not running, or running status.
- have tasks default to 'not present'
- add a call to set a tasks status from not present -> not running
- have all modules call that at init time
- have GCS react to this appropriately.

**Comment by tracernz** [comment]
Yes, I'd like to do that. Doesn't work for F1 though...

**Comment by mlyle** [comment]
Fixed by #993
