### ISSUE TITLE
BrainFPV support

### ISSUE THREAD

**Issue by fujin** [d-ronin/dronin#8]
With the relaxation of strict open-hardware policies it will be possible for us to have BrainFPV in-tree, with unified GCS, packaging, release timelines, if @BrainFPV is up for it.

What needs to be done to make this happen? Is everyone OK with the idea? Brain is a great, commodity board with excellent performance.

**Comment by tgreer** [comment]
+1 to this. I love the brain hardware, it bugs me that (though no fault of @BrainFPV) there's a delay in stuff making it down to the brain tree.

**Comment by jihlein** [comment]
Could possibly do the same with the Dodo, cleaning up (primarily removing the bootloader) the code I already have.

**Comment by fujin** [comment]
@jihlein I have local modifications for that I had some success testing on spracing3, tornadof3 as well. I think supporting the f3-clone-derivative boards is also a good idea. Will log an issue. :+1:

**Comment by fujin** [comment]
Latest @ #36

**Comment by tgreer** [comment]
Closing this as #36 has now been merged. Yay!
