### ISSUE TITLE
Request: Ability to have external mag on Revo

### ISSUE THREAD

**Issue by rabno1** [d-ronin/dRonin#805]
Wouldn't even know where to start to get this working myself but would love to be able to use the external mag in my cheapo GPS with my revolution fc.  I believe the mag uses I2C and would be great if we could use the flexi port to connect it to.
Ill do anything i can to help.

**Comment by jihlein** [comment]
I actually have this done, but not tested. Let me rebase and make sure it still builds, then I'll push a PR. Someone with a Revolution will have to test.

**Comment by mlyle** [comment]
@rabno1-- do you have an external mag and are you able to confirm that https://github.com/d-ronin/dRonin/pull/806#issuecomment-197154629  works?

Note that the magnetometer heading shows up as a red stripe in the primary flight display on the flight data tab.

**Comment by rabno1** [comment]
Wow that was quick. Ill need to wire up the mag but ill get on it and test it out. Ill report back ASAP.
