### ISSUE TITLE
Quanton boot panic/loop

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#82]
User has reported Quanton boot failure / panic loop via IRC, investigate/fix.

```
09:01 <sfabris> don't know if it is expected, but my quanton is bootlooping with dronin :-(
09:02 <sfabris> (dronin next, just pulled)
```

**Comment by sfabris** [comment]
GCS and firmware pulled from dronin:

Built on Nov 28 2015 at 19:56:55
From revision 87f49a9d 20151128
UAVO hash 86ca6bf0

From what fujin  is saying on irc should be a panic(1) (one brief blue led flash).

**Comment by jihlein** [comment]
My Quanton seems to be working fine. Maybe eeprom needs to be cleared and the setup restarted from a clean state?

**Comment by mlyle** [comment]
If it's one flash and not repeating it's not a panic.  But it could be an invalid-config related boot fault.

**Comment by mlyle** [comment]
@sfabris -- any details?  does this still happen after config reset?

**Comment by sfabris** [comment]
Can't try for a few days, as I am travelling. Will test and report once
back.

2015-12-03 1:12 GMT+01:00 Michael Lyle <notifications@github.com>:

**Comment by mlyle** [comment]
WORKSFORME  I suspect this is actually #83
