### ISSUE TITLE
Recurring situations where old configuration causes boot-time reset

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#83]
We need to run this problem down and kill it with fire.

**Comment by mlyle** [comment]
Relates to #3

**Comment by tracernz** [comment]
Should be fixed by #801

**Comment by tracernz** [comment]
@mlyle, since you're not planning to use upgrader (?) for pipxtreme, this issue is not fixed?

**Comment by mlyle** [comment]
I think it'd be much more challenging to fill pipxtreme flash-- like, OK, technically possible, but...

**Comment by mlyle** [comment]
(only one object stored on pipxtreme)

**Comment by tracernz** [comment]
Assuming that filling the flash is the issue ;-).

**Comment by mlyle** [comment]
;) well, if it's not... the issue has never been seen on pipx, so...

**Comment by tracernz** [comment]
Did that issue the other day turn out to be something else?

**Comment by mlyle** [comment]
I think they reflashed it again and it started working.
