### ISSUE TITLE
VehicleSetupWizard should prevent PWM+Oneshot configs on CC3D

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#847]
They're an illegal combination because of shared timer resources.

**Comment by tracernz** [comment]
It would be nice to do this in a more general way using the timer bank information already in the board plugins.

**Comment by mlyle** [comment]
This one comes up a lot.  Marking blocker.

**Comment by mlyle** [comment]
No longer necessary with the "fake oneshotting" introduced by #958
