### ISSUE TITLE
Tanto Beta2 Issue

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#861]
Checklist:
- [x] Check androidGCS
- [x] Check upgrade scenarios from LP
- [ ] Check upgrade scenarios from OP, if able
- [x] Check upgrade scenarios from TL
- [x] Check upgrade scenarios-- wrong bootloader that doesn't show settings partition
- [x] #862 AltHoldSettings import anomaly
- [x] #868 Uploader-- multiple devices in bootloader state
- [ ] PathPlannerSettings import anomaly-- low severity, but worth investigating to see if it contaminates other things

For keeping track of rev, non-bug feedback, relnote draft, etc.

Documentation:  http://dronin.readme.io

~~Githash: 4c53eeeb47601920e2e0614f94c25b640f7675ca~~ (was build 281)
Githash: 44ca0c08d27ea5501eb399b5cba64225ff338fcc
- Windows: http://jar.lyle.org:8080/job/dronin/286/Nodes=winx86/
- OSX: http://jar.lyle.org:8080/job/dronin/286/Nodes=osx/
- Linux/Android: http://jar.lyle.org:8080/job/dronin/286/Nodes=master/

**Comment by fujin** [comment]
woo!

**Comment by cpusmith** [comment]
![image](https://cloud.githubusercontent.com/assets/4100472/14197657/e7e941d8-f79e-11e5-8454-f28500d93da9.png)

Should the selection boxes be so wide?

**Comment by mlyle** [comment]
@cpusmith -- change @tracernz made, I thought it was kinda cute.

**Comment by mlyle** [comment]
This is the second major release of the dRonin flight controller firmware.  It feels like we've made a lot of progress– and we hope you agree!  Significant effort was put into usability, reliability, and the upgrade process, and new features like HangTime (low-power stabilization) are a lot of fun.

Please see our new documentation at: http://dRonin.readme.io

Jump ahead to: [Changes](#changes) /  [Errata & troubleshooting](#errata)  /  [Download files](#artifacts)

**This software is provided without any warranty. Use at your own risk!**

## <a name="changes"></a> Major changes since last release:
- Upgrade simplified for all targets except Naze32 and PipXtreme.  To upgrade, just start the ground control system and then plug in the flight board, and carefully follow the on-screen prompts. [Further information is on the wiki.](https://github.com/d-ronin/dRonin/wiki/Upgrade)
- HangTime allows controlled maneuvering for a limited time at zero throttle in multirotors.  HangTime should be used with switch arming and power settings that are well under hover power. [See the HangTime documentation for more details](https://github.com/d-ronin/dRonin/wiki/HangTime)
- Intelligent clipping management added to improve vehicle performance when motors are near minimum or maximum speed.  In these cases, an "Actuators" alarm will fire that is visible on on-screen displays (Brain, MWOSD).
- The Naze32 rev6 flight controller is now supported.
- Telemetry and configuration subsystem is now considerably faster to connect and more reliable.
- Many modules are now automatically enabled or disabled based on port configuration.
- Further improvements to CCPM helicopter flight modes and configurability.
- Support for the Storm32 Brushless Gimbal Controller across most targets.
- Support for sending GPS data across MSP protocol to MWOSD.
- Support for OpenLog across most larger targets.
- Support for non-inverted SBus, for ports that do not have an integrated inverter or for radios that send non-inverted SBus.
- Significant improvements to performance of altitude-hold mode.
- Additional port types and configurations are supported on the Revolution, Quanton, and Colibri flight controllers.
- External magnetometers supported on the Revolution flight controller.
- New failsafe flight mode to allow deliberate triggering of failsafe behavior with flight mode switch.
- Improvement to board hardware configuration for Lumenier LUX and simulator targets.
- Retrofit of USB subsystem in ground control software eliminates a major cause of crashes and hangs.
- Included minimal version of Android GCS (as an .apk file for side-loading).
- Vehicle setup wizard now follows best practices-- no standard PWM output, enables spin while armed behavior.
- Freed resources-- CPU, memory, and flash-- across all flight boards
- Board-specific ADC pin names display in GCS to improve battery module usability.
- Ensured consistent support for receiver and telemetry protocols across ports on all targets.
- Renamed targets for usability: "revomini" is now "revolution", "coptercontrol" is now CC3D.
- Acro+ insanity factor is now configurable on the expert stabilization configuration pane.
- Actuator curve fit default value changed to 0.9; it is now configurable on the expert stabilization configuration pane.
- "Apply" button removed from most screens of GCS in favor of a single "Save" button.
- Significantly improved dialog to import saved UAV configurations.
- Bugs where objects could fail to save in the UAV Object Browser were corrected.
- Input wizard is much less likely to falsely detect axis activity.
- Various other usability and look and feel improvements to the ground control software.
- MWRate and Throttle PID Attenuation are now deprecated and will be removed in a future release.
- Development infrastructure and upstream libraries upgraded: Arm 2015Q4 tools, qt-5.51, STM32 Libraries.
- Ease of configuring Windows development environment improved.
- Python API augmented to have additional functionality to read configurations and to more flexibly handle logs.
- Windows installer now ensures that old files from previous installations are removed to prevent erratic behavior.

## <a name="errata"></a>Errata & Troubleshooting
- Windows: If you are unable to communicate with the flight controller after plugging it in, please see [this procedure](https://github.com/d-ronin/dRonin/wiki/Windows-driver-troubleshooting) for a possible solution.
- Windows: If using older Intel integrated graphics, you may need to [follow this procedure](https://github.com/d-ronin/dRonin/wiki/Running-the-GCS-on-non-OpenGL-2.1-capable-systems) to start GCS.
- Windows: If you receive the message "The program cannot start because MSVCR120.dll is missing from your computer," you must [download the Microsoft Visual C++ runtime](https://www.microsoft.com/en-us/download/details.aspx?id=40784) to proceed.  Please download the `vcredist_x86.exe` version of the package.  This is not usually necessary because most computers have installed software that requires this before. 
- OS X: the application is unsigned; it is necessary to open `Applications`, right-click on `dRonin GCS` and select `Open` on the first launch. 
- Linux: you will have to install .udev rules for the device. The .deb package attempts to do this automatically.  To do this manually, [download the udev permissions file](https://raw.githubusercontent.com/d-ronin/dRonin/next/package/linux/deb/_package.udev) and then run `sudo cp _package.udev /etc/udev/rules.d/45-dronin-permissions.rules && sudo udevadm control --reload-rules`
- Naze32: support is still early.  There is no support for flashing boards in GCS.  The procedure to flash a Naze32 is [here](https://github.com/d-ronin/dRonin/wiki/OpenNaze-Naze32).

<a name="artifacts"></a>

**Comment by fujin** [comment]
typo:

> Fred resources-- CPU, memory, and flash-- across all flight boards

**Comment by fujin** [comment]
`CCPM` with regard to helis is? collective.. pitch..? not CPPM right?

**Comment by fujin** [comment]
omg sorry pressed close by acccident

**Comment by fujin** [comment]
typo:

> Significantly iproved ialog to import saved UAV configurations.

are you going to proof/spellcheck this yet, @mlyle ?

**Comment by mlyle** [comment]
I'm going to work on editing it more, yes

**Comment by mlyle** [comment]
I think however I cut and paste it ate some letters :P

**Comment by tracernz** [comment]
@mlyle The change wasn't really intentional, just a side effect of not explicitly setting the widget size. :-P

**Comment by fujin** [comment]
@mlyle happy to read over before it's published :) looks like some simple stuff that gspell or whatever would pick up.

**Comment by pug398** [comment]
In a settings file I know the order of the objects does not matter but how about the order of the fields within a object? Trying to track down an issue with importing pathplanner settings.

**Comment by mlyle** [comment]
It shouldn't, no.. 

I haven't tried to repro the pathplanner thing yet, but I've audited a lot of code.  The flight side there does some slightly odd things (not new) but they don't look wrong, per se.

**Comment by mlyle** [comment]
Relnotes mostly done and ready for any review.

**Comment by mluessi** [comment]
Looks good to me :)

**Comment by tracernz** [comment]
Rel notes looking pretty good now. Maybe /s/now CC3D/now "cc3d"/ to be consistent.

@fujin Missed your comment earlier, https://en.wikipedia.org/wiki/Cyclic/collective_pitch_mixing ;-)

**Comment by pug398** [comment]
Is android GCS supplied in Master suppose to be a copy of the dev signed apk or exported without any key?

**Comment by mlyle** [comment]
@pug398 -- for the GCS that will ship with Tanto, it'll be an unsigned image for side-loading.

#705 is the bug where we brought the build infrastructure back, and deferred a couple of remaining issues (maps API, store, signing) to another release.

(We've not enregistered in the google play store or the Maps API program etc yet).

**Comment by pug398** [comment]
@mlyle So to date the unsigned apks are just placeholders and are not actually suppose to install on a device?

**Comment by mlyle** [comment]
@pug398 -- I've installed them on my device.. I just have sideloaded it with bluetooth and started it.

**Comment by mlyle** [comment]
(Am I missing something?  I don't think I did anything special to use our artifact)

**Comment by pug398** [comment]
I don't know. None of them will install for me and I have "non Play" security turned off.

**Comment by mlyle** [comment]
What android version?  @tracernz what have you used-- you've been successful right?

**Comment by tracernz** [comment]
Perhaps you need to have your device in developer mode to install it? Settings > About phone and tap "Build number" seven times. I loaded it using `make androidgcs_install` which uses ADB, so debugging needs to be enabled for that method.

**Comment by mlyle** [comment]
Hm, I am not in developer mode; on moto x pure on android 6.

**Comment by pug398** [comment]
@tracernz 
Thank you for that tidbit of info. That is way cool. Unfortunately apk still will not install.

Android version 4.4.2

**Comment by mlyle** [comment]
I think I see.  It looks like the apk doesn't work in the release configuration.  Fixing.

**Comment by pug398** [comment]
Before I forget again there are a couple of minor issues with browser object descriptions. Not sure if you want to fix them up before release.
Settings>CameraStabSettings - remove one of the m from module
Settings>OnScreenDisplayPageSettings -  add c to all mention of sreen 
Data Objects>FlightTelemetryStats - change openpilot to autopilot maybe
Data Objects>SystemAlarms - change openpilot to autopilot maybe

**Comment by pug398** [comment]
Same for Settings>OnScreenDisplaySettings as it looks like it has it's own description.

**Comment by tracernz** [comment]
@pug398 I have some of this done in a branch I started working on the other day (it does a lot of other stuff to UAVOs as well). https://github.com/tracernz/dronin/tree/mrc-uavo-stuffs

**Comment by mlyle** [comment]
ok, stopping doing it then :)

**Comment by pug398** [comment]
Cool. I have been meaning to mention it for awhile but it kept slipping my mind. Doesn't take much you know :)

**Comment by tracernz** [comment]
Maybe fix the typos etc. up for this release and I will rebase it out of my branch since it won't land for a while.

**Comment by mlyle** [comment]
New beta artifacts posted above

**Comment by pug398** [comment]
Android GCS working now. Good job :)

**Comment by jhitesma** [comment]
Tried the android GCS last night now that I have a new phone with a connector that isn't worn out.  Seemed to work just fine.  At least as well as the android GCS ever worked.
