### ISSUE TITLE
Bootloader: Board revision management is bad.

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#869]
1. Revision should be volatile so it doesn't get const-optimized.
2. Revision should default to 0xffff and be short aligned (e.g. be programmable at runtime).
3. BU should preserve revision when doing a boot-update. (instead of failing if revision mismatch).
4. Procedure should exist for programming board revision at commissioning-time.

**Comment by tracernz** [comment]
Where possible we should detect revision at runtime (e.g. like we do on Naze32). Need to study schematics of other boards to see where else this might be possible.

**Comment by mlyle** [comment]
Yah, 0xffff can mean 'detect at runtime' for any targets that support it.

**Comment by tracernz** [comment]
Indeed. :-)

**Comment by mlyle** [comment]
I think we should just leave this as a bit of yucky legacy.  Really verifying this to be correct is too hard.
