### ISSUE TITLE
Use single wire mode for HOTT telemetry

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#885]
HOTT is a single wire protocol, so on F3 and F4 we should use single wire mode for the UART. This makes it easier for users, as the cable only has to be connected to the Tx pin.

@tracernz I think you are using this system, WDYT?

**Comment by droidicus** [comment]
Could this also be applied to FrSky S.BUS telemetry?

**Comment by mlyle** [comment]
frsky smartport telemetry?  it already is, on F3 (where we have hardware inversion).  it will be on brainre1 as a special case, too.

**Comment by droidicus** [comment]
Yea, S.Port, I always get the two confused...

**Comment by mlyle** [comment]
Deferred pending any further user complaint on this topic.

**Comment by tracernz** [comment]
I wonder if we actually have any HoTT telemetry users. Maybe I can get that from usage data. (For the record/OP, I don't have any Graupner gear, just Jeti and Spektrum)

**Comment by mlyle** [comment]
It's somewhat obscure, and definitely isn't very usable on our setup (both because of this issue and the UI etc).

**Comment by tracernz** [comment]
I want to find somebody with Graupner gear who is willing to test some stuff so I can refactor it into the SRXL driver. :wink: We can also test this with the same person if they appear.

**Comment by mlyle** [comment]
I'll keep an eye out.

![0e3df60cabeec611be2872b82db57458](https://cloud.githubusercontent.com/assets/90903/19180226/cd5c5760-8c18-11e6-971f-5b0bf7c574be.jpg)

**Comment by jihlein** [comment]
I have a Graupner system at work, part of a Mikrocopter octo setup.  It's never been used.  Let me see if I can borrow it to help test this.  

I'll check when I get back to the office next week.
