### ISSUE TITLE
MSP->UAVTalk autodetect doesn't seem to work at 115200

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#890]
Reported by @malcurin on IRC.

Maybe our state machine for the basic case doesn't work-- when the telemetry and MSP baud rates are the same.

**Comment by dustin** [comment]
I thought it wasn't working at 115200 and did work at 57600

**Comment by mlyle** [comment]
Sorry got distracted

**Comment by mlyle** [comment]
OK, I think my interpretation of events is this:
- User had telemetry speed on flight board set to 57600
- User connected with MSP module enabled, changed MSP->telemetry
- User couldn't connect with GCS set to 115200 and telemetry set explicitly to 57600

Suggested changes--
- We need tracernz's stuff so we can simultaneously do autotune & MSP -- #762 -- to eliminate some of this error-prone stuff.
