### ISSUE TITLE
Documentation:  Need to document how to get dRonin-MWOSD

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#899]
And/or make a distribution etc

cc @dustin

**Comment by tracernz** [comment]
Same as MWOSD procedure for other FCs except uncomment define DRONIN instead of define X.

**Comment by mlyle** [comment]
Yah.  sucks to make people compile stuff etc though.

**Comment by tracernz** [comment]
It's the arduino way

**Comment by mlyle** [comment]
oh shit, wrong issue number in #1016.

**Comment by fujin** [comment]
hmmm.. I don't think this is valid? you just `#define DRONIN` and you are good to go.. the rest is all user-config

**Comment by mlyle** [comment]
People have showed up many times and asked about it (and expected preloaded images to work, etc)-- seems like a couple paragraphs in the docs would help.

**Comment by tracernz** [comment]
We could pull some of the work in ShikOfTheRa/scarab-osd#222 into a PR and see if we can get Makefile building happening in upstream scarab-osd. That should get us closer.

**Comment by tracernz** [comment]
Some brief docs for this release: https://github.com/d-ronin/dRonin/wiki/User-Guide:-Setting-Up-MWOSD. Would appreciate test and feedback.

**Comment by emaugain** [comment]
@tracernz I have a micro minimosd so I can test this out.

**Comment by tracernz** [comment]
@emaugain I suspect a few of the details could be documented more clearly/explicitly. I'd be greatful for your feedback. :+1:

**Comment by emaugain** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
https://dronin.readme.io/docs/configuring-mwosd-for-dronin

**Comment by emaugain** [comment]
@mlyle tested this and the guide was clear - i don't see flight mode and armed/un-armed
(used to show on cleanflight) am i missing anything?

**Comment by dustin** [comment]
Arm state is implicit.  Detailed flight modes currently requires lots of
extension (as they're also implicit in the base feature set).

It's not clear what you see it what you're doing. There are lots of ways to
get that stuff to not show up in mwosd.

**Comment by jihlein** [comment]
I had started a re-work of MWOSD such that it would display armed/unarmed and the Dronin specific modes.  It's on my todo list to finish.

**Comment by dustin** [comment]
I've not had an issue with arm/disarm.  Is something broken?

The mode-specific thing is currently done in one of like, three ways in
MWOSD.  :/  The one we're using is kind of implicit based on compatibility
with MW.  It's pretty gross.  There's another that has named modes that go
across the wire, but MWOSD still needs to know all the modes in order to
render them (since it's a font thing).
