### ISSUE TITLE
Flight: SUMD: Strange stick scaling on inputs

### ISSUE THREAD

**Issue by DTFUHF** [d-ronin/dRonin#912]
This line: https://github.com/d-ronin/dRonin/blob/080150a5b271fcfb3fe36aa1e20f92fc0d956aca/flight/PiOS/Common/pios_hsum.c#L255

has the effect of scaling SUMD's inputs around a center value of 1500, the protocol is described here on page 4: http://www.deviationtx.com/media/kunena/attachments/98/HoTT-SUMD-Spec-REV01-12062012-pdf.pdf

It's likely this scaling is used for another Graupner protocol, SUMD only requires simple /8 on these values.

**Comment by tracernz** [comment]
Our convention is to not even scale channel values in the driver so this should be removed I think.

**Comment by fujin** [comment]
Confirmed? I think:
![1460690722](https://cloud.githubusercontent.com/assets/6873/14550619/4d622f5e-031e-11e6-8bc8-98a344a38681.png)

**Comment by tracernz** [comment]
Let's remove the scaling and pass raw values out of the rx driver, as we do for other rx drivers. ManualControl normalises them on [-1.0, 1.0] already so no point doing it twice.

**Comment by mlyle** [comment]
as long as it fits easily into uint16_t and stays well over  0 and under, say, 60000, i'm cool with this plan.

**Comment by tracernz** [comment]
It is a uint16_t...

**Comment by tracernz** [comment]
Possible values are in the docs. I intend to replace the HSUM driver with a generic SRXL driver that supports all variants of SRXL.

**Comment by mlyle** [comment]
Yes, but we have special values at the top and bottom of the uint16_t range..

**Comment by tracernz** [comment]
Yep, it doesn't go to those, as per the specification document above ;-) (max is 0x41a0 == 16800). FWIW, the special values are -1, -2 and -3 (65535, 65534 and 65533).

**Comment by DTFUHF** [comment]
It probably wouldn't hurt to add a check for those values upon reception,
as the protocol is capable of transmitting them.

**Comment by mlyle** [comment]
If 0 is possible (haven't read the document) we should probably offset the range, too.  0 is not currently special but it seems wise to avoid it.

**Comment by tracernz** [comment]
<img width="1081" alt="untitled" src="https://cloud.githubusercontent.com/assets/9995998/14575818/83474f60-03b8-11e6-90a7-82cee0f28ff0.png">

**Comment by mlyle** [comment]
nice
