### ISSUE TITLE
S.Bus not working on Lux with Tanto

### ISSUE THREAD

**Issue by droidicus** [d-ronin/dRonin#914]
Cannot get S.Bus working on Lux FC with Tanto. If I flash Renatus it works fine, but a reflash with Tanto and no data is being received. Tried with settings translation (autoupgrade), manually, and with config wizard.

**Comment by fujin** [comment]
Confirmed not working on my freshly flashed Tanto LUX :( I didn't get a chance to test before release. Doesn't pick up throttle, shows connected:false, etc.

**Comment by fujin** [comment]
@mlyle maybe we wanna bump the priority on this a little? :) can we do a hotfix?

**Comment by jihlein** [comment]
I see the problem for the rxport. It should work on main or flexi. I can put together the fix tomorrow evening. The port configuration is missing for the rxport. None of the serial rx's will work.

**Comment by tracernz** [comment]
This is not a regression, it's been there forever and nobody noticed so I think priority/low is justified: https://github.com/d-ronin/dRonin/blob/1ac0ae516f9bebbebbbeaec6ac6664bf588f5462/flight/targets/acbro/fw/pios_board.c#L308

**Comment by droidicus** [comment]
@tracernz as indicated above, this works in Renatus, and does not work in Tanto, I would call that a regression in back-to-back releases.

**Comment by tracernz** [comment]
Then the missing rxport config wasn't the issue? Or something else changed...

**Comment by jihlein** [comment]
The missing rx port is the issue.  The problem was introduced when the PIOS_HAL argument list was reduced in PR #403.  The same issue was discovered, and fixed, in Sparky.  Unfortunately we didn't catch it in Lux. 

Let me know if I should fix it on the Tanto branch or next branch.  The fix affects 2 files.

**Comment by droidicus** [comment]
@jihlein I would submit a PR to next, it can be cherrypicked if we do a hotfix at a later time.
