### ISSUE TITLE
Report: some imported values don't get saved

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#919]
Unconfirmed, but reported by @pug398 who is distressingly accurate about these types of things.

Particularly Altitude Settings or Sparky1 HW settings.

It's possible we have some kind of issue with the save-object state machine on GCS or flight side, or it's a general problem with telemetry.  Or something else entirely.

**Comment by pug398** [comment]
I will watch the update process closer and name each fc cloud settings file with a unique identifier. Then I will still have the original exported data should I find an issue after doing multiple auto updates. The previous reported problem of PathPlanner settings not importing to sparky2 flash might be related to this.

**Comment by pug398** [comment]
Sparky2 simply does not save AltitudeHold settings in flash for me. They import in but do not save to flash. They are present in the cloud file and exported uav file, import in (both auto/manual) but as soon as board power is cycled it is lost. You can import either way, go to the browser, save and they stick. It is not being written to flash on import.

**Comment by pug398** [comment]
20160211-efc3 and previous (working), 20160223-49ed and later (not working). Most likely introduced when import changes were made somewhere in between.

**Comment by mlyle** [comment]
@pug398 cool-- that was one of two things I suspected.

Kids are off school this week so I've not been super productive-- but I'll be able to audit that set of importer changes soon to see why it could be skipping saves.

**Comment by pug398** [comment]
With 685711b0 20160418 HW, AH and PathPlanner settings all saved permanently on sparky2.
All settings saved permanently on sparky1. The ones I had issue with appear to be saving now.

**Comment by mlyle** [comment]
Ick.. we didn't fix anything :P

**Comment by pug398** [comment]
Perhaps a change in firmware timing? Updating firmware was the only change on my end.

**Comment by jihlein** [comment]
I'm seeing some odd behavior on latest next with AQ32 target.  I can't save frame type or output channels.  I did an erase settings and tried again, still unable to save.

Also have noticed the same on Sparky.

**Comment by mlyle** [comment]
@jihlein -- try a clean build.  Odds are there's problems with build dependencies resulting in mismatched objects between firmware and GCS to get problems like that.

**Comment by jihlein** [comment]
I did.  Just noticed that if I hit save twice before rebooting, it saves.  Let me experiment some more.

**Comment by pug398** [comment]
I have seen the need to save twice before as well. c98a wouldn't save some objects but 6857 has saved all objects so far. As soon as Jenkins is going again I will try the next build to see if it continues to save or whether it was just blind luck.

**Comment by pug398** [comment]
I just upgraded sparky1, sparky2, revo and quanton with a7dc and all settings saved properly. Don't know but it sure seems a lot better now :)

**Comment by mlyle** [comment]
Closing because no recent repro.  Yuck.  (Though there's been some related fix / robustness improvement).
