### ISSUE TITLE
GCS:Flight Modes:Remove Multiwii mode deprecation note

### ISSUE THREAD

**Issue by pug398** [d-ronin/dRonin#934]
- Seen in version (release version or githash): 685711b0 20160418
- On flight controller (if applicable): 

Issue details:
Multiwii flight mode removed but note about deprecation is still present on Input>Flight Mode Switch Settings tab.

**Comment by pug398** [comment]
Or perhaps it is planned to be removed once the MWRate mode is removed from dropdown.

**Comment by mlyle** [comment]
Apparently I screwed this up... :P
