### ISSUE TITLE
Yaw/Roll camera tilt based reprojection (C.A.T.S)

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#951]
- Seen in version (release version or githash): 
  all
- On flight controller (if applicable): 
  all

Issue details:
In cases of significant camera tilt, yaw and roll effects can begin to be reversed.

@DTFUHF started a branch to reproject roll and yaw based on the camera tilt uavo :joy_cat: - I brought this up to date here: https://github.com/fujin/dronin/tree/cats

@mlyle suggests the following for a more correct implementation:
- [x] add a Stabilization1Reprojection /2/3 to ManualControlSettings...
- [x] change stabilization to pull it out at the same time it pulls out the stabilization1settings for what axis is what
- [x] put that code in stabilization, to be used when reprojection TiltAngle is chosen
- [x] could punt this to someone else -- add UI to pick a reprojection

Need to be super careful about autotune flights here I expect. Like potentially disable the reprojection while doing so.

```
09:03:04 <icee> then someone else could use the same infrastructure to make like, reprojection HeadFree
09:03:43 <icee> and you can turn on and off the reprojection with the flight mode switch
09:04:05 <icee> like have rate/rate/rate/tiltanglecomp, level/level/rate/nocomp, rate/rate/rate/nocomp flight modes
09:04:37 <icee> ufoDziner / fujin-- oh, be cautious-- DO NOT fly with this code / with a non-zero tilt angle like on an autotune flight
```

**Comment by mlyle** [comment]
> Need to be super careful about autotune flights here I expect. Like potentially disable the reprojection while doing so.

Note that building the infrastructure this way will automatically disable reprojection during autotune (because you won't be in a stabilization bank and hence will have no reprojection chosen).
