### ISSUE TITLE
Flight:Attitude: Unsafe UAVO Callback Usage

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#953]
UAVO callback (https://github.com/d-ronin/dRonin/blob/next/flight/Modules/Attitude/attitude.c#L1468) touches lots of variables that aren't marked volatile. Compiler can perform unsafe optimizations. Should follow standard pattern of setting a flag and checking it each iteration of the task.

**Comment by mlyle** [comment]
Stabilization does this too
