### ISSUE TITLE
GCS:Import/Export UAVO JSON Support

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#954]
We use JSON representation of UAVOs in quite a few places now, esp. Autotown. Would be nice to be able to import UAVOs in this format.

**Comment by yamahabest** [comment]
This doesn't sound that difficult, @tracernz would you have some more information/pointers?

**Comment by mlyle** [comment]
@tracernz -- is this so important now that cloud stuff speaks XML?

**Comment by tracernz** [comment]
Not really important, just more convenient in python/JavaScript/c++/etc. 😜 And of course less verbose and more human readable.

**Comment by mlyle** [comment]
Cloud stuff now imports XML too-- recommend we close this.  Bad for end-users to have multiple formats.

**Comment by tracernz** [comment]
It's a shame that it's XML but agree yes.
