### ISSUE TITLE
TxPID not usable - extremely large values

### ISSUE THREAD

**Issue by fabianhu** [d-ronin/dRonin#970]
- Seen in version (release version or githash): 2016-04-09.2
- On flight controller (if applicable): Sparky
  OS: Ubuntu 15.10

Issue details:
Set up TxPID, with SUMD as input, selected aux 0..2 as inputs
entered e.g. 10 and 50 as the range values, which are converted to 10,00000 and 50,00000 (where ',' (Comma) is the decimal separator in my locale
Everything seems fine to this point.

In the Stability pane, the PID values are updated with values 10000... (can't see all zeroes) to 50000....
Changing the locale to '.' as decimal separator does not change the behaviour.
Scaling down to 0.001 to 0.005 does the job for pitch.Kp and pitch.Ki, but pitch.Kd shows some really strange behaviour.

Am I confused by the fact that the values are multiplied by 1000 from  the internal value in the basic view?

Best regards, Fabian

**Comment by mlyle** [comment]
@fabianhu the "real" PID values-- as shown on the advanced and expert panes are the actual values multiplied by the angular rate or the angle to come up with control outputs.  These are very small values--  the default P of 0.002 reacts to an angular rate of 10 deg/sec with a 2% control movement.

However, values like 0.00003 for derivative aren't very user friendly to someone sliding a big slider, so the basic tab has values that are significantly higher-- 10000x higher.

**Comment by mlyle** [comment]
P.S. the scaling factor for basic kD is: `<string>scale:0.000001</string>`
