### ISSUE TITLE
Feature: Check from GCS for new release, and offer to download/update automatically

### ISSUE THREAD

**Issue by yamahabest** [d-ronin/dRonin#974]
Could help getting users to the latest release.

**Comment by tracernz** [comment]
@PTDreamer was working on this but he's been MIA for a while..

**Comment by yamahabest** [comment]
That's too bad. Functionality would be nice to have.

**Comment by mlyle** [comment]
Yup.

Whether there's auto-upgrade (which I'm a bit meh about) or notification... it would be nice to have.

It pays no dividends until the release after it's shipped, though. ;)

**Comment by tracernz** [comment]
Notification should be easy enough. Just a question of whether we do it through autotown or directly with github API.

**Comment by yamahabest** [comment]
I could imagine an Alpha, Beta, Release setting.
Where Alpha is "nightly" build, Beta pre-release and Release ...

Would really like auto-upgrade, after approval of user of course, but a notification (maybe with the release notes, and a link to the download location) is already a good step.

**Comment by dustin** [comment]
There was discussion about this yesterday which seemed to conclude that using something like an [appcast](https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds) would be appropriate.
