### ISSUE TITLE
Mixer's getting lost

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#981]
- Seen in version (release version or githash): mpl-tantobeta-151-g97e129c
- On flight controller (if applicable): afromini amaze (naze32)

Issue details:

Each time I connect to my vehicle, the vtail mixer has rudder and pitch at 100%.

The stored mixer isn't actually changing, so I think this might just be a display issue.

**Comment by mlyle** [comment]
Almost certaintly dup #747
