### ISSUE TITLE
Can't store PIDs

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#982]
- Seen in version (release version or githash): mpl-tantobeta-151-g97e129c
- On flight controller (if applicable): Afromini Amaze (naze32)

Issue details:

In a fixed wing vtail config, I'm trying to turn down PIDs.  I can see the effect sometimes, but I get a red x when I attempt to store.

Not sure if anything is useful in the logs, but this is what I see:

```
23:41:56[DEBUG][smartsavebutton.cpp] Sending object to remote end -  "StabilizationSettings"
23:41:56[DEBUG][smartsavebutton.cpp] Save request for object "StabilizationSettings"
23:41:56[DEBUG][smartsavebutton.cpp] Sending object to remote end -  "ActuatorSettings"
23:41:57[DEBUG][smartsavebutton.cpp] Object upload error: "ActuatorSettings"
23:41:57[DEBUG]RESULT "Objects not uploaded:\nActuatorSettings\n" () () ("ActuatorSettings")
```

Values do not get saved, and things don't seem to work right in general until I power cycle and reconnect.

**Comment by mlyle** [comment]
Conclusion was bad hardware somewhere-- this particular setup didn't work at 115.2k.
