### ISSUE TITLE
FlySky i-bus protocol support

### ISSUE THREAD

**Issue by fujin** [d-ronin/dRonin#988]
- Seen in version (release version or githash): 
  All
- On flight controller (if applicable):
  All

Issue details:
FlySky i-bus protocol is not available under serial port options. No FlySky i-bus protocol appears to be implemented. User with FlySky i-bus protocol radio only cannot make use of dRonin, requires switching to PPM or changing radio system.

**Comment by fujin** [comment]
I have heard that it may be possible to use `ni-sbus` for this, but haven't investigated at all. I am looking at getting some i-bus gear from local supplier, it comes up pretty often in our beginner groups.

**Comment by dustin** [comment]
From what I can tell, it's very different from s.bus.  The CF reverse engineering project is the closest thing I can find to a protocol spec: https://github.com/cleanflight/cleanflight/issues/1125 (I guess spec availability is a similarity to s.bus).

**Comment by tracernz** [comment]
https://github.com/multiwii/baseflight/pull/241

**Comment by bazyl78** [comment]
This would be really helpfull. There is arduino code ibus2ppm if it helps.

**Comment by tracernz** [comment]
@bazyl78 Check out #991

**Comment by bazyl78** [comment]
Great man :)
