### ISSUE TITLE
How Vibration Analisys works?

### ISSUE THREAD

**Issue by szepnorbee** [d-ronin/dRonin#992]
Latest public version on CC3D.

Hi! How Vibration Analisys works? I've enabled the modul, but remains grayed out. That does not work? Or hardware limitations with the CC3D?

**Comment by tracernz** [comment]
Not possible on CC3D or Naze sorry. Resources (RAM and flash) are too limited. It would be nice to indicate this better in GCS, which is the subject of #786.
