### ISSUE TITLE
Reverse motor directions Quad X motor layout

### ISSUE THREAD

**Issue by emil-nasso** [d-ronin/dRonin#995]
Is it possible to set up a Quad X motor layout with all motor directions reversed with dRonin?

There are two benefits to this, as I see it:
- If you fly into grass/vegetation, it will be thrown away from the camera instead on spraying the lens with chopped up grass. :) I can't be the only one that sucks at racing and spend way too much time in tall grass and has a frame/camera that is completely covered in grass from time to time? ;)
- If you hit something with a prop (for example a race gate) the prop rotates "with the collision" instead of rotating into the item you collide with. This could perhaps help a bit with recovery but primarily, it should be a bit more friendly to the motors.

Is there a way to do this in dRonin?

Being able to choose "Quad X - reversed direction" frame type would be a really cool feature, in my opinion!

**Comment by tracernz** [comment]
Already been possible for many years. ;-)
![screenshot from 2016-05-16 06-33-10 png](https://cloud.githubusercontent.com/assets/9995998/15276042/6dd29c68-1b30-11e6-8804-d6aa93e670e6.png)

**Comment by emil-nasso** [comment]
Holy shit. I'm embarrassed, and slightly blind, apparently.... :) Thanks for pointing that out.

Move along, nothing to see here.

**Comment by tracernz** [comment]
No problem! :-)
