### ISSUE TITLE
Starting OSX GCS with revo already plugged in does not autoconnect successfully

### ISSUE THREAD

**Issue by mlyle** [d-ronin/dRonin#998]
- Seen in version (release version or githash): recent next 
- On flight controller (if applicable): Revo

Issue details:

Need to not forget this; saw this 2-3 times in a row on my imac; need to investigate.

**Comment by fujin** [comment]
I have 2x revo now, will try to repro. Do you think it is OSX specific?

**Comment by mlyle** [comment]
Yes, I think it's OSX specific.  No repro on Sparky 2.1 on current next.  Going to try revo now.

**Comment by mlyle** [comment]
No repro on Revo on current next.

**Comment by mlyle** [comment]
NoRepro.
