### ISSUE TITLE
ADC RSSI only works for ADC0 and ADC1

### ISSUE THREAD

**Issue by mluessi** [d-ronin/dRonin#999]
For some reason, analog RSSI only works for the first two ADC inputs. Tested on Brain and RE1. The same pin / ADC works in the battery module. 

Not sure what the reason is.

**Comment by mluessi** [comment]
Also confirmed on Sparky2

**Comment by tracernz** [comment]
Same code, with the exception of the scaling, is used by battery (GetChannelVolt) and RSSI(GetChannelRaw).
https://github.com/d-ronin/dRonin/blob/next/flight/PiOS/Common/pios_adc.c#L184-L229

**Comment by mluessi** [comment]
@tracernz found the problem: When selecting "ADC0", the GCS sets the `RssiChannelNumber` to 1 instead of 0, so the ADC inputs are always 1 off. Note that this is also true for other RSSI input types. I suggest we remove the "Disabled" option from the combo box, as it is redundant with RSSI type `None`. WDYT?

**Comment by tracernz** [comment]
Good catch. The "Disabled" option applies to all instances of InputChannelForm, and special-casing RSSI would make it inconsistent with the other channel types. We should just subtract 1 I think?

**Comment by mluessi** [comment]
@tracernz yes, your solution is better. For other RSSI types it was actually correct as for the receiver types channel 0 means disabled.
